with source as (
    select * from {{ source('EI_RDM','prc_file_supplier_dnb_stg') }}
    WHERE SOURCE_SYSTEM = '{{env_var("DBT_SOURCE_SYSTEM")}}'
),
renamed as (
    select
        CAST (ALTERNATE_SUPPLIER_NUMBER      AS VARCHAR(256)) AS ALTERNATE_SUPPLIER_NUMBER,
        CAST (SOURCE_SYSTEM                  AS VARCHAR(256)) AS SOURCE_SYSTEM,
        CAST (SOURCE_SYSTEM_ADDRESS_NUMBER   AS VARCHAR(256)) AS SOURCE_SYSTEM_ADDRESS_NUMBER,
        CAST (SUPPLIER_NAME                  AS VARCHAR(256)) AS SUPPLIER_NAME,
        CAST (ADDRESS_LINE_1                 AS VARCHAR(256)) AS ADDRESS_LINE_1,
        CAST (ADDRESS_LINE_2                 AS VARCHAR(256)) AS ADDRESS_LINE_2,
        CAST (SUPPLIER_TYPE                  AS VARCHAR(256)) AS SUPPLIER_TYPE,
        CAST (SUPPLIER_SUBTYPE               AS VARCHAR(256)) AS SUPPLIER_SUBTYPE,
        CAST (D_B_SIC_DESCRIPTION1           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION1,
        CAST (D_B_SIC_DESCRIPTION2           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION2,
        CAST (D_B_SIC_DESCRIPTION3           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION3,
        CAST (D_B_SIC_DESCRIPTION4           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION4,
        CAST (D_B_SIC_DESCRIPTION5           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION5,
        CAST (D_B_SIC_DESCRIPTION6           AS VARCHAR(256)) AS D_B_SIC_DESCRIPTION6,
        CAST (NAICS_DESCRIPTION1             AS VARCHAR(256)) AS NAICS_DESCRIPTION1,
        CAST (NAICS_DESCRIPTION2             AS VARCHAR(256)) AS NAICS_DESCRIPTION2,
        CAST (NAICS_DESCRIPTION3             AS VARCHAR(256)) AS NAICS_DESCRIPTION3,
        CAST (NAICS_DESCRIPTION4             AS VARCHAR(256)) AS NAICS_DESCRIPTION4,
        CAST (NAICS_DESCRIPTION5             AS VARCHAR(256)) AS NAICS_DESCRIPTION5,
        CAST (NAICS_DESCRIPTION6             AS VARCHAR(256)) AS NAICS_DESCRIPTION6,
        CAST (ALASKAN_NATIVE_CORPORATION     AS VARCHAR(256)) AS ALASKAN_NATIVE_CORPORATION,
        CAST (CERTIFIED_SMALLBUSINESS        AS VARCHAR(256)) AS CERTIFIED_SMALLBUSINESS,
        CAST (DISABLED_VET_BUS_ENTERPRISE    AS VARCHAR(256)) AS DISABLED_VET_BUS_ENTERPRISE,
        CAST (DISADVANTAGED_BUS_ENTERPRISE   AS VARCHAR(256)) AS DISADVANTAGED_BUS_ENTERPRISE,
        CAST (DISADVNTGED_VET_ENTERPRISE     AS VARCHAR(256)) AS DISADVNTGED_VET_ENTERPRISE,
        CAST (HIST_BLK_COLL_UNIV_MIN_INSTITN AS VARCHAR(256)) AS HIST_BLK_COLL_UNIV_MIN_INSTITN,
        CAST (HUB_ZONE_CERTIFICATION         AS VARCHAR(256)) AS HUB_ZONE_CERTIFICATION,
        CAST (LABOR_SURPLUS_AREA             AS VARCHAR(256)) AS LABOR_SURPLUS_AREA,
        CAST (MINORITY_BUS_ENTERPRISE        AS VARCHAR(256)) AS MINORITY_BUS_ENTERPRISE,
        CAST (MINORITY_CERTIFICATION_CODE    AS VARCHAR(256)) AS MINORITY_CERTIFICATION_CODE,
        CAST (SERVICE_DISABLED_VET_OWNED     AS VARCHAR(256)) AS SERVICE_DISABLED_VET_OWNED,
        CAST (SMALL_BUSINESS_INDICATOR       AS VARCHAR(256)) AS SMALL_BUSINESS_INDICATOR,
        CAST (SMALL_DISADVANTAGED_BUS        AS VARCHAR(256)) AS SMALL_DISADVANTAGED_BUS,
        CAST (VETERAN_BUS_ENTERPRISE         AS VARCHAR(256)) AS VETERAN_BUS_ENTERPRISE,
        CAST (VETERAN_OWNED_INDICATOR        AS VARCHAR(256)) AS VETERAN_OWNED_INDICATOR,
        CAST (VIETNAM_VETERAN_OWNED          AS VARCHAR(256)) AS VIETNAM_VETERAN_OWNED,
        CAST (WOMAN_OWND_BUS_ENTERPRSE       AS VARCHAR(256)) AS WOMAN_OWND_BUS_ENTERPRSE,
        CAST (WOMAN_OWNED_INDICATOR          AS VARCHAR(256)) AS WOMAN_OWNED_INDICATOR         
    from source
)

select * from renamed