WITH pre_src as 
(
    SELECT 'SUPPLIER' AS GENERIC_ADDRESS_TYPE,* FROM {{ ref('stg_d_wbx_supplier') }}
),

file_supplier as (
    select * from {{ ref('src_prc_file_supplier_dnb_stg') }}
),
conv_supplier_master as (
    select * from {{ ref('conv_dim_wbx_supplier') }}
),
src as
(
select
pre_Src.generic_Address_type,
Company_code,
pre_src.source_system_address_number,  
pre_src.source_system,
pre_src.source_name,
pre_src.source_supplier_type as supplier_type,
pre_src.SUPP_TRANSPORT_MODE as TRANSPORT_MODE,
coalesce(trim(FSP.SUPPLIER_TYPE), pre_src.source_SUPPLIER_TYPE) as PHI_SUPPLIER_TYPE,
FSP.supplier_subtype  as phi_supplier_subtype,
pre_src.address_line_1,
address_type,
address_type_description,
city,
state_province_code,
postal_code,
country_code,
LONG_ADDRESS_NUMBER,
tax_number,
pre_src.SUPP_SHIPPING_TERMS as SHIPPING_TERMS,
supp_payment_terms_code,
payment_instrument_code,
payment_instrument_name,
supp_currency_code,
pre_src.supplier_name,
pre_src.voucher_date,
FSP.HIST_BLK_COLL_UNIV_MIN_INSTITN as "HIST_BLK_COLL-UNIV_MIN_INSTITN",
FSP.DISADVANTAGED_BUS_ENTERPRISE,
FSP.DISABLED_VET_BUS_ENTERPRISE,
FSP.MINORITY_CERTIFICATION_CODE,
FSP.ALASKAN_NATIVE_CORPORATION,
FSP.DISADVNTGED_VET_ENTERPRISE,
FSP.SERVICE_DISABLED_VET_OWNED,
FSP.WOMAN_OWND_BUS_ENTERPRSE as  "WOMAN-OWND_BUS_ENTERPRSE",
FSP.ALTERNATE_SUPPLIER_NUMBER,
FSP.SMALL_BUSINESS_INDICATOR,
FSP.HUB_ZONE_CERTIFICATION as  "HUB-ZONE_CERTIFICATION",
FSP.CERTIFIED_SMALLBUSINESS,
FSP.MINORITY_BUS_ENTERPRISE,
FSP.SMALL_DISADVANTAGED_BUS,
FSP.VETERAN_OWNED_INDICATOR,
FSP.WOMAN_OWNED_INDICATOR as "WOMAN-OWNED_INDICATOR",
FSP.VETERAN_BUS_ENTERPRISE,
FSP.D_B_SIC_DESCRIPTION1 as "D&B_SIC_DESCRIPTION1",
FSP.D_B_SIC_DESCRIPTION2 as "D&B_SIC_DESCRIPTION2",
FSP.D_B_SIC_DESCRIPTION3 as "D&B_SIC_DESCRIPTION3",
FSP.D_B_SIC_DESCRIPTION4 as "D&B_SIC_DESCRIPTION4",
FSP.D_B_SIC_DESCRIPTION5 as "D&B_SIC_DESCRIPTION5",
FSP.D_B_SIC_DESCRIPTION6 as "D&B_SIC_DESCRIPTION6",
FSP.VIETNAM_VETERAN_OWNED,
FSP.NAICS_DESCRIPTION1,
FSP.NAICS_DESCRIPTION2,
FSP.NAICS_DESCRIPTION3,
FSP.NAICS_DESCRIPTION4,
FSP.NAICS_DESCRIPTION5,
FSP.NAICS_DESCRIPTION6,
FSP.LABOR_SURPLUS_AREA,
date_inserted,
date_updated
from pre_src
LEFT JOIN file_supplier FSP ON pre_SRC.SOURCE_SYSTEM_ADDRESS_NUMBER = FSP.SOURCE_SYSTEM_ADDRESS_NUMBER
),



normalize_fields as (
    select
        SRC.SOURCE_SYSTEM,
        SRC.GENERIC_ADDRESS_TYPE,
        company_code,
        NVL (TO_CHAR(SOURCE_SYSTEM_ADDRESS_NUMBER_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SOURCE_SYSTEM_ADDRESS_NUMBER)) AS SOURCE_SYSTEM_ADDRESS_NUMBER,
        NVL (TO_CHAR(ADDRESS_TYPE_DESCRIPTION_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.ADDRESS_TYPE))           AS ADDRESS_TYPE_DESCRIPTION,
        NVL (TO_CHAR(PAYMENT_INSTRUMENT_CODE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.PAYMENT_INSTRUMENT_CODE)) AS PAYMENT_INSTRUMENT_CODE,
        NVL (TO_CHAR(PAYMENT_INSTRUMENT_NAME_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.PAYMENT_INSTRUMENT_NAME)) AS PAYMENT_INSTRUMENT_NAME,
        NVL (TO_CHAR(PAYMENT_TERMS_CODE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SUPP_PAYMENT_TERMS_CODE))      AS SUPP_PAYMENT_TERMS_CODE,
        NVL (TO_CHAR(PAYMENT_TERMS_DESC_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SUPP_PAYMENT_TERMS_CODE))      AS PAYMENT_TERMS_DESCRIPTION,
        NVL (TO_CHAR(STATE_PROVINCE_CODE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.STATE_PROVINCE_CODE))         AS STATE_PROVINCE_CODE,
        NVL (TO_CHAR(SUPP_CURRENCY_CODE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SUPP_CURRENCY_CODE))           AS SUPP_CURRENCY_CODE,
        NVL (TO_CHAR(STATE_PROVINCE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.STATE_PROVINCE_CODE))              AS STATE_PROVINCE,
        NVL (TO_CHAR(PHI_SUPPLIER_SUBTYPE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.PHI_SUPPLIER_SUBTYPE))       AS PHI_SUPPLIER_SUBTYPE,
        NVL (TO_CHAR(PHI_SUPPLIER_TYPE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.PHI_SUPPLIER_TYPE))             AS PHI_SUPPLIER_TYPE,
        NVL (TO_CHAR(SUPPLIER_TYPE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SUPPLIER_TYPE))                      AS SUPPLIER_TYPE,
        NVL (TO_CHAR(SUPPLIER_NAME_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SUPPLIER_NAME))                     AS SUPPLIER_NAME,
        NVL (TO_CHAR(UNIFIED_SUPPLIER_NAME_LKP.NORMALIZED_VALUE), TO_CHAR(SUPPLIER_NAME))                 AS UNIFIED_SUPPLIER_NAME,
        NVL (TO_CHAR(ADDRESS_TYPE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.ADDRESS_TYPE))                       AS ADDRESS_TYPE,
        NVL (TO_CHAR(COUNTRY_CODE_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.COUNTRY_CODE))                       AS COUNTRY_CODE,
        NVL (TO_CHAR(SOURCE_NAME_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.SOURCE_NAME))                         AS SOURCE_NAME,
        NVL (TO_CHAR(TAX_NUMBER_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.TAX_NUMBER))                           AS TAX_NUMBER,
        NVL (TO_CHAR(COUNTRY_LKP.NORMALIZED_VALUE), TO_CHAR(SRC.COUNTRY_CODE))                            AS COUNTRY,
        SRC.TRANSPORT_MODE,
        SRC.SHIPPING_TERMS,
        SRC.ADDRESS_LINE_1,
        SRC.LONG_ADDRESS_NUMBER,
        SRC.POSTAL_CODE,
        SRC.CITY,
        SRC."HIST_BLK_COLL-UNIV_MIN_INSTITN",
        SRC.DISADVANTAGED_BUS_ENTERPRISE,
        SRC.DISABLED_VET_BUS_ENTERPRISE,
        SRC.MINORITY_CERTIFICATION_CODE,
        SRC.ALASKAN_NATIVE_CORPORATION,
        SRC.DISADVNTGED_VET_ENTERPRISE,
        SRC.SERVICE_DISABLED_VET_OWNED,
        SRC."WOMAN-OWND_BUS_ENTERPRSE",
        SRC.ALTERNATE_SUPPLIER_NUMBER,
        SRC.SMALL_BUSINESS_INDICATOR,
        SRC."HUB-ZONE_CERTIFICATION",
        SRC.CERTIFIED_SMALLBUSINESS,
        SRC.MINORITY_BUS_ENTERPRISE,
        SRC.SMALL_DISADVANTAGED_BUS,
        SRC.VETERAN_OWNED_INDICATOR,
        SRC."WOMAN-OWNED_INDICATOR",
        SRC.VETERAN_BUS_ENTERPRISE,
        SRC."D&B_SIC_DESCRIPTION1",
        SRC."D&B_SIC_DESCRIPTION2",
        SRC."D&B_SIC_DESCRIPTION3",
        SRC."D&B_SIC_DESCRIPTION4",
        SRC."D&B_SIC_DESCRIPTION5",
        SRC."D&B_SIC_DESCRIPTION6",
        SRC.VIETNAM_VETERAN_OWNED,
        SRC.NAICS_DESCRIPTION1,
        SRC.NAICS_DESCRIPTION2,
        SRC.NAICS_DESCRIPTION3,
        SRC.NAICS_DESCRIPTION4,
        SRC.NAICS_DESCRIPTION5,
        SRC.NAICS_DESCRIPTION6,
        SRC.LABOR_SURPLUS_AREA,
        SRC.DATE_INSERTED,
        SRC.DATE_UPDATED,
        SRC.VOUCHER_DATE
      
    from  SRC
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SOURCE_SYSTEM_ADDRESS_NUMBER','UPPER(SRC.SOURCE_SYSTEM_ADDRESS_NUMBER)','SOURCE_SYSTEM_ADDRESS_NUMBER_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','PAYMENT_INSTRUMENT_CODE','UPPER(SRC.PAYMENT_INSTRUMENT_CODE)','PAYMENT_INSTRUMENT_CODE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','PAYMENT_INSTRUMENT_NAME','UPPER(SRC.PAYMENT_INSTRUMENT_NAME)','PAYMENT_INSTRUMENT_NAME_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','ADDRESS_TYPE_DESCRIPTION','UPPER(SRC.ADDRESS_TYPE)','ADDRESS_TYPE_DESCRIPTION_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','PAYMENT_TERMS_CODE','UPPER(SRC.SUPP_PAYMENT_TERMS_CODE)','PAYMENT_TERMS_CODE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','PAYMENT_TERMS_DESC','UPPER(SRC.SUPP_PAYMENT_TERMS_CODE)','PAYMENT_TERMS_DESC_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','STATE_PROVINCE_CODE','UPPER(SRC.STATE_PROVINCE_CODE)','STATE_PROVINCE_CODE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SUPPLIER_SUBTYPE','UPPER(SRC.PHI_SUPPLIER_SUBTYPE)','PHI_SUPPLIER_SUBTYPE_LKP') }} 
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SUPP_CURRENCY_CODE','UPPER(SRC.SUPP_CURRENCY_CODE)','SUPP_CURRENCY_CODE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','UNIFIED_SUPPLIER_NAME','UPPER(SRC.SOURCE_SYSTEM_ADDRESS_NUMBER)','UNIFIED_SUPPLIER_NAME_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','STATE_PROVINCE','UPPER(SRC.STATE_PROVINCE_CODE)','STATE_PROVINCE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SUPPLIER_TYPE','UPPER(SRC.PHI_SUPPLIER_TYPE)','PHI_SUPPLIER_TYPE_LKP') }} 
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SUPPLIER_TYPE','UPPER(SRC.SUPPLIER_TYPE)','SUPPLIER_TYPE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SUPPLIER_NAME','UPPER(SRC.SUPPLIER_NAME)','SUPPLIER_NAME_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','COUNTRY_CODE','UPPER(SRC.COUNTRY_CODE)','COUNTRY_CODE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','ADDRESS_TYPE','UPPER(SRC.ADDRESS_TYPE)','ADDRESS_TYPE_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','SOURCE_NAME','UPPER(SRC.SOURCE_NAME)','SOURCE_NAME_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','TAX_NUMBER','UPPER(SRC.TAX_NUMBER)','TAX_NUMBER_LKP') }}
    LEFT JOIN {{ lkp_normalization('SRC.SOURCE_SYSTEM','ADDRESS_BOOK','COUNTRY','UPPER(COUNTRY_CODE)','COUNTRY_LKP') }}
),

vendors as
(
    select 
{{ dbt_utils.surrogate_key(['SOURCE_SYSTEM','SOURCE_SYSTEM_ADDRESS_NUMBER','GENERIC_ADDRESS_TYPE','COMPANY_CODE']) }} AS SUPPLIER_ADDRESS_NUMBER_GUID,
{{ dbt_utils.surrogate_key(['SOURCE_SYSTEM','COMPANY_CODE',"'COMPANY'"]) }} as COMPANY_ADDRESS_GUID,
* 
from normalize_fields
),

sort_vendor_fields as (
    select
        GENERIC_ADDRESS_TYPE,
        {{ dbt_utils.surrogate_key(['SUPPLIER_ADDRESS_NUMBER_GUID']) }} AS UNIQUE_KEY,
        SOURCE_SYSTEM_ADDRESS_NUMBER,
        COMPANY_CODE,
        COMPANY_ADDRESS_GUID,
        PAYMENT_INSTRUMENT_CODE,
        PAYMENT_INSTRUMENT_NAME,
        UNIFIED_SUPPLIER_NAME,
        PHI_SUPPLIER_SUBTYPE,
        PHI_SUPPLIER_TYPE,
        SOURCE_SYSTEM,
        SUPPLIER_NAME,
        DATE_INSERTED,
        VOUCHER_DATE,
        DATE_UPDATED,
        SUPP_CURRENCY_CODE      AS CURRENCY_CODE,
        SUPP_PAYMENT_TERMS_CODE AS PAYMENT_TERMS_CODE,
        PAYMENT_TERMS_DESCRIPTION,
        SUPPLIER_TYPE           AS SOURCE_SUPPLIER_TYPE,
        NULL                    AS SUPPLIER_ADDRESS_NUMBER_GUID_OLD,
        TRANSPORT_MODE,
        SHIPPING_TERMS,
        SUPPLIER_ADDRESS_NUMBER_GUID,
        ADDRESS_LINE_1,
        ADDRESS_TYPE_DESCRIPTION,
        ADDRESS_TYPE,
        CITY,
        COUNTRY,
        COUNTRY_CODE,
        LONG_ADDRESS_NUMBER,
       POSTAL_CODE,
       SOURCE_NAME,
       STATE_PROVINCE,
       STATE_PROVINCE_CODE,
       TAX_NUMBER
from vendors
    
),

NEW_DIM as (
    select distinct
       A.GENERIC_ADDRESS_TYPE        AS GENERIC_ADDRESS_TYPE,
       NVL (A.SUPPLIER_ADDRESS_NUMBER_GUID_OLD, B.SUPPLIER_ADDRESS_NUMBER_GUID_OLD) AS SUPPLIER_ADDRESS_NUMBER_GUID_OLD,
       A.SUPPLIER_ADDRESS_NUMBER_GUID AS SUPPLIER_ADDRESS_NUMBER_GUID,
       A.SOURCE_SYSTEM_ADDRESS_NUMBER AS SOURCE_SYSTEM_ADDRESS_NUMBER,
       A.PAYMENT_INSTRUMENT_CODE      AS PAYMENT_INSTRUMENT_CODE,
       A.PAYMENT_INSTRUMENT_NAME      AS PAYMENT_INSTRUMENT_NAME,
       A.UNIFIED_SUPPLIER_NAME        AS UNIFIED_SUPPLIER_NAME,
       A.SOURCE_SUPPLIER_TYPE         AS SOURCE_SUPPLIER_TYPE,
       A.PHI_SUPPLIER_SUBTYPE         AS PHI_SUPPLIER_SUBTYPE,
       A.PAYMENT_TERMS_CODE           AS PAYMENT_TERMS_CODE,
       A.PAYMENT_TERMS_DESCRIPTION    AS PAYMENT_TERMS_DESCRIPTION,
       A.PHI_SUPPLIER_TYPE            AS PHI_SUPPLIER_TYPE,
       A.TRANSPORT_MODE               AS TRANSPORT_MODE,
       A.SHIPPING_TERMS               AS SHIPPING_TERMS,
       A.SOURCE_SYSTEM                AS SOURCE_SYSTEM,
       A.SUPPLIER_NAME                AS SUPPLIER_NAME,
       A.CURRENCY_CODE                AS CURRENCY_CODE,
       A.DATE_INSERTED                AS DATE_INSERTED,
       A.DATE_UPDATED                 AS DATE_UPDATED,
       A.VOUCHER_DATE                 AS VOUCHER_DATE,
       A.UNIQUE_KEY                   AS UNIQUE_KEY,
       A.COMPANY_CODE                 AS COMPANY_CODE,
       A.COMPANY_ADDRESS_GUID         AS COMPANY_ADDRESS_GUID,
       A.ADDRESS_LINE_1               as ADDRESS_LINE_1,
       A.ADDRESS_TYPE_DESCRIPTION     as ADDRESS_TYPE_DESCRIPTION,
       A.ADDRESS_TYPE                 as ADDRESS_TYPE,
       A.CITY                         as CITY,
       A.COUNTRY                      as COUNTRY,
       A.COUNTRY_CODE                 as COUNTRY_CODE,
       A.LONG_ADDRESS_NUMBER          as LONG_ADDRESS_NUMBER,
       A.POSTAL_CODE                  as POSTAL_CODE,
       A.SOURCE_NAME                  as SOURCE_NAME,
       A.STATE_PROVINCE               as STATE_PROVINCE,
       A.STATE_PROVINCE_CODE          as STATE_PROVINCE_CODE,
       A.TAX_NUMBER                   as TAX_NUMBER
    from sort_vendor_fields A
    LEFT JOIN conv_supplier_master B
    ON A.SUPPLIER_ADDRESS_NUMBER_GUID = B.SUPPLIER_ADDRESS_NUMBER_GUID
),

OLD_DIM AS
(
        select distinct
       A.GENERIC_ADDRESS_TYPE        AS GENERIC_ADDRESS_TYPE,
       A.SUPPLIER_ADDRESS_NUMBER_GUID_OLD AS SUPPLIER_ADDRESS_NUMBER_GUID_OLD,
       A.SUPPLIER_ADDRESS_NUMBER_GUID AS SUPPLIER_ADDRESS_NUMBER_GUID,
       A.SOURCE_SYSTEM_ADDRESS_NUMBER AS SOURCE_SYSTEM_ADDRESS_NUMBER,
       A.PAYMENT_INSTRUMENT_CODE      AS PAYMENT_INSTRUMENT_CODE,
       A.PAYMENT_INSTRUMENT_NAME      AS PAYMENT_INSTRUMENT_NAME,
       A.UNIFIED_SUPPLIER_NAME        AS UNIFIED_SUPPLIER_NAME,
       A.SOURCE_SUPPLIER_TYPE         AS SOURCE_SUPPLIER_TYPE,
       A.PHI_SUPPLIER_SUBTYPE         AS PHI_SUPPLIER_SUBTYPE,
       A.PAYMENT_TERMS_CODE           AS PAYMENT_TERMS_CODE,
       A.PAYMENT_TERMS_DESCRIPTION    AS PAYMENT_TERMS_DESCRIPTION,
       A.PHI_SUPPLIER_TYPE            AS PHI_SUPPLIER_TYPE,
       A.TRANSPORT_MODE               AS TRANSPORT_MODE,
       A.SHIPPING_TERMS               AS SHIPPING_TERMS,
       A.SOURCE_SYSTEM                AS SOURCE_SYSTEM,
       A.SUPPLIER_NAME                AS SUPPLIER_NAME,
       A.CURRENCY_CODE                AS CURRENCY_CODE,
       A.DATE_INSERTED                AS DATE_INSERTED,
       A.DATE_UPDATED                 AS DATE_UPDATED,
       A.VOUCHER_DATE                 AS VOUCHER_DATE,
       A.UNIQUE_KEY                   AS UNIQUE_KEY,
       A.COMPANY_CODE                 AS COMPANY_CODE,
       A.COMPANY_ADDRESS_GUID         AS COMPANY_ADDRESS_GUID,
       NULL                           AS ADDRESS_LINE_1,
       NULL           as ADDRESS_TYPE_DESCRIPTION,
       NULL           as ADDRESS_TYPE,
       NULL           as CITY,
       NULL           as COUNTRY,
       NULL           as COUNTRY_CODE,
       NULL           as LONG_ADDRESS_NUMBER,
       NULL           as POSTAL_CODE,
       NULL           as SOURCE_NAME,
       NULL           as STATE_PROVINCE,
       NULL           as STATE_PROVINCE_CODE,
       NULL           as TAX_NUMBER
    from conv_supplier_master A
    LEFT JOIN sort_vendor_fields B
    ON A.SUPPLIER_ADDRESS_NUMBER_GUID = B.SUPPLIER_ADDRESS_NUMBER_GUID
    WHERE B.SUPPLIER_ADDRESS_NUMBER_GUID IS NULL
),

FINAL AS
(Select * from NEW_DIM
UNION
Select * from OLD_DIM)

select * from final