{{ config(materialized=env_var("DBT_MAT_VIEW"), tags=["finance","gl","gl_trans"]) }}

with cte_fct_wbx_fin_gl_trans as (select * from {{ ref('fct_wbx_fin_gl_trans') }}),
cte_hirerarchy as (select * from {{ ref('xref_wbx_hierarchy') }}),
cte_Account as (select * from {{ ref('dim_wbx_account') }}),
cte_plant_dc as (select * from {{ ref('dim_wbx_plant_dc') }}),
cte_company as (select * from {{ ref('dim_wbx_company') }}),
cte_item_ext as (select * from {{ ref('dim_wbx_item_ext') }}),
cte_customer_ext as (select * from {{ ref('dim_wbx_customer_ext') }}),
cte_final as 
(
    SELECT
GL.SOURCE_SYSTEM,
GL.DOCUMENT_COMPANY,
GL.SOURCE_DOCUMENT_TYPE,
GL.DOCUMENT_TYPE,
GL.DOCUMENT_NUMBER,
GL.GL_DATE,
GL.SOURCE_BUSINESS_UNIT_CODE,
GL.PAYMENT_TRANS_DATE,
GL.BASE_CURRENCY,
GL.TARGET_ACCOUNT_IDENTIFIER,
GL.GL_POSTED_FLAG,
GL.BATCH_DATE,
GL.COMPANY_CODE,
GL.SOURCE_OBJECT_ID,
GL.SOURCE_COMPANY_CODE,
GL.TRANSACTION_CURRENCY,
GL.INVOICE_DATE,
GL.ACCOUNT_CAT21_CODE,
GL.SOURCE_DATE_UPDATED,
GL.EXPLANATION_TXT,
GL.REMARK_TXT,
GL.REFERENCE1_TXT,
GL.REFERENCE2_TXT,
GL.REFERENCE3_TXT,
GL.DEPARTMENT,
GL.TXN_CONV_RT,
GL.PHI_CURRENCY,
GL.PHI_CONV_RT,
GL.PCOMP_CURRENCY,
GL.PCOMP_CONV_RT,
GL.PRODUCT_DIM,
GL.CUSTOMER_DIM,
GL.OC_TXN_LEDGER_AMT,
GL.OC_BASE_LEDGER_AMT,
GL.OC_PCOMP_LEDGER_AMT,
GL.OC_PHI_LEDGER_AMT,
GL.JOURNAL_CATEGORY,
ACCT.ACCOUNT_DESCRIPTION,
HR_ACCT.DESC_1 AS ACCOUNT_HIER_LVL1,
HR_ACCT.DESC_2 AS ACCOUNT_HIER_LVL2,
HR_ACCT.DESC_3 AS ACCOUNT_HIER_LVL3,
HR_ACCT.DESC_4 AS ACCOUNT_HIER_LVL4,
HR_ACCT.DESC_5 AS ACCOUNT_HIER_LVL5,
HR_ACCT.DESC_6 AS ACCOUNT_HIER_LVL6,
HR_ACCT.DESC_7 AS ACCOUNT_HIER_LVL7,
HR_ACCT.DESC_8 AS ACCOUNT_HIER_LVL8,
HR_ACCT.DESC_9 AS ACCOUNT_HIER_LVL9,
PLT.BUSINESS_UNIT_NAME,
CMP.COMPANY_NAME,
PC_DESC.PRODUCT_CLASS_DESC,
TT_DESC.TRADE_TYPE_DESC
FROM cte_fct_wbx_fin_gl_trans GL 
LEFT JOIN cte_hirerarchy HR_ACCT 
    ON GL.SOURCE_BUSINESS_UNIT_CODE||'|'||GL.SOURCE_OBJECT_ID = HR_ACCT.TAGETIK_ACCOUNT
LEFT JOIN cte_Account ACCT 
    ON GL.ACCOUNT_GUID = ACCT.ACCOUNT_GUID
    AND GL.SOURCE_SYSTEM = ACCT.SOURCE_SYSTEM
LEFT JOIN cte_plant_dc PLT  
    ON PLT.PLANTDC_ADDRESS_GUID = GL.BUSINESS_UNIT_ADDRESS_GUID
    AND PLT.SOURCE_SYSTEM = GL.SOURCE_SYSTEM
LEFT JOIN cte_company CMP 
    ON CMP.COMPANY_CODE = GL.COMPANY_CODE    
    AND CMP.SOURCE_SYSTEM = GL.SOURCE_SYSTEM
LEFT JOIN (SELECT PRODUCT_CLASS_CODE, PRODUCT_CLASS_DESC FROM cte_item_ext 
WHERE PRODUCT_CLASS_CODE <> '' GROUP BY PRODUCT_CLASS_CODE, PRODUCT_CLASS_DESC) PC_DESC
    ON GL.PRODUCT_DIM = PC_DESC.PRODUCT_CLASS_CODE
LEFT JOIN (SELECT TRADE_TYPE_CODE, TRADE_TYPE_DESC FROM cte_customer_ext  
WHERE TRADE_TYPE_CODE <> '' GROUP BY TRADE_TYPE_CODE, TRADE_TYPE_DESC) TT_DESC
    ON RIGHT(GL.CUSTOMER_DIM,2) = TT_DESC.TRADE_TYPE_CODE    
WHERE upper(HR_ACCT.DESC_5) = 'GCAT'
)
select 
    SOURCE_SYSTEM,
	DOCUMENT_COMPANY,
	SOURCE_DOCUMENT_TYPE,
	DOCUMENT_TYPE,
	DOCUMENT_NUMBER,
	GL_DATE,
	SOURCE_BUSINESS_UNIT_CODE,
	PAYMENT_TRANS_DATE,
	BASE_CURRENCY,
	TARGET_ACCOUNT_IDENTIFIER,
	GL_POSTED_FLAG,
	BATCH_DATE,
	COMPANY_CODE,
	SOURCE_OBJECT_ID,
	SOURCE_COMPANY_CODE,
	TRANSACTION_CURRENCY,
	INVOICE_DATE,
	ACCOUNT_CAT21_CODE,
	SOURCE_DATE_UPDATED,
	EXPLANATION_TXT,
	REMARK_TXT,
	REFERENCE1_TXT,
	REFERENCE2_TXT,
	REFERENCE3_TXT,
	DEPARTMENT,
	TXN_CONV_RT,
	PHI_CURRENCY,
	PHI_CONV_RT,
	PCOMP_CURRENCY,
	PCOMP_CONV_RT,
	PRODUCT_DIM,
	CUSTOMER_DIM,
	OC_TXN_LEDGER_AMT,
	OC_BASE_LEDGER_AMT,
	OC_PCOMP_LEDGER_AMT,
	OC_PHI_LEDGER_AMT,
	JOURNAL_CATEGORY,
	ACCOUNT_DESCRIPTION,
	ACCOUNT_HIER_LVL1,
	ACCOUNT_HIER_LVL2,
	ACCOUNT_HIER_LVL3,
	ACCOUNT_HIER_LVL4,
	ACCOUNT_HIER_LVL5,
	ACCOUNT_HIER_LVL6,
	ACCOUNT_HIER_LVL7,
	ACCOUNT_HIER_LVL8,
	ACCOUNT_HIER_LVL9,
	BUSINESS_UNIT_NAME,
	COMPANY_NAME,
	PRODUCT_CLASS_DESC,
	TRADE_TYPE_DESC
from cte_final