{{ config(materialized=env_var("DBT_MAT_VIEW"), tags=["sales","pricing","sales_pricing"]) }}


with cte_sls_wtx_slsuber_fact as (select * from {{ ref('fct_wbx_sls_uber') }}), --R_EI_SYSADM.sls_wtx_slsuber_fact
cte_customer as (select * from {{ ref('dim_wbx_customer') }}),
cte_item as (select * from {{ ref('dim_wbx_item') }}),
cte_customer_Ext as (select * from {{ ref('dim_wbx_customer_ext') }}),
cte_item_ext as (select * from {{ ref('dim_wbx_item_ext') }}),
cte_sls_promo_dim as (select * from {{ ref('dim_wbx_promo') }}), --EI_RDM.SLS_WTX_PROMO_DIM

cte_v_sls_wtx_promo_summary as (select * from {{ ref('v_sls_wtx_promo_summary') }}),
cte_v_wtx_cust_planning as --cte for the view POSTSNOWP.EI_RDM.v_wtx_cust_planning
(
    SELECT * from {{ref('dim_wbx_cust_planning')}}

),
cte_final as 
(
    select * from (select
ub.SOURCE_ITEM_IDENTIFIER,
CALENDAR_DATE,
SOURCE_CONTENT_FILTER,
ITM_EXT.DESCRIPTION as ITM_DESCRIPTION,
ITM_EXT.ITEM_TYPE, 
ITM_EXT.BRANDING_DESC as BRANDING_DESCRIPTION,
ITM_EXT.PRODUCT_CLASS_DESC as PRODUCT_CLASS_DESCRIPTION,
ITM_EXT.SUB_PRODUCT_DESC as SUB_PRODUCT_DESCRIPTION,
ITM_EXT.STRATEGIC_DESC as STRATEGIC_DESCRIPTION,
ITM_EXT.POWER_BRAND_DESC as POWER_BRAND_DESC,
ITM_EXT.MANUFACTURING_GROUP_DESC as MANUFACTURING_GROUP_DESCRIPTION,
ITM_EXT.CATEGORY_DESC as CATEGORY_DESCRIPTION,
ITM_EXT.PACK_SIZE_DESC as PACK_SIZE_DESCRIPTION, 
ITM_EXT.SUB_CATEGORY_DESC as SUB_CATEGORY_DESCRIPTION,
ITM_EXT.PROMO_TYPE_DESC as PROMO_TYPE_DESCRIPTION,
COALESCE(CUST_EXT.TRADE_CLASS_DESC, PLAN.TRADE_CLASS) AS TRADE_CLASS,
COALESCE(CUST_EXT.TRADE_GROUP_DESC, PLAN.TRADE_GROUP) AS TRADE_GROUP,
COALESCE(CUST_EXT.TRADE_TYPE_DESC, PLAN.TRADE_TYPE) AS TRADE_TYPE,
COALESCE(CUST_EXT.TRADE_SECTOR_DESC, PLAN.TRADE_SECTOR_DESC) AS TRADE_SECTOR,
COALESCE(CUST_EXT.SUB_MARKET_DESC, PLAN.SUB_MARKET) AS SUBMARKET,
CUST.CUSTOMER_NAME AS CUSTOMER_BRANCH_NAME,
CUST.BILL_NAME AS CUSTOMER_ACCOUNT_NAME,
UB.DOCUMENT_COMPANY,
TRM_OTHER_DIRECT_PERC,
TRM_SNAPSHOT_DATE,
PROMO_SNAPSHOT_DATE,
PRM_ISPROMOSKU,
PROMO_STAT_DESC,
PRM_SI_T_VOL_CSE,
UB.PRM_SI_T_VOL_CSE * ITM_EXT.CONSUMER_UNITS as PRM_SI_T_VOL_CU,
PRM_SI_T_VOL_KG,
PRM_ACTUALS_AP_AVP_DISC,
PRM_FORECAST_AP_AVP_DISC,
PRM_ACTUALS_AP_DIRECT_SHOPPER_MARKETING,
PRM_FORECAST_AP_DIRECT_SHOPPER_MARKETING,
PRM_ACTUALS_AP_EARLY_SETTLEMENT_DISC,
PRM_FORECAST_AP_EARLY_SETTLEMENT_DISC,
PRM_ACTUALS_AP_EVERYDAY_LOW_PRICES,
PRM_FORECAST_AP_EVERYDAY_LOW_PRICES,
PRM_ACTUALS_AP_OFF_INVOICE_DISC,
PRM_FORECAST_AP_OFF_INVOICE_DISC, 
PRM_ACTUALS_AP_OTHER_DIRECT_PAYMENTS, 
PRM_FORECAST_AP_OTHER_DIRECT_PAYMENTS, 
PRM_ACTUALS_AP_PROMO_FIXED_FUNDING, 
PRM_FORECAST_AP_PROMO_FIXED_FUNDING, 
PRM_ACTUALS_AP_RANGE_SUPPORT_ALLOWANCE, 
PRM_FORECAST_AP_RANGE_SUPPORT_ALLOWANCE, 
PRM_ACTUALS_AP_RETRO, 
PRM_FORECAST_AP_RETRO,
PRM_ACTUALS_AP_GROWTH_INCENTIVES, 
PRM_FORECAST_AP_GROWTH_INCENTIVES,
CY_BASE_RPT_GRS_AMT, 
FCF_AP_GROSS_SELLING_VALUE, 
FCF_TOT_VOL_CA, 
UB.FCF_TOT_VOL_CA * ITM_EXT.CONSUMER_UNITS as FCF_TOT_VOL_CU, 
FCF_TOT_VOL_KG, 
FCF_TOT_VOL_UL, 
FCF_TOT_VOL_CA * ITM_EXT.CONSUMER_UNITS_IN_TRADE_UNITS as FCF_TOT_VOL_PK,
CY_SHIPPED_CA_QUANTITY, 
UB.CY_SHIPPED_CA_QUANTITY * ITM_EXT.CONSUMER_UNITS as CY_SHIPPED_CU_QUANTITY, 
UB.CY_SHIPPED_CA_QUANTITY * ITM_EXT.CONSUMER_UNITS_IN_TRADE_UNITS AS CY_SHIPPED_PK_QUANTITY,
CY_SHIPPED_UL_QUANTITY,
CY_SHIPPED_KG_QUANTITY,
CY_GL_BASE_PERMD_RNG_SPT,
CY_GL_BASE_PERMD_EDLP,
CY_GL_BASE_PERMD_CSH_DISC,
CY_GL_BASE_PERMD_RSA_INCT,
CY_GL_BASE_TRADE_AVP,
FCF_AP_NET_SALES_VALUE,
SNAPSHOT_FORECAST_DATE,
COALESCE(CUST_EXT.MARKET_DESC, PLAN.MARKET) AS MARKET,
UB.PRM_SI_T_VOL_CSE * ITM_EXT.CONSUMER_UNITS_IN_TRADE_UNITS AS PRM_SI_T_VOL_PK
FROM cte_sls_wtx_slsuber_fact UB
LEFT JOIN cte_customer CUST
    ON UB.CUSTOMER_ADDR_NUMBER_GUID = CUST.CUSTOMER_ADDRESS_NUMBER_GUID

LEFT JOIN (SELECT *  FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY SOURCE_SYSTEM, ITEM_GUID order by DESCRIPTION) rowNum
            FROM (SELECT SOURCE_SYSTEM, ITEM_GUID, DESCRIPTION FROM cte_item 
                WHERE SOURCE_SYSTEM = '{{env_var('DBT_SOURCE_SYSTEM')}}' GROUP BY SOURCE_SYSTEM, ITEM_GUID, DESCRIPTION) ) X WHERE rowNum=1) ITM
    ON UB.SOURCE_SYSTEM = ITM.SOURCE_SYSTEM
    AND UB.ITEM_GUID = ITM.ITEM_GUID

LEFT JOIN cte_customer_Ext CUST_EXT
    ON UB.CUSTOMER_ADDR_NUMBER_GUID = CUST_EXT.CUSTOMER_ADDRESS_NUMBER_GUID

LEFT JOIN (SELECT SOURCE_SYSTEM, SOURCE_ITEM_IDENTIFIER, MAX(DUMMY_PRODUCT_FLAG) AS DUMMY_PRODUCT_FLAG, MAX(ITEM_TYPE) AS ITEM_TYPE, MAX(BRANDING_DESC) AS BRANDING_DESC, MAX(PRODUCT_CLASS_DESC) AS PRODUCT_CLASS_DESC, MAX(SUB_PRODUCT_DESC) AS SUB_PRODUCT_DESC
            , MAX(STRATEGIC_DESC) AS STRATEGIC_DESC, MAX(POWER_BRAND_DESC) AS POWER_BRAND_DESC, MAX(MANUFACTURING_GROUP_DESC) AS MANUFACTURING_GROUP_DESC
            , MAX(CATEGORY_DESC) AS CATEGORY_DESC, MAX(PACK_SIZE_DESC) AS PACK_SIZE_DESC, MAX(SUB_CATEGORY_DESC) AS SUB_CATEGORY_DESC
            , MAX(CONSUMER_UNITS_IN_TRADE_UNITS) AS CONSUMER_UNITS_IN_TRADE_UNITS, MAX(PROMO_TYPE_DESC) AS PROMO_TYPE_DESC, MAX(CONSUMER_UNITS) AS CONSUMER_UNITS
			, MAX(DESCRIPTION) AS DESCRIPTION
            FROM cte_item_ext 
            GROUP BY SOURCE_SYSTEM, SOURCE_ITEM_IDENTIFIER) ITM_EXT
    ON UB.SOURCE_SYSTEM = ITM_EXT.SOURCE_SYSTEM
    AND UB.SOURCE_ITEM_IDENTIFIER = ITM_EXT.SOURCE_ITEM_IDENTIFIER
   LEFT JOIN cte_sls_promo_dim PROMO_DIM
    ON UB.PROMO_GUID = PROMO_DIM.PROMO_GUID
    AND UB.PROMO_SNAPSHOT_DATE = PROMO_DIM.SNAPSHOT_DATE
	
	LEFT JOIN cte_v_wtx_cust_planning PLAN
    ON TRIM(UB.PLAN_SOURCE_CUSTOMER_CODE) = TRIM(PLAN.TRADE_TYPE_CODE)
    and UB.DOCUMENT_COMPANY=PLAN.company_code
/*    
LEFT JOIN EI_RDM.SLS_WTX_MAPE_TARGETS MAPE_TGT
    ON COALESCE(CUST_EXT.TRADE_TYPE_CODE, PLAN.TRADE_TYPE_CODE) = TRIM(MAPE_TGT.TRADE_TYPE_CODE)
    AND UB.CALENDAR_DATE BETWEEN MAPE_TGT.EFF_DATE AND MAPE_TGT.EXPIR_DATE */
    
    WHERE UB.CALENDAR_DATE>= DATEADD('month',-27,DATE_TRUNC('year',CURRENT_DATE))) where SOURCE_CONTENT_FILTER in ('ACTUALS','TERMS','FORECAST') 
    and (SNAPSHOT_FORECAST_DATE>=(SELECT DATEADD(DAY,-21,MAX(SNAPSHOT_FORECAST_DATE)) from cte_sls_wtx_slsuber_fact) or SNAPSHOT_FORECAST_DATE is null)
	
	
UNION ALL
	
select
SOURCE_ITEM_IDENTIFIER,
CALENDAR_DATE,
'PROMOTIONS' as SOURCE_CONTENT_FILTER,
DESCRIPTION,
ITEM_TYPE,
BRANDING_DESC,
PRODUCT_CLASS_DESC,
SUB_PRODUCT_DESC,
STRATEGIC_DESC,
POWER_BRAND_DESC,
MANUFACTURING_GROUP_DESC,
CATEGORY_DESC,
PACK_SIZE_DESC,
SUB_CATEGORY_DESC,
PROMO_TYPE_DESC,
TRADE_CLASS,
TRADE_GROUP,
TRADE_TYPE,
TRADE_SECTOR,
SUBMARKET,
NULL,
NULL,
NULL,
NULL,
NULL,
SNAPSHOT_DATE,
ISPROMOSKU,
PROMO_STAT_DESC,
SI_T_VOL_CSE,
PRM_SI_T_VOL_CU,
SI_T_VOL_KG,
ACTUALS_AP_AVP_DISC,
FORECAST_AP_AVP_DISC,
ACTUALS_AP_DIRECT_SHOPPER_MARKETING,
FORECAST_AP_DIRECT_SHOPPER_MARKETING,
ACTUALS_AP_EARLY_SETTLEMENT_DISC,
FORECAST_AP_EARLY_SETTLEMENT_DISC,
ACTUALS_AP_EVERYDAY_LOW_PRICES,
FORECAST_AP_EVERYDAY_LOW_PRICES,
ACTUALS_AP_OFF_INVOICE_DISC,
FORECAST_AP_OFF_INVOICE_DISC,
ACTUALS_AP_OTHER_DIRECT_PAYMENTS,
FORECAST_AP_OTHER_DIRECT_PAYMENTS,
ACTUALS_AP_PROMO_FIXED_FUNDING,
FORECAST_AP_PROMO_FIXED_FUNDING,
ACTUALS_AP_RANGE_SUPPORT_ALLOWANCE,
FORECAST_AP_RANGE_SUPPORT_ALLOWANCE,
ACTUALS_AP_RETRO,
FORECAST_AP_RETRO,
ACTUALS_AP_GROWTH_INCENTIVES,
FORECAST_AP_GROWTH_INCENTIVES,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
PRM_SI_T_VOL_PK
from cte_v_sls_wtx_promo_summary where SNAPSHOT_DATE>=(SELECT DATEADD(DAY,-21,MAX(SNAPSHOT_DATE)) from cte_v_sls_wtx_promo_summary)
)
select 
SOURCE_ITEM_IDENTIFIER,
	CALENDAR_DATE,
	SOURCE_CONTENT_FILTER,
	ITM_DESCRIPTION,
	ITEM_TYPE,
	BRANDING_DESCRIPTION,
	PRODUCT_CLASS_DESCRIPTION,
	SUB_PRODUCT_DESCRIPTION,
	STRATEGIC_DESCRIPTION,
	POWER_BRAND_DESC,
	MANUFACTURING_GROUP_DESCRIPTION,
	CATEGORY_DESCRIPTION,
	PACK_SIZE_DESCRIPTION,
	SUB_CATEGORY_DESCRIPTION,
	PROMO_TYPE_DESCRIPTION,
	TRADE_CLASS,
	TRADE_GROUP,
	TRADE_TYPE,
	TRADE_SECTOR,
	SUBMARKET,
	CUSTOMER_BRANCH_NAME,
	CUSTOMER_ACCOUNT_NAME,
	DOCUMENT_COMPANY as COMPANY,
	TRM_OTHER_DIRECT_PERC,
	TRM_SNAPSHOT_DATE,
	PROMO_SNAPSHOT_DATE,
	PRM_ISPROMOSKU,
	PROMO_STAT_DESC,
	PRM_SI_T_VOL_CSE,
	PRM_SI_T_VOL_CU,
	PRM_SI_T_VOL_KG,
	PRM_ACTUALS_AP_AVP_DISC,
	PRM_FORECAST_AP_AVP_DISC,
	PRM_ACTUALS_AP_DIRECT_SHOPPER_MARKETING,
	PRM_FORECAST_AP_DIRECT_SHOPPER_MARKETING,
	PRM_ACTUALS_AP_EARLY_SETTLEMENT_DISC,
	PRM_FORECAST_AP_EARLY_SETTLEMENT_DISC,
	PRM_ACTUALS_AP_EVERYDAY_LOW_PRICES,
	PRM_FORECAST_AP_EVERYDAY_LOW_PRICES,
	PRM_ACTUALS_AP_OFF_INVOICE_DISC,
	PRM_FORECAST_AP_OFF_INVOICE_DISC,
	PRM_ACTUALS_AP_OTHER_DIRECT_PAYMENTS,
	PRM_FORECAST_AP_OTHER_DIRECT_PAYMENTS,
	PRM_ACTUALS_AP_PROMO_FIXED_FUNDING,
	PRM_FORECAST_AP_PROMO_FIXED_FUNDING,
	PRM_ACTUALS_AP_RANGE_SUPPORT_ALLOWANCE,
	PRM_FORECAST_AP_RANGE_SUPPORT_ALLOWANCE,
	PRM_ACTUALS_AP_RETRO,
	PRM_FORECAST_AP_RETRO,
	PRM_ACTUALS_AP_GROWTH_INCENTIVES,
	PRM_FORECAST_AP_GROWTH_INCENTIVES,
	CY_BASE_RPT_GRS_AMT,
	FCF_AP_GROSS_SELLING_VALUE,
	FCF_TOT_VOL_CA,
	FCF_TOT_VOL_CU,
	FCF_TOT_VOL_KG,
	FCF_TOT_VOL_UL,
	FCF_TOT_VOL_PK,
	CY_SHIPPED_CA_QUANTITY,
	CY_SHIPPED_CU_QUANTITY,
	CY_SHIPPED_PK_QUANTITY,
	CY_SHIPPED_UL_QUANTITY,
	CY_SHIPPED_KG_QUANTITY,
	CY_GL_BASE_PERMD_RNG_SPT,
	CY_GL_BASE_PERMD_EDLP,
	CY_GL_BASE_PERMD_CSH_DISC,
	CY_GL_BASE_PERMD_RSA_INCT,
	CY_GL_BASE_TRADE_AVP,
	FCF_AP_NET_SALES_VALUE,
	SNAPSHOT_FORECAST_DATE,
	MARKET,
	PRM_SI_T_VOL_PK from cte_final