

with source as (

    select * from {{ source('WEETABIX', 'EXC_Fact_Account_Plan_Actual') }}


),

renamed as (

    select
        day_idx,
        cust_idx,
        sku_idx,
        scen_idx,
        isonpromo_si,
        isonpromo_so,
        tot_vol_sp_base_uom,
        tot_vol_sp_base_uom_pre_adjustment,
        tot_vol_sp_base_uom_mgmt_adjustment,
        retail_tot_vol_sp_base_uom,
        promo_vol,
        tot_vol_sgl,
        tot_vol_kg,
        ap_added_value_pack,
        ap_permanent_disc,
        ap_invoiced_sales_value,
        ap_net_sales_value,
        ap_net_realisable_revenue,
        ap_variable_trade,
        ap_net_net_sales_value,
        ap_fixed_trade_cust_invoiced,
        ap_total_trade_cust_invoiced,
        ap_fixed_trade_non_cust_invoiced,
        ap_total_trade,
        ap_gross_margin_standard,
        ap_gross_margin_actual,
        ap_gcat_standard,
        ap_gcat_actuals,
        ap_fixed_annual_payments_pre_adjustment,
        ap_fixed_annual_payments_mgmt_adjustment,
        ap_fixed_annual_payments,
        ap_category_pre_adjustment,
        ap_category_mgmt_adjustment,
        ap_category,
        ap_promo_fixed_funding_pre_adjustment,
        ap_promo_fixed_funding_mgmt_adjustment,
        ap_promo_fixed_funding,
        ap_cash_disc_pre_adjustment,
        ap_cash_disc_mgmt_adjustment,
        ap_cash_disc,
        ap_direct_shopper_marketing_pre_adjustment,
        ap_direct_shopper_marketing_mgmt_adjustment,
        ap_direct_shopper_marketing,
        ap_range_support_allowance_pre_adjustment,
        ap_range_support_allowance_mgmt_adjustment,
        ap_range_support_allowance,
        ap_range_support_incentives_pre_adjustment,
        ap_range_support_incentives_mgmt_adjustment,
        ap_range_support_incentives,
        ap_indirect_shopper_marketing_pre_adjustment,
        ap_indirect_shopper_marketing_mgmt_adjustment,
        ap_indirect_shopper_marketing,
        ap_retro_pre_adjustment,
        ap_retro_mgmt_adjustment,
        ap_retro,
        ap_avp_disc_pre_adjustment,
        ap_avp_disc_mgmt_adjustment,
        ap_avp_disc,
        ap_everyday_low_prices_pre_adjustment,
        ap_everyday_low_prices_mgmt_adjustment,
        ap_everyday_low_prices,
        ap_off_invoice_disc_pre_adjustment,
        ap_off_invoice_disc_mgmt_adjustment,
        ap_off_invoice_disc,
        ap_field_marketing_pre_adjustment,
        ap_field_marketing_mgmt_adjustment,
        ap_field_marketing,
        ap_tot_prime_cost_variance_pre_adjustment,
        ap_tot_prime_cost_variance_mgmt_adjustment,
        ap_tot_prime_cost_variance,
        ap_tot_prime_cost_standard_pre_adjustment,
        ap_tot_prime_cost_standard_mgmt_adjustment,
        ap_tot_prime_cost_standard,
        ap_early_settlement_disc_pre_adjustment,
        ap_early_settlement_disc_mgmt_adjustment,
        ap_early_settlement_disc,
        ap_other_direct_payments_pre_adjustment,
        ap_other_direct_payments_mgmt_adjustment,
        ap_other_direct_payments,
        ap_other_indirect_payments_pre_adjustment,
        ap_other_indirect_payments_mgmt_adjustment,
        ap_other_indirect_payments,
        ap_gross_selling_value_pre_adjustment,
        ap_gross_selling_value_mgmt_adjustment,
        ap_gross_selling_value,
        ap_gross_sales_value,
        ap_growth_incentives_pre_adjustment,
        ap_growth_incentives_mgmt_adjustment,
        ap_growth_incentives,
        retail_tot_vol_sgl,
        retail_tot_vol_kg,
        ap_retail_revenue_mrrsp,
        ap_retail_revenue_rsp,
        ap_retail_revenue_net,
        ap_retail_cost_of_sales,
        ap_retail_retailer_retro_funding,
        ap_retail_margin_excl_fixed_funding,
        ap_retail_promo_fixed_spend,
        ap_retail_total_spend,
        ap_retail_margin_incl_fixed_funding,
        ap_retail_revenue_net_excl_mrrsp,
        ap_retail_revenue_net_excl_rsp

    from source

)

select * from renamed
