{{ config(
    tags=["rdm_legacy"]
) }}

with
    source as (select * from {{ ref("dim_wbx_item") }}),
    renamed as (
        select
            source_system,
            item_guid,
            business_unit_address_guid,
            vendor_address_guid,
            source_item_identifier,
            source_business_unit_code,
            case_item_number,
            legacy_case_item_number,
            alternate_item_number,
            case_upc,
            NULL as case_gtin_number,
            NULL as consumer_upc,
            consumer_gtin_number,
            description,
            pack_size_desc,
            short_description,
            bus_unit_desc,
            NULL as company_desc,
            division_c0de,
            division,
            planner_code,
            buyer_code,
            shelf_life_days,
            stock_type,
            stock_desc,
            item_type,
            item_class,
            NULL as holdings_type,
            NULL as gl_class,
            gl_class_name,
            NULL as width,
            NULL as depth,
            NULL as height,
            NULL as weight,
            NULL as item_supplier_code,
            NULL as handling_spec,
            NULL as stock_location,
            NULL as line_type,
            NULL as basket_reprice_grp,
            formula_variation,
            NULL as order_policy_code,
            NULL as value_order_policy,
            NULL as planning_code,
            NULL as planning_fence_rule,
            NULL as planning_fence,
            NULL as freeze_fence,
            NULL as display_fence,
            NULL as issue_type_code,
            NULL as round_to_whole_no,
            NULL as issue_and_receipt,
            NULL as lot_process_type,
            NULL as commitment_method,
            NULL as lot_serial_number,
            NULL as sales_price_level,
            NULL as freight_classification,
            NULL as nmfc_item_number,
            reorder_quantity,
            max_reorder_quantity,
            min_reorder_quantity,
            reorder_point,
            multiple_order_quantity,
            NULL as time_basis,
            NULL as default_pack_code,
            NULL as production_line_type,
            NULL as quota_category,
            NULL as case_barcode_marking,
            NULL as foodservice_product_group,
            NULL as pasta_shape,
            NULL as design_group,
            consumer_unit_size,
            NULL as user_code_3,
            NULL as origin,
            pasta_shape_variant,
            NULL as availability,
            NULL as customer_unit,
            NULL as department,
            NULL as lot_sizing_method,
            NULL as procurement_uom,
            NULL as sales_uom,
            primary_uom,
            NULL as secondary_uom,
            NULL as purchasing_uom,
            NULL as pricing_uom,
            NULL as shipping_uom,
            NULL as production_uom,
            NULL as component_uom,
            NULL as weight_uom,
            NULL as volume_uom,
            NULL as package_uom,
            NULL as dimension_uom,
            NULL as gross_weight_uom,
            NULL as consumer_units_per_case,
            NULL as cases_per_customer_pallet,
            NULL as cases_per_manufacturing_pallet,
            NULL as cases_per_pallet_tier,
            NULL as tiers_per_customer_pallet,
            NULL as tiers_per_manufacturing_pallet,
            case_gross_weight,
            case_net_weight,
            NULL as case_hundred_weight,
            NULL as case_volume,
            NULL as batch_to_pound,
            NULL as pallet_to_each,
            NULL as pallet_to_cubic_feet,
            NULL as pallet_to_linnear_feet,
            NULL as pallet_to_pound,
            NULL as roll_to_each,
            NULL as roll_to_cubic_feet,
            NULL as roll_to_pound,
            purchase_make_indicator,
            NULL as taxable_indicator,
            NULL as plan_orders,
            NULL as order_period,
            NULL as time_fence,
            NULL as dual_uom_indicator,
            NULL as abc_code,
            NULL as gl_category_id,
            NULL as inventory_category_id,
            NULL as cost_category_id,
            NULL as planning_category_id,
            NULL as storage_category_id,
            NULL as autolot_active_indicator,
            NULL as lot_prefix,
            NULL as lot_suffix,
            NULL as sublot_suffix,
            update_date,
            load_date,
            NULL as procurement_uom_desc,
            NULL as sales_uom_desc,
            primary_uom_desc,
            NULL as secondary_uom_desc,
            NULL as purchasing_uom_desc,
            NULL as pricing_uom_desc,
            NULL as shipping_uom_desc,
            NULL as production_uom_desc,
            NULL as component_uom_desc,
            NULL as weight_uom_desc,
            NULL as volume_uom_desc,
            NULL as package_uom_desc,
            NULL as dimension_uom_desc,
            NULL as gross_weight_uom_desc,
            obsolete_flag,
            NULL as generated_row_desc,
            NULL as brand_code,
            NULL as brand_name,
            NULL as primary_manufacture_loc_code,
            NULL as primary_manufacture_loc_desc,
            NULL as commercialize_cust_grp_code,
            NULL as commercialize_cust_grp_desc,
            NULL as carton_upc,
            NULL as eaches_upc,
            NULL as subbrand_name
        from source
    )

select *
from renamed
