
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'wbx_dbt'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
on-run-end:
  - "{% if target.name != 'default' %}{{ ent_dbt_package.test_results_history(results) }}{% endif %}"
  - "{% if target.name != 'default' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +copy_grants: true
  wbx_dbt:
    # Applies to all files under models/example/
    phi:
      src:
        +schema: "{{env_var('DBT_SRC_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      stg_dim:
        +schema: "{{env_var('DBT_STG_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      int_dim:
        +schema: "{{env_var('DBT_DIM_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      dim:
        +schema: "{{env_var('DBT_DIM_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: false
        +full_refresh: false
      dim_conversion:
        +schema: "{{env_var('DBT_DIM_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: false
      dim_legacy:
        +schema: "{{env_var('DBT_DIM_LEGACY_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      fct:
        +schema: "{{env_var('DBT_FACT_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: false
      fct_conversion:
        +schema: "{{env_var('DBT_FACT_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: false
        +enabled: true
      stg_fct:
        +schema: "{{env_var('DBT_STG_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: true
      int_fct:
        +schema: "{{env_var('DBT_FACT_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: true
      rpt:
        +schema: "{{env_var('DBT_RPT_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_TABLE')}}"
        +transient: false
      redzone:
        +schema: "{{env_var('DBT_RZ_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      dbt_artifacts:
        +schema: "{{env_var('DBT_ARTIFACTS_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
      rpt_legacy:
        +schema: "{{env_var('DBT_RPT_LEGACY_SCHEMA')}}"
        +materialized: "{{env_var('DBT_MAT_VIEW')}}"
        +transient: false
  dbt_artifacts:
    +database: "{{env_var('DBT_TGT_DB')}}" # optional, default is your target database
    +schema: "{{env_var('DBT_ARTIFACTS_SCHEMA')}}" # optional, default is your target schema
    staging:
      +database: "{{env_var('DBT_TGT_DB')}}" # optional, default is your target database
      +schema: "{{env_var('DBT_ARTIFACTS_SCHEMA')}}" # optional, default is your target schema
    sources:
      +database: "{{env_var('DBT_TGT_DB')}}" # optional, default is your target database
      +schema: "{{env_var('DBT_ARTIFACTS_SCHEMA')}}" # optional, default is your target schema

        
# configuration for tests directory
tests:
  +severity: warn  # all tests
  +store_failures: "{{ (env_var('DBT_STORE_TEST_RESULTS') == 'YES') | as_bool }}"
  +schema: "{{env_var('DBT_TEST_SCHEMA')}}"


query-comment:
  comment: "{{ query_comment(node) }}"
  append: true


vars:
  dbt_artifacts_create_schema: false
  #+dbt_artifacts_database: "{{env_var('DBT_TGT_DB')}}"
  #dbt_artifacts_schema: 'DBT_ARTIFACTS'
  #+dbt_artifacts_schema: "{{env_var('DBT_ARTIFACTS_SCHEMA') | as_text}}"
