{{
    config(
        materialized = env_var('DBT_MAT_INCREMENTAL'),
        tags=["finance","ar"],
        transient = false,
        unique_key = 'UNIQUE_KEY',
        on_schema_change='sync_all_columns',        
        pre_hook=
        """
        {% set now = modules.datetime.datetime.now() %}
        {%- set full_load_day -%} {{env_var('DBT_FULL_LOAD_DAY')}} {%- endset -%}
        {%- set day_today -%} {{ now.strftime('%A') }} {%- endset -%}
        {% if day_today == full_load_day %}
        {{ truncate_if_exists(this.schema, this.table) }}
        {% endif %}
        """ 
    )
}}

with int_fact as
(
    select *
    , ROW_NUMBER() OVER (PARTITION BY unique_key ORDER BY 1) rowNum
    from {{ref('int_f_wbx_fin_ar_receipt_detail') }}
),

/* Pulls the corresponding AX history across to blend w/ the D365 transactional data.
    For the conv model, the relevant dimension values have been converted, where that is applicable.
*/
old_ax_fact as (
    select * from {{ ref('conv_fct_wbx_fin_ar_receipt_detail') }}
),

int as (
select 
    source_system,
    payment_identifier,
    line_number,
    receipt_number  ,
    document_number,
    document_type,
    document_company,
    document_pay_item,
    gl_date,
    posted_flag,
    source_account_identifier,
    target_account_identifier,
    account_guid,
    company_code,
    foreign_transaction_flag,
    discount_src_accnt_identifier,
    discount_trgt_accnt_identifier,
    discount_account_guid,
    writeoff_reason_code,
    writeoff_src_accnt_identifier,
    writeoff_trgt_accnt_identifier,
    writeoff_account_guid,
    chargeback_reason_code,
    chargeback_src_accnt_idntifier,
    chargeback_trgt_accnt_idntifer,
    chargeback_account_guid,
    deduction_reason_code,
    deduction_src_accnt_idntifer,
    deduction_trgt_accnt_idntifer,
    deduction_account_guid,
    source_business_unit_code,
    business_unit_address_guid,
    remark_txt,
    deduction_document_number,
    deduction_document_type,
    deduction_document_company,
    deduction_document_pay_item,
    journal_document_number,
    journal_document_type,
    journal_document_company,
    void_date,
    void_reason_code,
    net_due_date,
    discount_date,
    inv_jrnl_date,
    reference_txt,
    source_customer_identifier,
    customer_address_number_guid,
    source_payor_identifier,
    payor_address_number_guid,
    source_payment_instr_code,
    target_payment_instr_code,
    payment_instr_desc,
    transaction_currency,
    base_currency,
    phi_currency,
    pcomp_currency,
    txn_conv_rt,
    base_conv_rt,
    phi_conv_rt,
    pcomp_conv_rt,
    txn_payment_amt,
    txn_discount_avail_amt,
    txn_discount_taken_amt,
    txn_writeoff_amt,
    txn_chargeback_amt,
    txn_deduction_amt,
    txn_gain_loss_amt,
    base_payment_amt,
    base_discount_avail_amt,
    base_discount_taken_amt,
    base_writeoff_amt,
    base_chargeback_amt,
    base_deduction_amt,
    base_gain_loss_amt,
    phi_payment_amt,
    phi_discount_avail_amt,
    phi_discount_taken_amt,
    phi_writeoff_amt,
    phi_chargeback_amt,
    phi_deduction_amt,
    phi_gain_loss_amt,
    pcomp_payment_amt,
    pcomp_discount_avail_amt,
    pcomp_discount_taken_amt,
    pcomp_writeoff_amt,
    pcomp_chargeback_amt,
    pcomp_deduction_amt,
    pcomp_gain_loss_amt,
    intercompany_flag,
    source_date_updated,
    load_date,
    update_date,
    source_updated_d_id,
    batch_type,
    batch_number,
    batch_date,
    deduction_document_guid,
    ar_custinv_hdr_unique_key,
    unique_key,
    'D365' as source_legacy
from int_fact
where rownum=1
),

ax_hist as (
    select 
        a.source_system,
        a.payment_identifier,
        a.line_number,
        a.receipt_number  ,
        a.document_number,
        a.document_type,
        a.document_company,
        a.document_pay_item,
        a.gl_date,
        a.posted_flag,
        a.source_account_identifier,
        a.target_account_identifier,
        a.account_guid,
        a.company_code,
        a.foreign_transaction_flag,
        a.discount_src_accnt_identifier,
        a.discount_trgt_accnt_identifier,
        a.discount_account_guid,
        a.writeoff_reason_code,
        a.writeoff_src_accnt_identifier,
        a.writeoff_trgt_accnt_identifier,
        a.writeoff_account_guid,
        a.chargeback_reason_code,
        a.chargeback_src_accnt_idntifier,
        a.chargeback_trgt_accnt_idntifer,
        a.chargeback_account_guid,
        a.deduction_reason_code,
        a.deduction_src_accnt_idntifer,
        a.deduction_trgt_accnt_idntifer,
        a.deduction_account_guid,
        a.source_business_unit_code,
        a.business_unit_address_guid,
        a.remark_txt,
        a.deduction_document_number,
        a.deduction_document_type,
        a.deduction_document_company,
        a.deduction_document_pay_item,
        a.journal_document_number,
        a.journal_document_type,
        a.journal_document_company,
        a.void_date,
        a.void_reason_code,
        a.net_due_date,
        a.discount_date,
        a.inv_jrnl_date,
        a.reference_txt,
        a.source_customer_identifier,
        a.customer_address_number_guid,
        a.source_payor_identifier,
        a.payor_address_number_guid,
        a.source_payment_instr_code,
        a.target_payment_instr_code,
        a.payment_instr_desc,
        a.transaction_currency,
        a.base_currency,
        a.phi_currency,
        a.pcomp_currency,
        a.txn_conv_rt,
        a.base_conv_rt,
        a.phi_conv_rt,
        a.pcomp_conv_rt,
        a.txn_payment_amt,
        a.txn_discount_avail_amt,
        a.txn_discount_taken_amt,
        a.txn_writeoff_amt,
        a.txn_chargeback_amt,
        a.txn_deduction_amt,
        a.txn_gain_loss_amt,
        a.base_payment_amt,
        a.base_discount_avail_amt,
        a.base_discount_taken_amt,
        a.base_writeoff_amt,
        a.base_chargeback_amt,
        a.base_deduction_amt,
        a.base_gain_loss_amt,
        a.phi_payment_amt,
        a.phi_discount_avail_amt,
        a.phi_discount_taken_amt,
        a.phi_writeoff_amt,
        a.phi_chargeback_amt,
        a.phi_deduction_amt,
        a.phi_gain_loss_amt,
        a.pcomp_payment_amt,
        a.pcomp_discount_avail_amt,
        a.pcomp_discount_taken_amt,
        a.pcomp_writeoff_amt,
        a.pcomp_chargeback_amt,
        a.pcomp_deduction_amt,
        a.pcomp_gain_loss_amt,
        a.intercompany_flag,
        a.source_date_updated,
        a.load_date,
        a.update_date,
        a.source_updated_d_id,
        a.batch_type,
        a.batch_number,
        a.batch_date,
        a.deduction_document_guid,
        a.ar_custinv_hdr_unique_key,
        a.unique_key,
        'AX' as source_legacy
    from old_ax_fact as a
    /* This ensures that if the unique_key is in D365 that it is not also pulled from the AX History. */
    left join int as b on a.unique_key = b.unique_key
    where b.source_system is null
),

final as (
    select * from int
    union
    select * from ax_hist
)

select 
    cast(substring(source_system,1,255) as text(255) ) as source_system  ,
    cast(substring(payment_identifier,1,255) as text(255) ) as payment_identifier  ,
    cast(line_number as number(38,10) ) as line_number  ,
    cast(substring(receipt_number,1,255) as text(255) ) as receipt_number  ,
    cast(substring(document_number,1,255) as text(255) ) as document_number  ,
    cast(substring(document_type,1,255) as text(255) ) as document_type  ,
    cast(substring(document_company,1,255) as text(255) ) as document_company  ,
    cast(substring(document_pay_item,1,255) as text(255) ) as document_pay_item  ,
    cast(gl_date as timestamp_ntz(9) ) as gl_date  ,
    cast(substring(posted_flag,1,6) as text(6) ) as posted_flag  ,
    cast(substring(source_account_identifier,1,255) as text(255) ) as source_account_identifier  ,
    cast(substring(target_account_identifier,1,255) as text(255) ) as target_account_identifier  ,
    cast(substring(account_guid,1,255) as text(255) ) as account_guid  ,
    cast(substring(company_code,1,255) as text(255) ) as company_code  ,
    cast(substring(foreign_transaction_flag,1,20) as text(20) ) as foreign_transaction_flag  ,
    cast(substring(discount_src_accnt_identifier,1,255) as text(255) ) as discount_src_accnt_identifier  ,
    cast(substring(discount_trgt_accnt_identifier,1,255) as text(255) ) as discount_trgt_accnt_identifier  ,
    cast(substring(discount_account_guid,1,255) as text(255) ) as discount_account_guid  ,
    cast(substring(writeoff_reason_code,1,255) as text(255) ) as writeoff_reason_code  ,
    cast(substring(writeoff_src_accnt_identifier,1,255) as text(255) ) as writeoff_src_accnt_identifier  ,
    cast(substring(writeoff_trgt_accnt_identifier,1,255) as text(255) ) as writeoff_trgt_accnt_identifier  ,
    cast(substring(writeoff_account_guid,1,255) as text(255) ) as writeoff_account_guid  ,
    cast(substring(chargeback_reason_code,1,255) as text(255) ) as chargeback_reason_code  ,
    cast(substring(chargeback_src_accnt_idntifier,1,255) as text(255) ) as chargeback_src_accnt_idntifier  ,
    cast(substring(chargeback_trgt_accnt_idntifer,1,255) as text(255) ) as chargeback_trgt_accnt_idntifer  ,
    cast(substring(chargeback_account_guid,1,255) as text(255) ) as chargeback_account_guid  ,
    cast(substring(deduction_reason_code,1,255) as text(255) ) as deduction_reason_code  ,
    cast(substring(deduction_src_accnt_idntifer,1,255) as text(255) ) as deduction_src_accnt_idntifer  ,
    cast(substring(deduction_trgt_accnt_idntifer,1,255) as text(255) ) as deduction_trgt_accnt_idntifer  ,
    cast(substring(deduction_account_guid,1,255) as text(255) ) as deduction_account_guid  ,
    cast(substring(source_business_unit_code,1,255) as text(255) ) as source_business_unit_code  ,
    cast(substring(business_unit_address_guid,1,255) as text(255) ) as business_unit_address_guid  ,
    cast(substring(remark_txt,1,255) as text(255) ) as remark_txt  ,
    cast(substring(deduction_document_number,1,255) as text(255) ) as deduction_document_number  ,
    cast(substring(deduction_document_type,1,255) as text(255) ) as deduction_document_type  ,
    cast(substring(deduction_document_company,1,255) as text(255) ) as deduction_document_company  ,
    cast(substring(deduction_document_pay_item,1,255) as text(255) ) as deduction_document_pay_item  ,
    cast(substring(journal_document_number,1,255) as text(255) ) as journal_document_number  ,
    cast(substring(journal_document_type,1,255) as text(255) ) as journal_document_type  ,
    cast(substring(journal_document_company,1,255) as text(255) ) as journal_document_company  ,
    cast(void_date as timestamp_ntz(9) ) as void_date  ,
    cast(substring(void_reason_code,1,255) as text(255) ) as void_reason_code  ,
    cast(net_due_date as timestamp_ntz(9) ) as net_due_date  ,
    cast(discount_date as timestamp_ntz(9) ) as discount_date  ,
    cast(inv_jrnl_date as timestamp_ntz(9) ) as inv_jrnl_date  ,
    cast(substring(reference_txt,1,255) as text(255) ) as reference_txt  ,
    cast(substring(source_customer_identifier,1,255) as text(255) ) as source_customer_identifier  ,
    cast(substring(customer_address_number_guid,1,255) as text(255) ) as customer_address_number_guid  ,
    cast(substring(source_payor_identifier,1,255) as text(255) ) as source_payor_identifier  ,
    cast(substring(payor_address_number_guid,1,255) as text(255) ) as payor_address_number_guid  ,
    cast(substring(source_payment_instr_code,1,255) as text(255) ) as source_payment_instr_code  ,
    cast(substring(target_payment_instr_code,1,255) as text(255) ) as target_payment_instr_code  ,
    cast(substring(payment_instr_desc,1,255) as text(255) ) as payment_instr_desc  ,
    cast(substring(transaction_currency,1,255) as text(255) ) as transaction_currency  ,
    cast(substring(base_currency,1,255) as text(255) ) as base_currency  ,
    cast(substring(phi_currency,1,255) as text(255) ) as phi_currency  ,
    cast(substring(pcomp_currency,1,255) as text(255) ) as pcomp_currency  ,
    cast(txn_conv_rt as number(29,9) ) as txn_conv_rt  ,
    cast(base_conv_rt as number(29,9) ) as base_conv_rt  ,
    cast(phi_conv_rt as number(29,9) ) as phi_conv_rt  ,
    cast(pcomp_conv_rt as number(29,9) ) as pcomp_conv_rt  ,
    cast(txn_payment_amt as number(38,10) ) as txn_payment_amt  ,
    cast(txn_discount_avail_amt as number(38,10) ) as txn_discount_avail_amt  ,
    cast(txn_discount_taken_amt as number(38,10) ) as txn_discount_taken_amt  ,
    cast(txn_writeoff_amt as number(38,10) ) as txn_writeoff_amt  ,
    cast(txn_chargeback_amt as number(38,10) ) as txn_chargeback_amt  ,
    cast(txn_deduction_amt as number(38,10) ) as txn_deduction_amt  ,
    cast(txn_gain_loss_amt as number(38,10) ) as txn_gain_loss_amt  ,
    cast(base_payment_amt as number(38,10) ) as base_payment_amt  ,
    cast(base_discount_avail_amt as number(38,10) ) as base_discount_avail_amt  ,
    cast(base_discount_taken_amt as number(38,10) ) as base_discount_taken_amt  ,
    cast(base_writeoff_amt as number(38,10) ) as base_writeoff_amt  ,
    cast(base_chargeback_amt as number(38,10) ) as base_chargeback_amt  ,
    cast(base_deduction_amt as number(38,10) ) as base_deduction_amt  ,
    cast(base_gain_loss_amt as number(38,10) ) as base_gain_loss_amt  ,
    cast(phi_payment_amt as number(38,10) ) as phi_payment_amt  ,
    cast(phi_discount_avail_amt as number(38,10) ) as phi_discount_avail_amt  ,
    cast(phi_discount_taken_amt as number(38,10) ) as phi_discount_taken_amt  ,
    cast(phi_writeoff_amt as number(38,10) ) as phi_writeoff_amt  ,
    cast(phi_chargeback_amt as number(38,10) ) as phi_chargeback_amt  ,
    cast(phi_deduction_amt as number(38,10) ) as phi_deduction_amt  ,
    cast(phi_gain_loss_amt as number(38,10) ) as phi_gain_loss_amt  ,
    cast(pcomp_payment_amt as number(38,10) ) as pcomp_payment_amt  ,
    cast(pcomp_discount_avail_amt as number(38,10) ) as pcomp_discount_avail_amt  ,
    cast(pcomp_discount_taken_amt as number(38,10) ) as pcomp_discount_taken_amt  ,
    cast(pcomp_writeoff_amt as number(38,10) ) as pcomp_writeoff_amt  ,
    cast(pcomp_chargeback_amt as number(38,10) ) as pcomp_chargeback_amt  ,
    cast(pcomp_deduction_amt as number(38,10) ) as pcomp_deduction_amt  ,
    cast(pcomp_gain_loss_amt as number(38,10) ) as pcomp_gain_loss_amt  ,
    cast(substring(intercompany_flag,1,1) as text(1) ) as intercompany_flag  ,
    cast(source_date_updated as timestamp_ntz(9) ) as source_date_updated  ,
    cast(load_date as timestamp_ntz(9) ) as load_date  ,
    cast(update_date as timestamp_ntz(9) ) as update_date  ,
    cast(source_updated_d_id as number(38,0) ) as source_updated_d_id  ,
    cast(substring(batch_type,1,4) as text(4) ) as batch_type  ,
    cast(substring(batch_number,1,255) as text(255) ) as batch_number  ,
    cast(batch_date as timestamp_ntz(9) ) as batch_date  ,
    cast(substring(deduction_document_guid,1,255) as text(255) ) as deduction_document_guid  ,
    cast(substring(ar_custinv_hdr_unique_key,1,255) as text(255) ) as ar_custinv_hdr_unique_key  ,
    cast(substring(unique_key,1,255) as text(255) ) as unique_key,
    cast(substring(source_legacy,1,255) as text(255) ) as source_legacy
from final