{{
  config( 
    materialized=env_var('DBT_MAT_INCREMENTAL'), 
    tags = ["sls","sales","forecast","sls_forecast","sls_finance"],
    snowflake_warehouse= env_var("DBT_WBX_SF_WH"),
    unique_key='snapshot_date', 
    on_schema_change='sync_all_columns', 
    incremental_strategy='delete+insert',
    full_refresh=false,
     pre_hook="""
            {{ truncate_if_exists(this.schema, this.table) }}
            """
    )
}}

/*This is intermediate model to fct_wbx_sls_budget so changing load stretegy to truncate load */

with old_table as
(
    select * from {{ref('conv_fct_wbx_sls_forecast_fin')}}  
    {% if check_table_exists( this.schema, this.table ) == 'False' %}
     limit {{env_var('DBT_NO_LIMIT')}} ----------Variable DBT_NO_LIMIT variable is set TO NULL to load everything from conv model if effective currency model is not present.
    {% else %} limit {{env_var('DBT_LIMIT')}}-----Variable DBT_LIMIT variable is set to 0 to load nothing if effective_currency table exist

{% endif %}

),

base_fct  as (
    select * from {{ref('int_f_wtx_sls_forecast_fin')}} where rownum=1
    {% if check_table_exists( this.schema, this.table ) == 'True' %}
     limit {{env_var('DBT_NO_LIMIT')}}
    {% else %} limit {{env_var('DBT_LIMIT')}}
    {% endif %}
),
old_model as
(
    select 
        cast(substring(source_system,1,255) as text(255) )                      as source_system  ,
        cast(sku_idx as number(38,0) )                                          as sku_idx  ,
        cast(substring(source_item_identifier,1,255) as text(255) )             as source_item_identifier  ,
        cast(item_guid as text(255) )                                           as item_guid  ,
        cast(cust_idx as number(38,0) )                                         as cust_idx  ,
        cast(substring(plan_source_customer_code,1,255) as text(255) )          as plan_source_customer_code  ,
        cast(substring(customer_address_number_guid,1,255) as text(255) )       as customer_address_number_guid  ,
        cast(snapshot_date as date)                                             as snapshot_date  ,
        cast(calendar_date as timestamp_ntz(9) )                                as calendar_date  ,
        cast(scen_idx as number(38,0) )                                         as scen_idx  ,
        cast(substring(scen_code,1,255) as text(255) )                          as scen_code  ,
        cast(substring(scen_name,1,255) as text(255) )                          as scen_name  ,
        cast(scenario_guid as text(255) )                                       as scenario_guid  ,
        cast(substring(isonpromo_si,1,255) as text(255) )                       as isonpromo_si  ,
        cast(substring(isonpromo_so,1,255) as text(255) )                       as isonpromo_so  ,
        cast(tot_vol_sp_base_uom as float)                                      as tot_vol_sp_base_uom  ,
        cast(tot_vol_sp_kg_uom as float)                                        as tot_vol_sp_kg_uom  ,
        cast(tot_vol_sp_ul_uom as float)                                        as tot_vol_sp_ul_uom  ,
        cast(tot_vol_sp_base_uom_pre_adjustment as float)                       as tot_vol_sp_base_uom_pre_adjustment  ,
        cast(tot_vol_sp_kg_uom_pre_adjustment as float)                         as tot_vol_sp_kg_uom_pre_adjustment  ,
        cast(tot_vol_sp_ul_uom_pre_adjustment as float)                         as tot_vol_sp_ul_uom_pre_adjustment  ,
        cast(tot_vol_sp_base_uom_mgmt_adjustment as float)                      as tot_vol_sp_base_uom_mgmt_adjustment  ,
        cast(tot_vol_sp_kg_uom_mgmt_adjustment as float)                        as tot_vol_sp_kg_uom_mgmt_adjustment  ,
        cast(tot_vol_sp_ul_uom_mgmt_adjustment as float)                        as tot_vol_sp_ul_uom_mgmt_adjustment  ,
        cast(retail_tot_vol_sp_base_uom as float)                               as retail_tot_vol_sp_base_uom  ,
        cast(retail_tot_vol_sp_kg_uom as float)                                 as retail_tot_vol_sp_kg_uom  ,
        cast(retail_tot_vol_sp_ul_uom as float)                                 as retail_tot_vol_sp_ul_uom  ,
        cast(promo_vol as float)                                                as promo_vol  ,
        cast(promo_vol_kg as float)                                             as promo_vol_kg  ,
        cast(promo_vol_ul as float)                                             as promo_vol_ul  ,
        cast(tot_vol_sgl as float)                                              as tot_vol_sgl  ,
        cast(tot_vol_sgl_ca as float)                                           as tot_vol_sgl_ca  ,
        cast(tot_vol_sgl_ul as float)                                           as tot_vol_sgl_ul  ,
        cast(tot_vol_kg as float)                                               as tot_vol_kg  ,
        cast(tot_vol_ca as float)                                               as tot_vol_ca  ,
        cast(tot_vol_ul as float)                                               as tot_vol_ul  ,
        cast(ap_added_value_pack as float)                                      as ap_added_value_pack  ,
        cast(ap_permanent_disc as float)                                        as ap_permanent_disc  ,
        cast(ap_invoiced_sales_value as float)                                  as ap_invoiced_sales_value  ,
        cast(ap_net_sales_value as float)                                       as ap_net_sales_value  ,
        cast(ap_net_realisable_revenue as float)                                as ap_net_realisable_revenue  ,
        cast(ap_variable_trade as float)                                        as ap_variable_trade  ,
        cast(ap_net_net_sales_value as float)                                   as ap_net_net_sales_value  ,
        cast(ap_fixed_trade_cust_invoiced as float)                             as ap_fixed_trade_cust_invoiced  ,
        cast(ap_total_trade_cust_invoiced as float)                             as ap_total_trade_cust_invoiced  ,
        cast(ap_fixed_trade_non_cust_invoiced as float)                         as ap_fixed_trade_non_cust_invoiced  ,
        cast(ap_total_trade as float)                                           as ap_total_trade  ,
        cast(ap_gross_margin_standard as float)                                 as ap_gross_margin_standard  ,
        cast(ap_gross_margin_actual as float)                                   as ap_gross_margin_actual  ,
        cast(ap_gcat_standard as float)                                         as ap_gcat_standard  ,
        cast(ap_gcat_actuals as float)                                          as ap_gcat_actuals  ,
        cast(ap_fixed_annual_payments_pre_adjustment as float)                  as ap_fixed_annual_payments_pre_adjustment  ,
        cast(ap_fixed_annual_payments_mgmt_adjustment as float)                 as ap_fixed_annual_payments_mgmt_adjustment  ,
        cast(ap_fixed_annual_payments as float)                                 as ap_fixed_annual_payments  ,
        cast(ap_category_pre_adjustment as float)                               as ap_category_pre_adjustment  ,
        cast(ap_category_mgmt_adjustment as float)                              as ap_category_mgmt_adjustment  ,
        cast(ap_category as float)                                              as ap_category  ,
        cast(ap_promo_fixed_funding_pre_adjustment as float)                    as ap_promo_fixed_funding_pre_adjustment  ,
        cast(ap_promo_fixed_funding_mgmt_adjustment as float)                   as ap_promo_fixed_funding_mgmt_adjustment  ,
        cast(ap_promo_fixed_funding as float)                                   as ap_promo_fixed_funding  ,
        cast(ap_cash_disc_pre_adjustment as float)                              as ap_cash_disc_pre_adjustment  ,
        cast(ap_cash_disc_mgmt_adjustment as float)                             as ap_cash_disc_mgmt_adjustment  ,
        cast(ap_cash_disc as float)                                             as ap_cash_disc  ,
        cast(ap_direct_shopper_marketing_pre_adjustment as float)               as ap_direct_shopper_marketing_pre_adjustment  ,
        cast(ap_direct_shopper_marketing_mgmt_adjustment as float)              as ap_direct_shopper_marketing_mgmt_adjustment  ,
        cast(ap_direct_shopper_marketing as float)                              as ap_direct_shopper_marketing  ,
        cast(ap_range_support_allowance_pre_adjustment as float)                as ap_range_support_allowance_pre_adjustment  ,
        cast(ap_range_support_allowance_mgmt_adjustment as float)               as ap_range_support_allowance_mgmt_adjustment  ,
        cast(ap_range_support_allowance as float)                               as ap_range_support_allowance  ,
        cast(ap_range_support_incentives_pre_adjustment as float)               as ap_range_support_incentives_pre_adjustment  ,
        cast(ap_range_support_incentives_mgmt_adjustment as float)              as ap_range_support_incentives_mgmt_adjustment  ,
        cast(ap_range_support_incentives as float)                              as ap_range_support_incentives  ,
        cast(ap_indirect_shopper_marketing_pre_adjustment as float)             as ap_indirect_shopper_marketing_pre_adjustment  ,
        cast(ap_indirect_shopper_marketing_mgmt_adjustment as float)            as ap_indirect_shopper_marketing_mgmt_adjustment  ,
        cast(ap_indirect_shopper_marketing as float)                            as ap_indirect_shopper_marketing  ,
        cast(ap_retro_pre_adjustment as float)                                  as ap_retro_pre_adjustment  ,
        cast(ap_retro_mgmt_adjustment as float)                                 as ap_retro_mgmt_adjustment  ,
        cast(ap_retro as float)                                                 as ap_retro  ,
        cast(ap_avp_disc_pre_adjustment as float)                               as ap_avp_disc_pre_adjustment  ,
        cast(ap_avp_disc_mgmt_adjustment as float)                              as ap_avp_disc_mgmt_adjustment  ,
        cast(ap_avp_disc as float)                                              as ap_avp_disc  ,
        cast(ap_everyday_low_prices_pre_adjustment as float)                    as ap_everyday_low_prices_pre_adjustment  ,
        cast(ap_everyday_low_prices_mgmt_adjustment as float)                   as ap_everyday_low_prices_mgmt_adjustment  ,
        cast(ap_everyday_low_prices as float)                                   as ap_everyday_low_prices  ,
        cast(ap_off_invoice_disc_pre_adjustment as float)                       as ap_off_invoice_disc_pre_adjustment  ,
        cast(ap_off_invoice_disc_mgmt_adjustment as float)                      as ap_off_invoice_disc_mgmt_adjustment  ,
        cast(ap_off_invoice_disc as float)                                      as ap_off_invoice_disc  ,
        cast(ap_field_marketing_pre_adjustment as float)                        as ap_field_marketing_pre_adjustment  ,
        cast(ap_field_marketing_mgmt_adjustment as float)                       as ap_field_marketing_mgmt_adjustment  ,
        cast(ap_field_marketing as float)                                       as ap_field_marketing  ,
        cast(ap_tot_prime_cost_variance_pre_adjustment as float)                as ap_tot_prime_cost_variance_pre_adjustment  ,
        cast(ap_tot_prime_cost_variance_mgmt_adjustment as float)               as ap_tot_prime_cost_variance_mgmt_adjustment  ,
        cast(ap_tot_prime_cost_variance as float)                               as ap_tot_prime_cost_variance  ,
        cast(ap_tot_prime_cost_standard_pre_adjustment as float)                as ap_tot_prime_cost_standard_pre_adjustment  ,
        cast(ap_tot_prime_cost_standard_mgmt_adjustment as float)               as ap_tot_prime_cost_standard_mgmt_adjustment  ,
        cast(ap_tot_prime_cost_standard as float)                               as ap_tot_prime_cost_standard  ,
        cast(ap_early_settlement_disc_pre_adjustment as float)                  as ap_early_settlement_disc_pre_adjustment  ,
        cast(ap_early_settlement_disc_mgmt_adjustment as float)                 as ap_early_settlement_disc_mgmt_adjustment  ,
        cast(ap_early_settlement_disc as float)                                 as ap_early_settlement_disc  ,
        cast(ap_other_direct_payments_pre_adjustment as float)                  as ap_other_direct_payments_pre_adjustment  ,
        cast(ap_other_direct_payments_mgmt_adjustment as float)                 as ap_other_direct_payments_mgmt_adjustment  ,
        cast(ap_other_direct_payments as float)                                 as ap_other_direct_payments  ,
        cast(ap_other_indirect_payments_pre_adjustment as float)                as ap_other_indirect_payments_pre_adjustment  ,
        cast(ap_other_indirect_payments_mgmt_adjustment as float)               as ap_other_indirect_payments_mgmt_adjustment  ,
        cast(ap_other_indirect_payments as float)                               as ap_other_indirect_payments  ,
        cast(ap_gross_selling_value_pre_adjustment as float)                    as ap_gross_selling_value_pre_adjustment  ,
        cast(ap_gross_selling_value_mgmt_adjustment as float)                   as ap_gross_selling_value_mgmt_adjustment  ,
        cast(ap_gross_selling_value as float)                                   as ap_gross_selling_value  ,
        cast(ap_gross_sales_value as float)                                     as ap_gross_sales_value  ,
        cast(ap_growth_incentives_pre_adjustment as float)                      as ap_growth_incentives_pre_adjustment  ,
        cast(ap_growth_incentives_mgmt_adjustment as float)                     as ap_growth_incentives_mgmt_adjustment  ,
        cast(ap_growth_incentives as float)                                     as ap_growth_incentives  ,
        cast(retail_tot_vol_sgl as float)                                       as retail_tot_vol_sgl  ,
        cast(retail_tot_vol_sgl_ca as float)                                    as retail_tot_vol_sgl_ca  ,
        cast(retail_tot_vol_sgl_ul as float)                                    as retail_tot_vol_sgl_ul  ,
        cast(retail_tot_vol_kg as float)                                        as retail_tot_vol_kg  ,
        cast(retail_tot_vol_ca as float)                                        as retail_tot_vol_ca  ,
        cast(retail_tot_vol_ul as float)                                        as retail_tot_vol_ul  ,
        cast(ap_retail_revenue_mrrsp as float)                                  as ap_retail_revenue_mrrsp  ,
        cast(ap_retail_revenue_rsp as float)                                    as ap_retail_revenue_rsp  ,
        cast(ap_retail_revenue_net as float)                                    as ap_retail_revenue_net  ,
        cast(ap_retail_cost_of_sales as float)                                  as ap_retail_cost_of_sales  ,
        cast(ap_retail_retailer_retro_funding as float)                         as ap_retail_retailer_retro_funding  ,
        cast(ap_retail_margin_excl_fixed_funding as float)                      as ap_retail_margin_excl_fixed_funding  ,
        cast(ap_retail_promo_fixed_spend as float)                              as ap_retail_promo_fixed_spend  ,
        cast(ap_retail_total_spend as float)                                    as ap_retail_total_spend  ,
        cast(ap_retail_margin_incl_fixed_funding as float)                      as ap_retail_margin_incl_fixed_funding  ,
        cast(ap_retail_revenue_net_excl_mrrsp as float)                         as ap_retail_revenue_net_excl_mrrsp  ,
        cast(ap_retail_revenue_net_excl_rsp as float)                           as ap_retail_revenue_net_excl_rsp  ,
        cast(gl_unit_price as float)                                            as gl_unit_price  ,
        cast(raw_material_unit_price as float)                                  as raw_material_unit_price  ,
        cast(ap_tot_prime_cost_standard_raw as float)                           as ap_tot_prime_cost_standard_raw  ,
        cast(packaging_unit_price as float)                                     as packaging_unit_price  ,
        cast(ap_tot_prime_cost_standard_packaging as float)                     as ap_tot_prime_cost_standard_packaging  ,
        cast(labour_unit_price as float)                                        as labour_unit_price  ,
        cast(ap_tot_prime_cost_standard_labour as float)                        as ap_tot_prime_cost_standard_labour  ,
        cast(bought_in_unit_price as float)                                     as bought_in_unit_price  ,
        cast(ap_tot_prime_cost_standard_bought_in as float)                     as ap_tot_prime_cost_standard_bought_in  ,
        cast(other_unit_price as float)                                         as other_unit_price  ,
        cast(ap_tot_prime_cost_standard_other as float)                         as ap_tot_prime_cost_standard_other  ,
        cast(co_pack_unit_price as float)                                       as co_pack_unit_price  ,
        cast(ap_tot_prime_cost_standard_co_pack as float)                       as ap_tot_prime_cost_standard_co_pack  ,
        -- cast(substring(sls_wtx_fin_forecast_fact_skey,1,16777216) as text(16777216) ) as sls_wtx_fin_forecast_fact_skey  ,
        {{ dbt_utils.surrogate_key([
            "cast(substring(source_system,1,255) as text(255) ) ",
            "cast(substring(plan_source_customer_code,1,255) as text(255) )",
            "cast(substring(source_item_identifier,1,255) as text(255) )",
            "cast(substring(calendar_date,1,255) as text(255) )",
            "cast(substring(scen_code,1,255) as text(255) )",
            "cast(substring(snapshot_date,1,255) as text(255) )"
        ]) }}                                                                   as unique_key
from old_table
),
snpt_fact as (
    select 
        cast(substring(source_system,1,255) as text(255) )                      as source_system  ,
        cast(sku_idx as number(38,0) )                                          as sku_idx  ,
        cast(substring(source_item_identifier,1,255) as text(255) )             as source_item_identifier  ,
        cast(item_guid as text(255) )                                           as item_guid  ,
        cast(cust_idx as number(38,0) )                                         as cust_idx  ,
        cast(substring(plan_source_customer_code,1,255) as text(255) )          as plan_source_customer_code  ,
        cast(substring(customer_address_number_guid,1,255) as text(255) )       as customer_address_number_guid  ,
        cast(snapshot_date as date)                                             as snapshot_date  ,
        cast(calendar_date as timestamp_ntz(9) )                                as calendar_date  ,
        cast(scen_idx as number(38,0) )                                         as scen_idx  ,
        cast(substring(scen_code,1,255) as text(255) )                          as scen_code  ,
        cast(substring(scen_name,1,255) as text(255) )                          as scen_name  ,
        cast(scenario_guid as text(255) )                                       as scenario_guid  ,
        cast(substring(isonpromo_si,1,255) as text(255) )                       as isonpromo_si  ,
        cast(substring(isonpromo_so,1,255) as text(255) )                       as isonpromo_so  ,
        cast(tot_vol_sp_base_uom as float)                                      as tot_vol_sp_base_uom  ,
        cast(tot_vol_sp_kg_uom as float)                                        as tot_vol_sp_kg_uom  ,
        cast(tot_vol_sp_ul_uom as float)                                        as tot_vol_sp_ul_uom  ,
        cast(tot_vol_sp_base_uom_pre_adjustment as float)                       as tot_vol_sp_base_uom_pre_adjustment  ,
        cast(tot_vol_sp_kg_uom_pre_adjustment as float)                         as tot_vol_sp_kg_uom_pre_adjustment  ,
        cast(tot_vol_sp_ul_uom_pre_adjustment as float)                         as tot_vol_sp_ul_uom_pre_adjustment  ,
        cast(tot_vol_sp_base_uom_mgmt_adjustment as float)                      as tot_vol_sp_base_uom_mgmt_adjustment  ,
        cast(tot_vol_sp_kg_uom_mgmt_adjustment as float)                        as tot_vol_sp_kg_uom_mgmt_adjustment  ,
        cast(tot_vol_sp_ul_uom_mgmt_adjustment as float)                        as tot_vol_sp_ul_uom_mgmt_adjustment  ,
        cast(retail_tot_vol_sp_base_uom as float)                               as retail_tot_vol_sp_base_uom  ,
        cast(retail_tot_vol_sp_kg_uom as float)                                 as retail_tot_vol_sp_kg_uom  ,
        cast(retail_tot_vol_sp_ul_uom as float)                                 as retail_tot_vol_sp_ul_uom  ,
        cast(promo_vol as float)                                                as promo_vol  ,
        cast(promo_vol_kg as float)                                             as promo_vol_kg  ,
        cast(promo_vol_ul as float)                                             as promo_vol_ul  ,
        cast(tot_vol_sgl as float)                                              as tot_vol_sgl  ,
        cast(tot_vol_sgl_ca as float)                                           as tot_vol_sgl_ca  ,
        cast(tot_vol_sgl_ul as float)                                           as tot_vol_sgl_ul  ,
        cast(tot_vol_kg as float)                                               as tot_vol_kg  ,
        cast(tot_vol_ca as float)                                               as tot_vol_ca  ,
        cast(tot_vol_ul as float)                                               as tot_vol_ul  ,
        cast(ap_added_value_pack as float)                                      as ap_added_value_pack  ,
        cast(ap_permanent_disc as float)                                        as ap_permanent_disc  ,
        cast(ap_invoiced_sales_value as float)                                  as ap_invoiced_sales_value  ,
        cast(ap_net_sales_value as float)                                       as ap_net_sales_value  ,
        cast(ap_net_realisable_revenue as float)                                as ap_net_realisable_revenue  ,
        cast(ap_variable_trade as float)                                        as ap_variable_trade  ,
        cast(ap_net_net_sales_value as float)                                   as ap_net_net_sales_value  ,
        cast(ap_fixed_trade_cust_invoiced as float)                             as ap_fixed_trade_cust_invoiced  ,
        cast(ap_total_trade_cust_invoiced as float)                             as ap_total_trade_cust_invoiced  ,
        cast(ap_fixed_trade_non_cust_invoiced as float)                         as ap_fixed_trade_non_cust_invoiced  ,
        cast(ap_total_trade as float)                                           as ap_total_trade  ,
        cast(ap_gross_margin_standard as float)                                 as ap_gross_margin_standard  ,
        cast(ap_gross_margin_actual as float)                                   as ap_gross_margin_actual  ,
        cast(ap_gcat_standard as float)                                         as ap_gcat_standard  ,
        cast(ap_gcat_actuals as float)                                          as ap_gcat_actuals  ,
        cast(ap_fixed_annual_payments_pre_adjustment as float)                  as ap_fixed_annual_payments_pre_adjustment  ,
        cast(ap_fixed_annual_payments_mgmt_adjustment as float)                 as ap_fixed_annual_payments_mgmt_adjustment  ,
        cast(ap_fixed_annual_payments as float)                                 as ap_fixed_annual_payments  ,
        cast(ap_category_pre_adjustment as float)                               as ap_category_pre_adjustment  ,
        cast(ap_category_mgmt_adjustment as float)                              as ap_category_mgmt_adjustment  ,
        cast(ap_category as float)                                              as ap_category  ,
        cast(ap_promo_fixed_funding_pre_adjustment as float)                    as ap_promo_fixed_funding_pre_adjustment  ,
        cast(ap_promo_fixed_funding_mgmt_adjustment as float)                   as ap_promo_fixed_funding_mgmt_adjustment  ,
        cast(ap_promo_fixed_funding as float)                                   as ap_promo_fixed_funding  ,
        cast(ap_cash_disc_pre_adjustment as float)                              as ap_cash_disc_pre_adjustment  ,
        cast(ap_cash_disc_mgmt_adjustment as float)                             as ap_cash_disc_mgmt_adjustment  ,
        cast(ap_cash_disc as float)                                             as ap_cash_disc  ,
        cast(ap_direct_shopper_marketing_pre_adjustment as float)               as ap_direct_shopper_marketing_pre_adjustment  ,
        cast(ap_direct_shopper_marketing_mgmt_adjustment as float)              as ap_direct_shopper_marketing_mgmt_adjustment  ,
        cast(ap_direct_shopper_marketing as float)                              as ap_direct_shopper_marketing  ,
        cast(ap_range_support_allowance_pre_adjustment as float)                as ap_range_support_allowance_pre_adjustment  ,
        cast(ap_range_support_allowance_mgmt_adjustment as float)               as ap_range_support_allowance_mgmt_adjustment  ,
        cast(ap_range_support_allowance as float)                               as ap_range_support_allowance  ,
        cast(ap_range_support_incentives_pre_adjustment as float)               as ap_range_support_incentives_pre_adjustment  ,
        cast(ap_range_support_incentives_mgmt_adjustment as float)              as ap_range_support_incentives_mgmt_adjustment  ,
        cast(ap_range_support_incentives as float)                              as ap_range_support_incentives  ,
        cast(ap_indirect_shopper_marketing_pre_adjustment as float)             as ap_indirect_shopper_marketing_pre_adjustment  ,
        cast(ap_indirect_shopper_marketing_mgmt_adjustment as float)            as ap_indirect_shopper_marketing_mgmt_adjustment  ,
        cast(ap_indirect_shopper_marketing as float)                            as ap_indirect_shopper_marketing  ,
        cast(ap_retro_pre_adjustment as float)                                  as ap_retro_pre_adjustment  ,
        cast(ap_retro_mgmt_adjustment as float)                                 as ap_retro_mgmt_adjustment  ,
        cast(ap_retro as float)                                                 as ap_retro  ,
        cast(ap_avp_disc_pre_adjustment as float)                               as ap_avp_disc_pre_adjustment  ,
        cast(ap_avp_disc_mgmt_adjustment as float)                              as ap_avp_disc_mgmt_adjustment  ,
        cast(ap_avp_disc as float)                                              as ap_avp_disc  ,
        cast(ap_everyday_low_prices_pre_adjustment as float)                    as ap_everyday_low_prices_pre_adjustment  ,
        cast(ap_everyday_low_prices_mgmt_adjustment as float)                   as ap_everyday_low_prices_mgmt_adjustment  ,
        cast(ap_everyday_low_prices as float)                                   as ap_everyday_low_prices  ,
        cast(ap_off_invoice_disc_pre_adjustment as float)                       as ap_off_invoice_disc_pre_adjustment  ,
        cast(ap_off_invoice_disc_mgmt_adjustment as float)                      as ap_off_invoice_disc_mgmt_adjustment  ,
        cast(ap_off_invoice_disc as float)                                      as ap_off_invoice_disc  ,
        cast(ap_field_marketing_pre_adjustment as float)                        as ap_field_marketing_pre_adjustment  ,
        cast(ap_field_marketing_mgmt_adjustment as float)                       as ap_field_marketing_mgmt_adjustment  ,
        cast(ap_field_marketing as float)                                       as ap_field_marketing  ,
        cast(ap_tot_prime_cost_variance_pre_adjustment as float)                as ap_tot_prime_cost_variance_pre_adjustment  ,
        cast(ap_tot_prime_cost_variance_mgmt_adjustment as float)               as ap_tot_prime_cost_variance_mgmt_adjustment  ,
        cast(ap_tot_prime_cost_variance as float)                               as ap_tot_prime_cost_variance  ,
        cast(ap_tot_prime_cost_standard_pre_adjustment as float)                as ap_tot_prime_cost_standard_pre_adjustment  ,
        cast(ap_tot_prime_cost_standard_mgmt_adjustment as float)               as ap_tot_prime_cost_standard_mgmt_adjustment  ,
        cast(ap_tot_prime_cost_standard as float)                               as ap_tot_prime_cost_standard  ,
        cast(ap_early_settlement_disc_pre_adjustment as float)                  as ap_early_settlement_disc_pre_adjustment  ,
        cast(ap_early_settlement_disc_mgmt_adjustment as float)                 as ap_early_settlement_disc_mgmt_adjustment  ,
        cast(ap_early_settlement_disc as float)                                 as ap_early_settlement_disc  ,
        cast(ap_other_direct_payments_pre_adjustment as float)                  as ap_other_direct_payments_pre_adjustment  ,
        cast(ap_other_direct_payments_mgmt_adjustment as float)                 as ap_other_direct_payments_mgmt_adjustment  ,
        cast(ap_other_direct_payments as float)                                 as ap_other_direct_payments  ,
        cast(ap_other_indirect_payments_pre_adjustment as float)                as ap_other_indirect_payments_pre_adjustment  ,
        cast(ap_other_indirect_payments_mgmt_adjustment as float)               as ap_other_indirect_payments_mgmt_adjustment  ,
        cast(ap_other_indirect_payments as float)                               as ap_other_indirect_payments  ,
        cast(ap_gross_selling_value_pre_adjustment as float)                    as ap_gross_selling_value_pre_adjustment  ,
        cast(ap_gross_selling_value_mgmt_adjustment as float)                   as ap_gross_selling_value_mgmt_adjustment  ,
        cast(ap_gross_selling_value as float)                                   as ap_gross_selling_value  ,
        cast(ap_gross_sales_value as float)                                     as ap_gross_sales_value  ,
        cast(ap_growth_incentives_pre_adjustment as float)                      as ap_growth_incentives_pre_adjustment  ,
        cast(ap_growth_incentives_mgmt_adjustment as float)                     as ap_growth_incentives_mgmt_adjustment  ,
        cast(ap_growth_incentives as float)                                     as ap_growth_incentives  ,
        cast(retail_tot_vol_sgl as float)                                       as retail_tot_vol_sgl  ,
        cast(retail_tot_vol_sgl_ca as float)                                    as retail_tot_vol_sgl_ca  ,
        cast(retail_tot_vol_sgl_ul as float)                                    as retail_tot_vol_sgl_ul  ,
        cast(retail_tot_vol_kg as float)                                        as retail_tot_vol_kg  ,
        cast(retail_tot_vol_ca as float)                                        as retail_tot_vol_ca  ,
        cast(retail_tot_vol_ul as float)                                        as retail_tot_vol_ul  ,
        cast(ap_retail_revenue_mrrsp as float)                                  as ap_retail_revenue_mrrsp  ,
        cast(ap_retail_revenue_rsp as float)                                    as ap_retail_revenue_rsp  ,
        cast(ap_retail_revenue_net as float)                                    as ap_retail_revenue_net  ,
        cast(ap_retail_cost_of_sales as float)                                  as ap_retail_cost_of_sales  ,
        cast(ap_retail_retailer_retro_funding as float)                         as ap_retail_retailer_retro_funding  ,
        cast(ap_retail_margin_excl_fixed_funding as float)                      as ap_retail_margin_excl_fixed_funding  ,
        cast(ap_retail_promo_fixed_spend as float)                              as ap_retail_promo_fixed_spend  ,
        cast(ap_retail_total_spend as float)                                    as ap_retail_total_spend  ,
        cast(ap_retail_margin_incl_fixed_funding as float)                      as ap_retail_margin_incl_fixed_funding  ,
        cast(ap_retail_revenue_net_excl_mrrsp as float)                         as ap_retail_revenue_net_excl_mrrsp  ,
        cast(ap_retail_revenue_net_excl_rsp as float)                           as ap_retail_revenue_net_excl_rsp  ,
        cast(gl_unit_price as float)                                            as gl_unit_price  ,
        cast(raw_material_unit_price as float)                                  as raw_material_unit_price  ,
        cast(ap_tot_prime_cost_standard_raw as float)                           as ap_tot_prime_cost_standard_raw  ,
        cast(packaging_unit_price as float)                                     as packaging_unit_price  ,
        cast(ap_tot_prime_cost_standard_packaging as float)                     as ap_tot_prime_cost_standard_packaging  ,
        cast(labour_unit_price as float)                                        as labour_unit_price  ,
        cast(ap_tot_prime_cost_standard_labour as float)                        as ap_tot_prime_cost_standard_labour  ,
        cast(bought_in_unit_price as float)                                     as bought_in_unit_price  ,
        cast(ap_tot_prime_cost_standard_bought_in as float)                     as ap_tot_prime_cost_standard_bought_in  ,
        cast(other_unit_price as float)                                         as other_unit_price  ,
        cast(ap_tot_prime_cost_standard_other as float)                         as ap_tot_prime_cost_standard_other  ,
        cast(co_pack_unit_price as float)                                       as co_pack_unit_price  ,
        cast(ap_tot_prime_cost_standard_co_pack as float)                       as ap_tot_prime_cost_standard_co_pack  ,
        -- cast(substring(sls_wtx_fin_forecast_fact_skey,1,16777216) as text(16777216) ) as sls_wtx_fin_forecast_fact_skey  ,
        {{ dbt_utils.surrogate_key([
            "cast(substring(source_system,1,255) as text(255) ) ",
            "cast(substring(plan_source_customer_code,1,255) as text(255) )",
            "cast(substring(source_item_identifier,1,255) as text(255) )",
            "cast(substring(calendar_date,1,255) as text(255) )",
            "cast(substring(scen_code,1,255) as text(255) )",
            "cast(substring(snapshot_date,1,255) as text(255) )"
        ]) }}                                                               as unique_key
from base_fct bf
    
)

select * from snpt_fact
union
select * from old_model
