{{
    config(
        materialized=env_var("DBT_MAT_INCREMENTAL"),
        tags=["wbx","sales", "actuals","sales_actuals"],
        transient=false,
        snowflake_warehouse= env_var("DBT_WBX_SF_WH"),
        unique_key="UNIQUE_KEY",
        full_refresh=false,
        on_schema_change="sync_all_columns",
        pre_hook="""
                {{ truncate_if_exists(this.schema, this.table) }}
                """,
    )
}}

/*
PCOS Currency conversion is handled in this code. Impacted fields are 
        base_ext_ing_cost,
        base_ext_pkg_cost,
        base_ext_lbr_cost,
        base_ext_boughtin_cost,
        base_ext_oth_cost,
        base_ext_copack_cost,
Base currency is EUR and GBP both

*/

/*
SOURCE_LEGACY have values AX,D365 and IBE_HIST.
D365 indicates current data sourced from D365.
AX corresponds to all AX history data
IBE_HIST indicated Iberica history data
*/

with int_view_f as (
    select * from {{ ref('int_f_wbx_sls_order') }}
),

old_fact as
(
    /* Filtering this down so as to NOT PULL AX HISTORY where the Sales Order and Line number are not also in D365.
        If the Sales Order and Line Number are in D365, that means it was converted in D365 itself and so we must suppress it out of
        AX History.
        This logic is in lieu of the normal unique_key check that is later in the code because the unique_key field is changed in D365 
        data even if the Sales Order and Line Number are the same.
    */
    select *
    , trunc(split_part(sales_line_number,'-',1)) as actual_line  -- parsed down to the actual line number, not the generated line number
    from {{ref('conv_fct_wbx_sls_order')}}
    where (sales_order_company, sales_order_number, actual_line) not in (select distinct upper(trim(dataareaid)), salesid, trunc(linenum)  
    from {{ref("src_salesline")}})
),

ibehist as (select *,'IBE_HIST' as source_legacy from {{ ref('fct_wbx_sls_order_ibehist') }}),
int_view_v as (
    select
        source_system,
        sales_line_number,
        sales_order_number,
        source_sales_order_type,
        sales_order_type,
        sales_order_company,
        line_invoice_date,
        line_actual_ship_date,
        base_ext_ing_cost,
        base_ext_pkg_cost,
        base_ext_lbr_cost,
        base_ext_bought_in_cost,
        base_ext_oth_cost,
        base_ext_copack_cost
    from {{ ref('int_v_wtx_mfg_cbom_variant') }}
    qualify row_number() over (
                    partition by
                        source_system,
                        sales_line_number,
                        sales_order_number,
                        source_sales_order_type,
                        sales_order_type,
                        sales_order_company,
                        line_invoice_date,
                        line_actual_ship_date
                    order by 1) =1 

),

fact as (
    select 
        tgt.source_system,
        tgt.sales_line_number,
        tgt.sales_order_number,
        tgt.source_sales_order_type,
        tgt.sales_order_type,
        tgt.sales_order_company,
        source_employee_code,
        employee_guid,
        source_line_type_code,
        line_type_code,
        line_type_desc,
        line_status_code,
        line_status_desc,
        ship_source_customer_code,
        ship_customer_address_guid,
        bill_source_customer_code,
        bill_customer_address_guid,
        ship_source_business_unit_code,
        ship_business_unit_guid,
        default_company_code,
        source_item_identifier,
        item_guid,
        division,
        org_unit_code,
        invoice_document_company,
        invoice_document_number,
        invoice_document_type,
        source_location_code,
        location_guid,
        source_lot_code,
        lot_guid,
        lot_status_code,
        line_ordered_date,
        line_sch_pick_up_date,
        line_prom_ship_date,
        line_cancelled_date,
        tgt.line_invoice_date,
        line_requested_date,
        line_original_promised_date,
        line_promised_delivery_date,
        line_gl_date,
        required_delivery_date,
        lead_time,
        gl_offset_code,
        early_flag,
        late_flag,
        source_business_unit_code,
        business_unit_address_guid,
        original_document_company,
        original_document_number,
        original_document_type,
        original_line_number,
        transfer_po_order_company,
        transfer_po_order_number,
        transfer_po_order_type,
        transfer_po_line_number,
        customer_po_number,
        vendor_ref_code,
        kit_source_item_identifier,
        kit_item_guid,
        kit_line_number,
        kit_component_number,
        component_line_no,
        base_open_amt,
        price_override_flag,
        cost_override_flag,
        source_payment_terms_code,
        payment_terms_guid,
        source_payment_instr_code,
        target_payment_instr_code,
        payment_instr_desc,
        price_adj_schd_code,
        item_price_grp_code,
        pick_slip_no,
        source_freight_handling_code,
        source_freight_handling_desc,
        serial_no,
        basket_price_code,
        transaction_quantity_uom,
        primary_uom,
        transaction_price_uom,
        unit_weight,
        weight_uom,
        unit_volume,
        volume_uom,
        gross_weight,
        gross_weight_uom,
        net_weight,
        net_kg_weight,
        gross_kg_weight,
        short_prim_quantity,
        ordered_prim_quantity,
        shipped_prim_quantity,
        backorder_prim_quantity,
        cancelled_prim_quantity,
        ordered_cwt_quantity,
        shipped_cwt_quantity,
        backord_cwt_quantity,
        cancel_cwt_quantity,
        short_cwt_quantity,
        ordered_ca_quantity,
        shipped_ca_quantity,
        backord_ca_quantity,
        cancel_ca_quantity,
        short_ca_quantity,
        ordered_tran_quantity,
        shipped_tran_quantity,
        cancel_tran_quantity,
        short_tran_quantity,
        backord_tran_quantity,
        ordered_ul_quantity,
        shipped_ul_quantity,
        short_ul_quantity,
        backord_ul_quantity,
        cancel_ul_quantity,
        ordered_kg_quantity,
        shipped_kg_quantity,
        cancel_kg_quantity,
        backord_kg_quantity,
        short_kg_quantity,
        base_currency,
        phi_currency,
        phi_conv_rt,
        mth_phi_conv_rt,
        division_currency,
        pcomp_currency,
        pcomp_conv_rt,
        mth_pcomp_conv_rt,
        base_unit_prim_price,
        base_list_prim_price,
        base_extend_tran_price,
        base_unit_prim_cost,
        base_extend_tran_cost,
        base_rpt_grs_prim_price,
        base_rpt_grs_prim_amt,
        base_rpt_net_prim_price,
        base_rpt_net_prim_amt,
        phi_rpt_grs_prim_amt,
        phi_rpt_grs_prim_price,
        phi_rpt_net_prim_amt,
        phi_rpt_net_prim_price,
        pcomp_rpt_grs_prim_amt,
        pcomp_rpt_grs_prim_price,
        pcomp_rpt_net_prim_amt,
        pcomp_rpt_net_prim_price,
        phi_m_grs_prim_amt,
        phi_m_grs_prim_price,
        phi_m_net_prim_amt,
        phi_m_net_prim_price,
        pcomp_m_grs_prim_amt,
        pcomp_m_grs_prim_price,
        pcomp_m_net_prim_amt,
        pcomp_m_net_prim_price,
        base_rpt_grs_kg_price,
        base_rpt_net_kg_price,
        base_rpt_grs_ca_price,
        base_rpt_net_ca_price,
        phi_rpt_grs_kg_price,
        phi_rpt_net_kg_price,
        phi_rpt_grs_ca_price,
        phi_rpt_net_ca_price,
        pcomp_rpt_grs_kg_price,
        pcomp_rpt_net_kg_price,
        pcomp_rpt_grs_ca_price,
        pcomp_rpt_net_ca_price,
        source_foreign_conv_rt,
        source_updated_d_id,
        source_updated_time,
        short_reason_code,
        short_reason_desc,
        bracket_price,
        list_price_uom,
        load_date,
        update_date,
        transaction_currency,
        trans_conv_rt,
        trans_rpt_grs_amt,
        trans_rpt_grs_price,
        trans_rpt_net_amt,
        trans_rpt_net_price,
        line_item_desc,
        open_prim_quantity,
        open_cwt_quantity,
        open_tran_quantity,
        open_ul_quantity,
        open_kg_quantity,
        mth_trans_conv_rt,
        trans_unit_tran_price,
        trans_list_tran_price,
        trans_extend_tran_price,
        tran_unit_tran_cost,
        trans_extend_tran_cost,
        trans_deduction_01_amt,
        trans_deduction_02_amt,
        trans_deduction_03_amt,
        sales_prim_quantity,
        sales_cwt_quantity,
        sales_ca_quantity,
        sales_tran_quantity,
        sales_ul_quantity,
        sales_kg_quantity,
        tgt.line_actual_ship_date,
        edi_indicator,
        base_deduction_01_amt,
        base_deduction_02_amt,
        base_deduction_03_amt,
        phi_deduction_01_amt,
        phi_deduction_02_amt,
        phi_deduction_03_amt,
        pcomp_deduction_01_amt,
        pcomp_deduction_02_amt,
        pcomp_deduction_03_amt,
        cancel_reason_code,
        cancel_reason_desc,
        trans_quantity_confirmed,
        trans_salesprice_confirmed,
        trans_lineamount_confirmed,
        trans_confirmdate_confirmed,
        trans_uom_confirmed,
        trans_currency_confirmed,
        prim_quantity_confirmed,
        cwt_quantity_confirmed,
        ul_quantity_confirmed,
        kg_quantity_confirmed,
        ca_quantity_confirmed,
        base_lineamount_confirmed,
        phi_lineamount_confirmed,
        pcomp_lineamount_confirmed,
        source_account_identifier,
        source_object_id,
        cost_centre,
        account_guid,
        trans_invoice_grs_amt,
        trans_invoice_net_amt,
        base_invoice_grs_amt,
        base_invoice_net_amt,
        phi_invoice_grs_amt,
        phi_invoice_net_amt,
        pcomp_invoice_grs_amt,
        pcomp_invoice_net_amt,
        variant_code,
        open_ca_quantity,
        src.base_ext_ing_cost,
        src.base_ext_pkg_cost,
        src.base_ext_lbr_cost,
        src.base_ext_bought_in_cost as base_ext_boughtin_cost,
        src.base_ext_oth_cost,
        src.base_ext_copack_cost,
        trans_invoice_disc_amt,
        base_invoice_disc_amt,
        phi_invoice_disc_amt,
        pcomp_invoice_disc_amt,
        delivery_instruction,
        cust_order_number,
        item_shelf_life,
        picking_route,
        trans_line_requested_date,
        unique_key,
        'D365' as source_legacy
    from int_view_f tgt
    left join int_view_v src
        on tgt.source_system = src.source_system
        and tgt.sales_line_number = src.sales_line_number
        and tgt.sales_order_number = src.sales_order_number
        and tgt.source_sales_order_type = src.source_sales_order_type
        and case
            when tgt.sales_order_type is null or trim(tgt.sales_order_type) = ''
            then '-'
            else tgt.sales_order_type
        end = case
            when src.sales_order_type is null or trim(tgt.sales_order_type) = ''
            then '-'
            else src.sales_order_type
        end
        and tgt.sales_order_company = src.sales_order_company
        and case
            when tgt.line_invoice_date is null
            then '9999-12-01'
            else tgt.line_invoice_date
        end = case
            when src.line_invoice_date is null then '9999-12-01' else src.line_invoice_date
        end
        and case
            when tgt.line_actual_ship_date is null
            then '9999-12-01'
            else tgt.line_actual_ship_date
        end = case
            when src.line_actual_ship_date is null
            then '9999-12-01'
            else src.line_actual_ship_date
        end

),

hist as(
    select
a.source_system as source_system,
a.sales_line_number as sales_line_number,
a.sales_order_number as sales_order_number,
a.source_sales_order_type as source_sales_order_type,
a.sales_order_type as sales_order_type,
a.sales_order_company as sales_order_company,
a.source_employee_code as source_employee_code,
a.employee_guid as employee_guid,
a.source_line_type_code as source_line_type_code,
a.line_type_code as line_type_code,
a.line_type_desc as line_type_desc,
a.line_status_code as line_status_code,
a.line_status_desc as line_status_desc,
a.ship_source_customer_code as ship_source_customer_code,
a.ship_customer_address_guid as ship_customer_address_guid,
a.bill_source_customer_code as bill_source_customer_code,
a.bill_customer_address_guid as bill_customer_address_guid,
a.ship_source_business_unit_code as ship_source_business_unit_code,
a.ship_business_unit_guid as ship_business_unit_guid,
a.default_company_code as default_company_code,
a.source_item_identifier as source_item_identifier,
a.item_guid as item_guid,
a.division as division,
a.org_unit_code as org_unit_code,
a.invoice_document_company as invoice_document_company,
a.invoice_document_number as invoice_document_number,
a.invoice_document_type as invoice_document_type,
a.source_location_code as source_location_code,
a.location_guid as location_guid,
a.source_lot_code as source_lot_code,
a.lot_guid as lot_guid,
a.lot_status_code as lot_status_code,
a.line_ordered_date as line_ordered_date,
a.line_sch_pick_up_date as line_sch_pick_up_date,
a.line_prom_ship_date as line_prom_ship_date,
a.line_cancelled_date as line_cancelled_date,
a.line_invoice_date as line_invoice_date,
a.line_requested_date as line_requested_date,
a.line_original_promised_date as line_original_promised_date,
a.line_promised_delivery_date as line_promised_delivery_date,
a.line_gl_date as line_gl_date,
a.required_delivery_date as required_delivery_date,
a.lead_time as lead_time,
a.gl_offset_code as gl_offset_code,
a.early_flag as early_flag,
a.late_flag as late_flag,
a.source_business_unit_code as source_business_unit_code,
a.business_unit_address_guid as business_unit_address_guid,
a.original_document_company as original_document_company,
a.original_document_number as original_document_number,
a.original_document_type as original_document_type,
a.original_line_number as original_line_number,
a.transfer_po_order_company as transfer_po_order_company,
a.transfer_po_order_number as transfer_po_order_number,
a.transfer_po_order_type as transfer_po_order_type,
a.transfer_po_line_number as transfer_po_line_number,
a.customer_po_number as customer_po_number,
a.vendor_ref_code as vendor_ref_code,
a.kit_source_item_identifier as kit_source_item_identifier,
a.kit_item_guid as kit_item_guid,
a.kit_line_number as kit_line_number,
a.kit_component_number as kit_component_number,
a.component_line_no as component_line_no,
a.base_open_amt as base_open_amt,
a.price_override_flag as price_override_flag,
a.cost_override_flag as cost_override_flag,
a.source_payment_terms_code as source_payment_terms_code,
a.payment_terms_guid as payment_terms_guid,
a.source_payment_instr_code as source_payment_instr_code,
a.target_payment_instr_code as target_payment_instr_code,
a.payment_instr_desc as payment_instr_desc,
a.price_adj_schd_code as price_adj_schd_code,
a.item_price_grp_code as item_price_grp_code,
a.pick_slip_no as pick_slip_no,
a.source_freight_handling_code as source_freight_handling_code,
a.source_freight_handling_desc as source_freight_handling_desc,
a.serial_no as serial_no,
a.basket_price_code as basket_price_code,
a.transaction_quantity_uom as transaction_quantity_uom,
a.primary_uom as primary_uom,
a.transaction_price_uom as transaction_price_uom,
a.unit_weight as unit_weight,
a.weight_uom as weight_uom,
a.unit_volume as unit_volume,
a.volume_uom as volume_uom,
a.gross_weight as gross_weight,
a.gross_weight_uom as gross_weight_uom,
a.net_weight as net_weight,
a.net_kg_weight as net_kg_weight,
a.gross_kg_weight as gross_kg_weight,
a.short_prim_quantity as short_prim_quantity,
a.ordered_prim_quantity as ordered_prim_quantity,
a.shipped_prim_quantity as shipped_prim_quantity,
a.backorder_prim_quantity as backorder_prim_quantity,
a.cancelled_prim_quantity as cancelled_prim_quantity,
a.ordered_cwt_quantity as ordered_cwt_quantity,
a.shipped_cwt_quantity as shipped_cwt_quantity,
a.backord_cwt_quantity as backord_cwt_quantity,
a.cancel_cwt_quantity as cancel_cwt_quantity,
a.short_cwt_quantity as short_cwt_quantity,
a.ordered_ca_quantity as ordered_ca_quantity,
a.shipped_ca_quantity as shipped_ca_quantity,
a.backord_ca_quantity as backord_ca_quantity,
a.cancel_ca_quantity as cancel_ca_quantity,
a.short_ca_quantity as short_ca_quantity,
a.ordered_tran_quantity as ordered_tran_quantity,
a.shipped_tran_quantity as shipped_tran_quantity,
a.cancel_tran_quantity as cancel_tran_quantity,
a.short_tran_quantity as short_tran_quantity,
a.backord_tran_quantity as backord_tran_quantity,
a.ordered_ul_quantity as ordered_ul_quantity,
a.shipped_ul_quantity as shipped_ul_quantity,
a.short_ul_quantity as short_ul_quantity,
a.backord_ul_quantity as backord_ul_quantity,
a.cancel_ul_quantity as cancel_ul_quantity,
a.ordered_kg_quantity as ordered_kg_quantity,
a.shipped_kg_quantity as shipped_kg_quantity,
a.cancel_kg_quantity as cancel_kg_quantity,
a.backord_kg_quantity as backord_kg_quantity,
a.short_kg_quantity as short_kg_quantity,
a.base_currency as base_currency,
a.phi_currency as phi_currency,
a.phi_conv_rt as phi_conv_rt,
a.mth_phi_conv_rt as mth_phi_conv_rt,
a.division_currency as division_currency,
a.pcomp_currency as pcomp_currency,
a.pcomp_conv_rt as pcomp_conv_rt,
a.mth_pcomp_conv_rt as mth_pcomp_conv_rt,
a.base_unit_prim_price as base_unit_prim_price,
a.base_list_prim_price as base_list_prim_price,
a.base_extend_tran_price as base_extend_tran_price,
a.base_unit_prim_cost as base_unit_prim_cost,
a.base_extend_tran_cost as base_extend_tran_cost,
a.base_rpt_grs_prim_price as base_rpt_grs_prim_price,
a.base_rpt_grs_prim_amt as base_rpt_grs_prim_amt,
a.base_rpt_net_prim_price as base_rpt_net_prim_price,
a.base_rpt_net_prim_amt as base_rpt_net_prim_amt,
a.phi_rpt_grs_prim_amt as phi_rpt_grs_prim_amt,
a.phi_rpt_grs_prim_price as phi_rpt_grs_prim_price,
a.phi_rpt_net_prim_amt as phi_rpt_net_prim_amt,
a.phi_rpt_net_prim_price as phi_rpt_net_prim_price,
a.pcomp_rpt_grs_prim_amt as pcomp_rpt_grs_prim_amt,
a.pcomp_rpt_grs_prim_price as pcomp_rpt_grs_prim_price,
a.pcomp_rpt_net_prim_amt as pcomp_rpt_net_prim_amt,
a.pcomp_rpt_net_prim_price as pcomp_rpt_net_prim_price,
a.phi_m_grs_prim_amt as phi_m_grs_prim_amt,
a.phi_m_grs_prim_price as phi_m_grs_prim_price,
a.phi_m_net_prim_amt as phi_m_net_prim_amt,
a.phi_m_net_prim_price as phi_m_net_prim_price,
a.pcomp_m_grs_prim_amt as pcomp_m_grs_prim_amt,
a.pcomp_m_grs_prim_price as pcomp_m_grs_prim_price,
a.pcomp_m_net_prim_amt as pcomp_m_net_prim_amt,
a.pcomp_m_net_prim_price as pcomp_m_net_prim_price,
a.base_rpt_grs_kg_price as base_rpt_grs_kg_price,
a.base_rpt_net_kg_price as base_rpt_net_kg_price,
a.base_rpt_grs_ca_price as base_rpt_grs_ca_price,
a.base_rpt_net_ca_price as base_rpt_net_ca_price,
a.phi_rpt_grs_kg_price as phi_rpt_grs_kg_price,
a.phi_rpt_net_kg_price as phi_rpt_net_kg_price,
a.phi_rpt_grs_ca_price as phi_rpt_grs_ca_price,
a.phi_rpt_net_ca_price as phi_rpt_net_ca_price,
a.pcomp_rpt_grs_kg_price as pcomp_rpt_grs_kg_price,
a.pcomp_rpt_net_kg_price as pcomp_rpt_net_kg_price,
a.pcomp_rpt_grs_ca_price as pcomp_rpt_grs_ca_price,
a.pcomp_rpt_net_ca_price as pcomp_rpt_net_ca_price,
a.source_foreign_conv_rt as source_foreign_conv_rt,
a.source_updated_d_id as source_updated_d_id,
a.source_updated_time as source_updated_time,
a.short_reason_code as short_reason_code,
a.short_reason_desc as short_reason_desc,
a.bracket_price as bracket_price,
a.list_price_uom as list_price_uom,
a.load_date as load_date,
a.update_date as update_date,
a.transaction_currency as transaction_currency,
a.trans_conv_rt as trans_conv_rt,
a.trans_rpt_grs_amt as trans_rpt_grs_amt,
a.trans_rpt_grs_price as trans_rpt_grs_price,
a.trans_rpt_net_amt as trans_rpt_net_amt,
a.trans_rpt_net_price as trans_rpt_net_price,
a.line_item_desc as line_item_desc,
a.open_prim_quantity as open_prim_quantity,
a.open_cwt_quantity as open_cwt_quantity,
a.open_tran_quantity as open_tran_quantity,
a.open_ul_quantity as open_ul_quantity,
a.open_kg_quantity as open_kg_quantity,
a.mth_trans_conv_rt as mth_trans_conv_rt,
a.trans_unit_tran_price as trans_unit_tran_price,
a.trans_list_tran_price as trans_list_tran_price,
a.trans_extend_tran_price as trans_extend_tran_price,
a.tran_unit_tran_cost as tran_unit_tran_cost,
a.trans_extend_tran_cost as trans_extend_tran_cost,
a.trans_deduction_01_amt as trans_deduction_01_amt,
a.trans_deduction_02_amt as trans_deduction_02_amt,
a.trans_deduction_03_amt as trans_deduction_03_amt,
a.sales_prim_quantity as sales_prim_quantity,
a.sales_cwt_quantity as sales_cwt_quantity,
a.sales_ca_quantity as sales_ca_quantity,
a.sales_tran_quantity as sales_tran_quantity,
a.sales_ul_quantity as sales_ul_quantity,
a.sales_kg_quantity as sales_kg_quantity,
a.line_actual_ship_date as line_actual_ship_date,
a.edi_indicator as edi_indicator,
a.base_deduction_01_amt as base_deduction_01_amt,
a.base_deduction_02_amt as base_deduction_02_amt,
a.base_deduction_03_amt as base_deduction_03_amt,
a.phi_deduction_01_amt as phi_deduction_01_amt,
a.phi_deduction_02_amt as phi_deduction_02_amt,
a.phi_deduction_03_amt as phi_deduction_03_amt,
a.pcomp_deduction_01_amt as pcomp_deduction_01_amt,
a.pcomp_deduction_02_amt as pcomp_deduction_02_amt,
a.pcomp_deduction_03_amt as pcomp_deduction_03_amt,
a.cancel_reason_code as cancel_reason_code,
a.cancel_reason_desc as cancel_reason_desc,
a.trans_quantity_confirmed as trans_quantity_confirmed,
a.trans_salesprice_confirmed as trans_salesprice_confirmed,
a.trans_lineamount_confirmed as trans_lineamount_confirmed,
a.trans_confirmdate_confirmed as trans_confirmdate_confirmed,
a.trans_uom_confirmed as trans_uom_confirmed,
a.trans_currency_confirmed as trans_currency_confirmed,
a.prim_quantity_confirmed as prim_quantity_confirmed,
a.cwt_quantity_confirmed as cwt_quantity_confirmed,
a.ul_quantity_confirmed as ul_quantity_confirmed,
a.kg_quantity_confirmed as kg_quantity_confirmed,
a.ca_quantity_confirmed as ca_quantity_confirmed,
a.base_lineamount_confirmed as base_lineamount_confirmed,
a.phi_lineamount_confirmed as phi_lineamount_confirmed,
a.pcomp_lineamount_confirmed as pcomp_lineamount_confirmed,
a.source_account_identifier as source_account_identifier,
a.source_object_id as source_object_id,
a.cost_centre as cost_centre,
a.account_guid as account_guid,
a.trans_invoice_grs_amt as trans_invoice_grs_amt,
a.trans_invoice_net_amt as trans_invoice_net_amt,
a.base_invoice_grs_amt as base_invoice_grs_amt,
a.base_invoice_net_amt as base_invoice_net_amt,
a.phi_invoice_grs_amt as phi_invoice_grs_amt,
a.phi_invoice_net_amt as phi_invoice_net_amt,
a.pcomp_invoice_grs_amt as pcomp_invoice_grs_amt,
a.pcomp_invoice_net_amt as pcomp_invoice_net_amt,
a.variant_code as variant_code,
a.open_ca_quantity as open_ca_quantity,
a.base_ext_ing_cost as base_ext_ing_cost,
a.base_ext_pkg_cost as base_ext_pkg_cost,
a.base_ext_lbr_cost as base_ext_lbr_cost,
a.base_ext_boughtin_cost as base_ext_boughtin_cost,
a.base_ext_oth_cost as base_ext_oth_cost,
a.base_ext_copack_cost as base_ext_copack_cost,
a.trans_invoice_disc_amt as trans_invoice_disc_amt,
a.base_invoice_disc_amt as base_invoice_disc_amt,
a.phi_invoice_disc_amt as phi_invoice_disc_amt,
a.pcomp_invoice_disc_amt as pcomp_invoice_disc_amt,
a.delivery_instruction as delivery_instruction,
a.cust_order_number as cust_order_number,
a.item_shelf_life as item_shelf_life,
a.picking_route as picking_route,
a.trans_line_requested_date as trans_line_requested_date,
a.unique_key,
a.source_legacy
from old_fact a
--left join fact b on a.unique_key =b.unique_key where b.source_system is null
/* This left join, which normally ensures that we do not pull rows from AX history that were migrated over to D365 is handled in the earlier filtering logic 
    against the conv model itself.
    This is specific to Sales Order (lines) and some other models where the UNIQUE_KEY logic doesn't suffice.
*/

),

all_records as 
(
    select * from fact
    union all 
    select * from ibehist 
    union all
    select * from hist 
),

currency_conv as 
(
select 
        source_system,
        sales_line_number,
        sales_order_number,
        source_sales_order_type,
        sales_order_type,
        sales_order_company,
        source_employee_code,
        employee_guid,
        source_line_type_code,
        line_type_code,
        line_type_desc,
        line_status_code,
        line_status_desc,
        ship_source_customer_code,
        ship_customer_address_guid,
        bill_source_customer_code,
        bill_customer_address_guid,
        ship_source_business_unit_code,
        ship_business_unit_guid,
        default_company_code,
        source_item_identifier,
        item_guid,
        division,
        org_unit_code,
        invoice_document_company,
        invoice_document_number,
        invoice_document_type,
        source_location_code,
        location_guid,
        source_lot_code,
        lot_guid,
        lot_status_code,
        line_ordered_date,
        line_sch_pick_up_date,
        line_prom_ship_date,
        line_cancelled_date,
        line_invoice_date,
        line_requested_date,
        line_original_promised_date,
        line_promised_delivery_date,
        line_gl_date,
        required_delivery_date,
        lead_time,
        gl_offset_code,
        early_flag,
        late_flag,
        source_business_unit_code,
        business_unit_address_guid,
        original_document_company,
        original_document_number,
        original_document_type,
        original_line_number,
        transfer_po_order_company,
        transfer_po_order_number,
        transfer_po_order_type,
        transfer_po_line_number,
        customer_po_number,
        vendor_ref_code,
        kit_source_item_identifier,
        kit_item_guid,
        kit_line_number,
        kit_component_number,
        component_line_no,
        base_open_amt,
        price_override_flag,
        cost_override_flag,
        source_payment_terms_code,
        payment_terms_guid,
        source_payment_instr_code,
        target_payment_instr_code,
        payment_instr_desc,
        price_adj_schd_code,
        item_price_grp_code,
        pick_slip_no,
        source_freight_handling_code,
        source_freight_handling_desc,
        serial_no,
        basket_price_code,
        transaction_quantity_uom,
        primary_uom,
        transaction_price_uom,
        unit_weight,
        weight_uom,
        unit_volume,
        volume_uom,
        gross_weight,
        gross_weight_uom,
        net_weight,
        net_kg_weight,
        gross_kg_weight,
        short_prim_quantity,
        ordered_prim_quantity,
        shipped_prim_quantity,
        backorder_prim_quantity,
        cancelled_prim_quantity,
        ordered_cwt_quantity,
        shipped_cwt_quantity,
        backord_cwt_quantity,
        cancel_cwt_quantity,
        short_cwt_quantity,
        ordered_ca_quantity,
        shipped_ca_quantity,
        backord_ca_quantity,
        cancel_ca_quantity,
        short_ca_quantity,
        ordered_tran_quantity,
        shipped_tran_quantity,
        cancel_tran_quantity,
        short_tran_quantity,
        backord_tran_quantity,
        ordered_ul_quantity,
        shipped_ul_quantity,
        short_ul_quantity,
        backord_ul_quantity,
        cancel_ul_quantity,
        ordered_kg_quantity,
        shipped_kg_quantity,
        cancel_kg_quantity,
        backord_kg_quantity,
        short_kg_quantity,
        base_currency,
        phi_currency,
        phi_conv_rt,
        mth_phi_conv_rt,
        division_currency,
        pcomp_currency,
        pcomp_conv_rt,
        mth_pcomp_conv_rt,
        base_unit_prim_price,
        base_list_prim_price,
        base_extend_tran_price,
        base_unit_prim_cost,
        base_extend_tran_cost,
        base_rpt_grs_prim_price,
        base_rpt_grs_prim_amt,
        base_rpt_net_prim_price,
        base_rpt_net_prim_amt,
        phi_rpt_grs_prim_amt,
        phi_rpt_grs_prim_price,
        phi_rpt_net_prim_amt,
        phi_rpt_net_prim_price,
        pcomp_rpt_grs_prim_amt,
        pcomp_rpt_grs_prim_price,
        pcomp_rpt_net_prim_amt,
        pcomp_rpt_net_prim_price,
        phi_m_grs_prim_amt,
        phi_m_grs_prim_price,
        phi_m_net_prim_amt,
        phi_m_net_prim_price,
        pcomp_m_grs_prim_amt,
        pcomp_m_grs_prim_price,
        pcomp_m_net_prim_amt,
        pcomp_m_net_prim_price,
        base_rpt_grs_kg_price,
        base_rpt_net_kg_price,
        base_rpt_grs_ca_price,
        base_rpt_net_ca_price,
        phi_rpt_grs_kg_price,
        phi_rpt_net_kg_price,
        phi_rpt_grs_ca_price,
        phi_rpt_net_ca_price,
        pcomp_rpt_grs_kg_price,
        pcomp_rpt_net_kg_price,
        pcomp_rpt_grs_ca_price,
        pcomp_rpt_net_ca_price,
        source_foreign_conv_rt,
        source_updated_d_id,
        source_updated_time,
        short_reason_code,
        short_reason_desc,
        bracket_price,
        list_price_uom,
        load_date,
        update_date,
        transaction_currency,
        trans_conv_rt,
        trans_rpt_grs_amt,
        trans_rpt_grs_price,
        trans_rpt_net_amt,
        trans_rpt_net_price,
        line_item_desc,
        open_prim_quantity,
        open_cwt_quantity,
        open_tran_quantity,
        open_ul_quantity,
        open_kg_quantity,
        mth_trans_conv_rt,
        trans_unit_tran_price,
        trans_list_tran_price,
        trans_extend_tran_price,
        tran_unit_tran_cost,
        trans_extend_tran_cost,
        trans_deduction_01_amt,
        trans_deduction_02_amt,
        trans_deduction_03_amt,
        sales_prim_quantity,
        sales_cwt_quantity,
        sales_ca_quantity,
        sales_tran_quantity,
        sales_ul_quantity,
        sales_kg_quantity,
        line_actual_ship_date,
        edi_indicator,
        base_deduction_01_amt,
        base_deduction_02_amt,
        base_deduction_03_amt,
        phi_deduction_01_amt,
        phi_deduction_02_amt,
        phi_deduction_03_amt,
        pcomp_deduction_01_amt,
        pcomp_deduction_02_amt,
        pcomp_deduction_03_amt,
        cancel_reason_code,
        cancel_reason_desc,
        trans_quantity_confirmed,
        trans_salesprice_confirmed,
        trans_lineamount_confirmed,
        trans_confirmdate_confirmed,
        trans_uom_confirmed,
        trans_currency_confirmed,
        prim_quantity_confirmed,
        cwt_quantity_confirmed,
        ul_quantity_confirmed,
        kg_quantity_confirmed,
        ca_quantity_confirmed,
        base_lineamount_confirmed,
        phi_lineamount_confirmed,
        pcomp_lineamount_confirmed,
        source_account_identifier,
        source_object_id,
        cost_centre,
        account_guid,
        trans_invoice_grs_amt,
        trans_invoice_net_amt,
        base_invoice_grs_amt,
        base_invoice_net_amt,
        phi_invoice_grs_amt,
        phi_invoice_net_amt,
        pcomp_invoice_grs_amt,
        pcomp_invoice_net_amt,
        variant_code,
        open_ca_quantity,
        base_ext_ing_cost,
        base_ext_pkg_cost,
        base_ext_lbr_cost,
        base_ext_boughtin_cost,
        base_ext_oth_cost,
        base_ext_copack_cost,
        coalesce(base_ext_ing_cost * trans_conv_rt,0) as trans_ext_ing_cost,
        coalesce(base_ext_pkg_cost * trans_conv_rt,0) as trans_ext_pkg_cost,
        coalesce(base_ext_lbr_cost * trans_conv_rt,0) as trans_ext_lbr_cost,
        coalesce(base_ext_boughtin_cost * trans_conv_rt,0) as trans_ext_boughtin_cost,
        coalesce(base_ext_oth_cost * trans_conv_rt,0) as trans_ext_oth_cost,
        coalesce(base_ext_copack_cost * trans_conv_rt,0) as trans_ext_copack_cost,
        --phi conversion
        coalesce(base_ext_ing_cost * phi_conv_rt,0) as phi_ext_ing_cost,
        coalesce(base_ext_pkg_cost * phi_conv_rt,0) as phi_ext_pkg_cost,
        coalesce(base_ext_lbr_cost * phi_conv_rt,0) as phi_ext_lbr_cost,
        coalesce(base_ext_boughtin_cost * phi_conv_rt,0) as phi_ext_boughtin_cost,
        coalesce(base_ext_oth_cost * phi_conv_rt,0) as phi_ext_oth_cost,
        coalesce(base_ext_copack_cost * phi_conv_rt,0) as phi_ext_copack_cost,
        --pcomp conversion
        coalesce(base_ext_ing_cost * pcomp_conv_rt,0) as pcomp_ext_ing_cost,
        coalesce(base_ext_pkg_cost * pcomp_conv_rt,0) as pcomp_ext_pkg_cost,
        coalesce(base_ext_lbr_cost * pcomp_conv_rt,0) as pcomp_ext_lbr_cost,
        coalesce(base_ext_boughtin_cost * pcomp_conv_rt,0) as pcomp_ext_boughtin_cost,
        coalesce(base_ext_oth_cost * pcomp_conv_rt,0) as pcomp_ext_oth_cost,
        coalesce(base_ext_copack_cost * pcomp_conv_rt,0) as pcomp_ext_copack_cost,
        trans_invoice_disc_amt,
        base_invoice_disc_amt,
        phi_invoice_disc_amt,
        pcomp_invoice_disc_amt,
        delivery_instruction,
        cust_order_number,
        item_shelf_life,
        picking_route,
        trans_line_requested_date,
        unique_key,
        source_legacy
    from all_records 
),
final as 
(
    select 
        cast(substring(source_system,1,255) as text(255) ) as source_system  ,
        cast(substring(sales_line_number,1,255) as text(255) ) as sales_line_number  ,
        cast(substring(sales_order_number,1,255) as text(255) ) as sales_order_number  ,
        cast(substring(source_sales_order_type,1,30) as text(30) ) as source_sales_order_type  ,
        cast(substring(sales_order_type,1,30) as text(30) ) as sales_order_type  ,
        cast(substring(sales_order_company,1,20) as text(20) ) as sales_order_company  ,
        cast(substring(source_employee_code,1,255) as text(255) ) as source_employee_code  ,
        cast(employee_guid as text(255) ) as employee_guid  ,
        cast(substring(source_line_type_code,1,255) as text(255) ) as source_line_type_code  ,
        cast(substring(line_type_code,1,255) as text(255) ) as line_type_code  ,
        cast(substring(line_type_desc,1,255) as text(255) ) as line_type_desc  ,
        cast(line_status_code as number(38,0) ) as line_status_code  ,
        cast(substring(line_status_desc,1,255) as text(255) ) as line_status_desc  ,
        cast(substring(ship_source_customer_code,1,255) as text(255) ) as ship_source_customer_code  ,
        cast(ship_customer_address_guid as text(255) ) as ship_customer_address_guid  ,
        cast(substring(bill_source_customer_code,1,255) as text(255) ) as bill_source_customer_code  ,
        cast(bill_customer_address_guid as text(255) ) as bill_customer_address_guid  ,
        cast(substring(ship_source_business_unit_code,1,255) as text(255) ) as ship_source_business_unit_code  ,
        cast(ship_business_unit_guid as text(255) ) as ship_business_unit_guid  ,
        cast(substring(default_company_code,1,255) as text(255) ) as default_company_code  ,
        cast(substring(source_item_identifier,1,255) as text(255) ) as source_item_identifier  ,
        cast(item_guid as text(255) ) as item_guid  ,
        cast(substring(division,1,255) as text(255) ) as division  ,
        cast(substring(org_unit_code,1,255) as text(255) ) as org_unit_code  ,
        cast(substring(invoice_document_company,1,255) as text(255) ) as invoice_document_company  ,
        cast(substring(invoice_document_number,1,255) as text(255) ) as invoice_document_number  ,
        cast(substring(invoice_document_type,1,255) as text(255) ) as invoice_document_type  ,
        cast(substring(source_location_code,1,255) as text(255) ) as source_location_code  ,
        cast(location_guid as text(255) ) as location_guid  ,
        cast(substring(source_lot_code,1,255) as text(255) ) as source_lot_code  ,
        cast(lot_guid as text(255) ) as lot_guid  ,
        cast(substring(lot_status_code,1,255) as text(255) ) as lot_status_code  ,
        cast(line_ordered_date as timestamp_ntz(9) ) as line_ordered_date  ,
        cast(line_sch_pick_up_date as timestamp_ntz(9) ) as line_sch_pick_up_date  ,
        cast(line_prom_ship_date as timestamp_ntz(9) ) as line_prom_ship_date  ,
        cast(line_cancelled_date as timestamp_ntz(9) ) as line_cancelled_date  ,
        cast(line_invoice_date as timestamp_ntz(9) ) as line_invoice_date  ,
        cast(line_requested_date as timestamp_ntz(9) ) as line_requested_date  ,
        cast(line_original_promised_date as timestamp_ntz(9) ) as line_original_promised_date  ,
        cast(line_promised_delivery_date as timestamp_ntz(9) ) as line_promised_delivery_date  ,
        cast(line_gl_date as timestamp_ntz(9) ) as line_gl_date  ,
        cast(required_delivery_date as timestamp_ntz(9) ) as required_delivery_date  ,
        cast(lead_time as number(38,0) ) as lead_time  ,
        cast(substring(gl_offset_code,1,255) as text(255) ) as gl_offset_code  ,
        cast(substring(early_flag,1,255) as text(255) ) as early_flag  ,
        cast(substring(late_flag,1,255) as text(255) ) as late_flag  ,
        cast(substring(source_business_unit_code,1,255) as text(255) ) as source_business_unit_code  ,
        cast(business_unit_address_guid as text(255) ) as business_unit_address_guid  ,
        cast(substring(original_document_company,1,255) as text(255) ) as original_document_company  ,
        cast(substring(original_document_number,1,255) as text(255) ) as original_document_number  ,
        cast(substring(original_document_type,1,255) as text(255) ) as original_document_type  ,
        cast(substring(original_line_number,1,255) as text(255) ) as original_line_number  ,
        cast(substring(transfer_po_order_company,1,255) as text(255) ) as transfer_po_order_company  ,
        cast(substring(transfer_po_order_number,1,255) as text(255) ) as transfer_po_order_number  ,
        cast(substring(transfer_po_order_type,1,255) as text(255) ) as transfer_po_order_type  ,
        cast(substring(transfer_po_line_number,1,255) as text(255) ) as transfer_po_line_number  ,
        cast(substring(customer_po_number,1,255) as text(255) ) as customer_po_number  ,
        cast(substring(vendor_ref_code,1,255) as text(255) ) as vendor_ref_code  ,
        cast(substring(kit_source_item_identifier,1,255) as text(255) ) as kit_source_item_identifier  ,
        cast(kit_item_guid as text(255) ) as kit_item_guid  ,
        cast(substring(kit_line_number,1,255) as text(255) ) as kit_line_number  ,
        cast(substring(kit_component_number,1,255) as text(255) ) as kit_component_number  ,
        cast(substring(component_line_no,1,255) as text(255) ) as component_line_no  ,
        cast(base_open_amt as number(38,0) ) as base_open_amt  ,
        cast(substring(price_override_flag,1,4) as text(4) ) as price_override_flag  ,
        cast(substring(cost_override_flag,1,4) as text(4) ) as cost_override_flag  ,
        cast(substring(source_payment_terms_code,1,255) as text(255) ) as source_payment_terms_code  ,
        cast(payment_terms_guid as text(255) ) as payment_terms_guid  ,
        cast(substring(source_payment_instr_code,1,60) as text(60) ) as source_payment_instr_code  ,
        cast(substring(target_payment_instr_code,1,60) as text(60) ) as target_payment_instr_code  ,
        cast(substring(payment_instr_desc,1,255) as text(255) ) as payment_instr_desc  ,
        cast(substring(price_adj_schd_code,1,8) as text(8) ) as price_adj_schd_code  ,
        cast(substring(item_price_grp_code,1,30) as text(30) ) as item_price_grp_code  ,
        cast(substring(pick_slip_no,1,30) as text(30) ) as pick_slip_no  ,
        cast(substring(source_freight_handling_code,1,20) as text(20) ) as source_freight_handling_code  ,
        cast(substring(source_freight_handling_desc,1,255) as text(255) ) as source_freight_handling_desc  ,
        cast(substring(serial_no,1,30) as text(30) ) as serial_no  ,
        cast(substring(basket_price_code,1,30) as text(30) ) as basket_price_code  ,
        cast(substring(transaction_quantity_uom,1,15) as text(15) ) as transaction_quantity_uom  ,
        cast(substring(primary_uom,1,255) as text(255) ) as primary_uom  ,
        cast(substring(transaction_price_uom,1,255) as text(255) ) as transaction_price_uom  ,
        cast(unit_weight as number(38,0) ) as unit_weight  ,
        cast(substring(weight_uom,1,255) as text(255) ) as weight_uom  ,
        cast(unit_volume as number(38,0) ) as unit_volume  ,
        cast(substring(volume_uom,1,16) as text(16) ) as volume_uom  ,
        cast(gross_weight as number(38,10) ) as gross_weight  ,
        cast(substring(gross_weight_uom,1,15) as text(15) ) as gross_weight_uom  ,
        cast(net_weight as number(38,10) ) as net_weight  ,
        cast(net_kg_weight as number(38,10) ) as net_kg_weight  ,
        cast(gross_kg_weight as number(38,10) ) as gross_kg_weight  ,
        cast(short_prim_quantity as number(19,2) ) as short_prim_quantity  ,
        cast(ordered_prim_quantity as number(19,2) ) as ordered_prim_quantity  ,
        cast(shipped_prim_quantity as number(19,2) ) as shipped_prim_quantity  ,
        cast(backorder_prim_quantity as number(19,2) ) as backorder_prim_quantity  ,
        cast(cancelled_prim_quantity as number(19,2) ) as cancelled_prim_quantity  ,
        cast(ordered_cwt_quantity as number(19,2) ) as ordered_cwt_quantity  ,
        cast(shipped_cwt_quantity as number(19,2) ) as shipped_cwt_quantity  ,
        cast(backord_cwt_quantity as number(19,2) ) as backord_cwt_quantity  ,
        cast(cancel_cwt_quantity as number(19,2) ) as cancel_cwt_quantity  ,
        cast(short_cwt_quantity as number(19,2) ) as short_cwt_quantity  ,
        cast(ordered_ca_quantity as number(19,2) ) as ordered_ca_quantity  ,
        cast(shipped_ca_quantity as number(19,2) ) as shipped_ca_quantity  ,
        cast(backord_ca_quantity as number(19,2) ) as backord_ca_quantity  ,
        cast(cancel_ca_quantity as number(19,2) ) as cancel_ca_quantity  ,
        cast(short_ca_quantity as number(19,2) ) as short_ca_quantity  ,
        cast(ordered_tran_quantity as number(19,2) ) as ordered_tran_quantity  ,
        cast(shipped_tran_quantity as number(19,2) ) as shipped_tran_quantity  ,
        cast(cancel_tran_quantity as number(19,2) ) as cancel_tran_quantity  ,
        cast(short_tran_quantity as number(19,2) ) as short_tran_quantity  ,
        cast(backord_tran_quantity as number(19,2) ) as backord_tran_quantity  ,
        cast(ordered_ul_quantity as number(19,2) ) as ordered_ul_quantity  ,
        cast(shipped_ul_quantity as number(19,2) ) as shipped_ul_quantity  ,
        cast(short_ul_quantity as number(19,2) ) as short_ul_quantity  ,
        cast(backord_ul_quantity as number(19,2) ) as backord_ul_quantity  ,
        cast(cancel_ul_quantity as number(19,2) ) as cancel_ul_quantity  ,
        cast(ordered_kg_quantity as number(19,2) ) as ordered_kg_quantity  ,
        cast(shipped_kg_quantity as number(19,2) ) as shipped_kg_quantity  ,
        cast(cancel_kg_quantity as number(19,2) ) as cancel_kg_quantity  ,
        cast(backord_kg_quantity as number(19,2) ) as backord_kg_quantity  ,
        cast(short_kg_quantity as number(19,2) ) as short_kg_quantity  ,
        cast(substring(base_currency,1,6) as text(6) ) as base_currency  ,
        cast(substring(phi_currency,1,6) as text(6) ) as phi_currency  ,
        cast(phi_conv_rt as number(29,7) ) as phi_conv_rt  ,
        cast(mth_phi_conv_rt as number(29,7) ) as mth_phi_conv_rt  ,
        cast(substring(division_currency,1,6) as text(6) ) as division_currency  ,
        cast(substring(pcomp_currency,1,6) as text(6) ) as pcomp_currency  ,
        cast(pcomp_conv_rt as number(29,7) ) as pcomp_conv_rt  ,
        cast(mth_pcomp_conv_rt as number(29,7) ) as mth_pcomp_conv_rt  ,
        cast(base_unit_prim_price as number(21,4) ) as base_unit_prim_price  ,
        cast(base_list_prim_price as number(21,4) ) as base_list_prim_price  ,
        cast(base_extend_tran_price as number(21,4) ) as base_extend_tran_price  ,
        cast(base_unit_prim_cost as number(21,4) ) as base_unit_prim_cost  ,
        cast(base_extend_tran_cost as number(21,4) ) as base_extend_tran_cost  ,
        cast(base_rpt_grs_prim_price as number(21,4) ) as base_rpt_grs_prim_price  ,
        cast(base_rpt_grs_prim_amt as number(21,4) ) as base_rpt_grs_prim_amt  ,
        cast(base_rpt_net_prim_price as number(21,4) ) as base_rpt_net_prim_price  ,
        cast(base_rpt_net_prim_amt as number(21,4) ) as base_rpt_net_prim_amt  ,
        cast(phi_rpt_grs_prim_amt as number(21,4) ) as phi_rpt_grs_prim_amt  ,
        cast(phi_rpt_grs_prim_price as number(21,4) ) as phi_rpt_grs_prim_price  ,
        cast(phi_rpt_net_prim_amt as number(21,4) ) as phi_rpt_net_prim_amt  ,
        cast(phi_rpt_net_prim_price as number(21,4) ) as phi_rpt_net_prim_price  ,
        cast(pcomp_rpt_grs_prim_amt as number(21,4) ) as pcomp_rpt_grs_prim_amt  ,
        cast(pcomp_rpt_grs_prim_price as number(21,4) ) as pcomp_rpt_grs_prim_price  ,
        cast(pcomp_rpt_net_prim_amt as number(21,4) ) as pcomp_rpt_net_prim_amt  ,
        cast(pcomp_rpt_net_prim_price as number(21,4) ) as pcomp_rpt_net_prim_price  ,
        cast(phi_m_grs_prim_amt as number(21,4) ) as phi_m_grs_prim_amt  ,
        cast(phi_m_grs_prim_price as number(21,4) ) as phi_m_grs_prim_price  ,
        cast(phi_m_net_prim_amt as number(21,4) ) as phi_m_net_prim_amt  ,
        cast(phi_m_net_prim_price as number(21,4) ) as phi_m_net_prim_price  ,
        cast(pcomp_m_grs_prim_amt as number(21,4) ) as pcomp_m_grs_prim_amt  ,
        cast(pcomp_m_grs_prim_price as number(21,4) ) as pcomp_m_grs_prim_price  ,
        cast(pcomp_m_net_prim_amt as number(21,4) ) as pcomp_m_net_prim_amt  ,
        cast(pcomp_m_net_prim_price as number(21,4) ) as pcomp_m_net_prim_price  ,
        cast(base_rpt_grs_kg_price as number(21,4) ) as base_rpt_grs_kg_price  ,
        cast(base_rpt_net_kg_price as number(21,4) ) as base_rpt_net_kg_price  ,
        cast(base_rpt_grs_ca_price as number(21,4) ) as base_rpt_grs_ca_price  ,
        cast(base_rpt_net_ca_price as number(21,4) ) as base_rpt_net_ca_price  ,
        cast(phi_rpt_grs_kg_price as number(21,4) ) as phi_rpt_grs_kg_price  ,
        cast(phi_rpt_net_kg_price as number(21,4) ) as phi_rpt_net_kg_price  ,
        cast(phi_rpt_grs_ca_price as number(21,4) ) as phi_rpt_grs_ca_price  ,
        cast(phi_rpt_net_ca_price as number(21,4) ) as phi_rpt_net_ca_price  ,
        cast(pcomp_rpt_grs_kg_price as number(21,4) ) as pcomp_rpt_grs_kg_price  ,
        cast(pcomp_rpt_net_kg_price as number(21,4) ) as pcomp_rpt_net_kg_price  ,
        cast(pcomp_rpt_grs_ca_price as number(21,4) ) as pcomp_rpt_grs_ca_price  ,
        cast(pcomp_rpt_net_ca_price as number(21,4) ) as pcomp_rpt_net_ca_price  ,
        cast(source_foreign_conv_rt as number(38,0) ) as source_foreign_conv_rt  ,
        cast(source_updated_d_id as number(38,0) ) as source_updated_d_id  ,
        cast(source_updated_time as timestamp_ntz(9) ) as source_updated_time  ,
        cast(substring(short_reason_code,1,5) as text(5) ) as short_reason_code  ,
        cast(substring(short_reason_desc,1,6) as text(6) ) as short_reason_desc  ,
        cast(bracket_price as number(38,0) ) as bracket_price  ,
        cast(substring(list_price_uom,1,6) as text(6) ) as list_price_uom  ,
        cast(load_date as date) as load_date  ,
        cast(update_date as date) as update_date  ,
        cast(substring(transaction_currency,1,6) as text(6) ) as transaction_currency  ,
        cast(trans_conv_rt as number(38,10) ) as trans_conv_rt  ,
        cast(trans_rpt_grs_amt as number(38,10) ) as trans_rpt_grs_amt  ,
        cast(trans_rpt_grs_price as number(38,10) ) as trans_rpt_grs_price  ,
        cast(trans_rpt_net_amt as number(38,10) ) as trans_rpt_net_amt  ,
        cast(trans_rpt_net_price as number(38,10) ) as trans_rpt_net_price  ,
        cast(substring(line_item_desc,1,50) as text(50) ) as line_item_desc  ,
        cast(open_prim_quantity as number(19,2) ) as open_prim_quantity  ,
        cast(open_cwt_quantity as number(19,2) ) as open_cwt_quantity  ,
        cast(open_tran_quantity as number(19,2) ) as open_tran_quantity  ,
        cast(open_ul_quantity as number(19,2) ) as open_ul_quantity  ,
        cast(open_kg_quantity as number(19,2) ) as open_kg_quantity  ,
        cast(mth_trans_conv_rt as number(29,7) ) as mth_trans_conv_rt  ,
        cast(trans_unit_tran_price as number(21,4) ) as trans_unit_tran_price  ,
        cast(trans_list_tran_price as number(21,4) ) as trans_list_tran_price  ,
        cast(trans_extend_tran_price as number(21,4) ) as trans_extend_tran_price  ,
        cast(tran_unit_tran_cost as number(21,4) ) as tran_unit_tran_cost  ,
        cast(trans_extend_tran_cost as number(21,4) ) as trans_extend_tran_cost  ,
        cast(trans_deduction_01_amt as number(38,10) ) as trans_deduction_01_amt  ,
        cast(trans_deduction_02_amt as number(38,10) ) as trans_deduction_02_amt  ,
        cast(trans_deduction_03_amt as number(38,10) ) as trans_deduction_03_amt  ,
        cast(sales_prim_quantity as number(19,2) ) as sales_prim_quantity  ,
        cast(sales_cwt_quantity as number(19,2) ) as sales_cwt_quantity  ,
        cast(sales_ca_quantity as number(19,2) ) as sales_ca_quantity  ,
        cast(sales_tran_quantity as number(19,2) ) as sales_tran_quantity  ,
        cast(sales_ul_quantity as number(19,2) ) as sales_ul_quantity  ,
        cast(sales_kg_quantity as number(19,2) ) as sales_kg_quantity  ,
        cast(line_actual_ship_date as timestamp_ntz(9) ) as line_actual_ship_date  ,
        cast(substring(edi_indicator,1,1) as text(1) ) as edi_indicator  ,
        cast(base_deduction_01_amt as number(38,10) ) as base_deduction_01_amt  ,
        cast(base_deduction_02_amt as number(38,10) ) as base_deduction_02_amt  ,
        cast(base_deduction_03_amt as number(38,10) ) as base_deduction_03_amt  ,
        cast(phi_deduction_01_amt as number(38,10) ) as phi_deduction_01_amt  ,
        cast(phi_deduction_02_amt as number(38,10) ) as phi_deduction_02_amt  ,
        cast(phi_deduction_03_amt as number(38,10) ) as phi_deduction_03_amt  ,
        cast(pcomp_deduction_01_amt as number(38,10) ) as pcomp_deduction_01_amt  ,
        cast(pcomp_deduction_02_amt as number(38,10) ) as pcomp_deduction_02_amt  ,
        cast(pcomp_deduction_03_amt as number(38,10) ) as pcomp_deduction_03_amt  ,
        cast(substring(cancel_reason_code,1,10) as text(10) ) as cancel_reason_code  ,
        cast(substring(cancel_reason_desc,1,60) as text(60) ) as cancel_reason_desc  ,
        cast(trans_quantity_confirmed as number(38,10) ) as trans_quantity_confirmed  ,
        cast(trans_salesprice_confirmed as number(38,10) ) as trans_salesprice_confirmed  ,
        cast(trans_lineamount_confirmed as number(38,10) ) as trans_lineamount_confirmed  ,
        cast(trans_confirmdate_confirmed as date) as trans_confirmdate_confirmed  ,
        cast(substring(trans_uom_confirmed,1,20) as text(20) ) as trans_uom_confirmed  ,
        cast(substring(trans_currency_confirmed,1,20) as text(20) ) as trans_currency_confirmed  ,
        cast(prim_quantity_confirmed as number(38,10) ) as prim_quantity_confirmed  ,
        cast(cwt_quantity_confirmed as number(38,10) ) as cwt_quantity_confirmed  ,
        cast(ul_quantity_confirmed as number(38,10) ) as ul_quantity_confirmed  ,
        cast(kg_quantity_confirmed as number(38,10) ) as kg_quantity_confirmed  ,
        cast(ca_quantity_confirmed as number(38,10) ) as ca_quantity_confirmed  ,
        cast(base_lineamount_confirmed as number(38,10) ) as base_lineamount_confirmed  ,
        cast(phi_lineamount_confirmed as number(38,10) ) as phi_lineamount_confirmed  ,
        cast(pcomp_lineamount_confirmed as number(38,10) ) as pcomp_lineamount_confirmed  ,
        cast(substring(source_account_identifier,1,255) as text(255) ) as source_account_identifier  ,
        cast(substring(source_object_id,1,255) as text(255) ) as source_object_id  ,
        cast(substring(cost_centre,1,255) as text(255) ) as cost_centre  ,
        cast(account_guid as text(255) ) as account_guid  ,
        cast(trans_invoice_grs_amt as number(38,10) ) as trans_invoice_grs_amt  ,
        cast(trans_invoice_net_amt as number(38,10) ) as trans_invoice_net_amt  ,
        cast(base_invoice_grs_amt as number(38,10) ) as base_invoice_grs_amt  ,
        cast(base_invoice_net_amt as number(38,10) ) as base_invoice_net_amt  ,
        cast(phi_invoice_grs_amt as number(38,10) ) as phi_invoice_grs_amt  ,
        cast(phi_invoice_net_amt as number(38,10) ) as phi_invoice_net_amt  ,
        cast(pcomp_invoice_grs_amt as number(38,10) ) as pcomp_invoice_grs_amt  ,
        cast(pcomp_invoice_net_amt as number(38,10) ) as pcomp_invoice_net_amt  ,
        cast(substring(variant_code,1,255) as text(255) ) as variant_code  ,
        cast(open_ca_quantity as number(19,2) ) as open_ca_quantity  ,
        cast(base_ext_ing_cost as number(38,10) ) as base_ext_ing_cost  ,
        cast(base_ext_pkg_cost as number(38,10) ) as base_ext_pkg_cost  ,
        cast(base_ext_lbr_cost as number(38,10) ) as base_ext_lbr_cost  ,
        cast(base_ext_boughtin_cost as number(38,10) ) as base_ext_boughtin_cost  ,
        cast(base_ext_oth_cost as number(38,10) ) as base_ext_oth_cost  ,
        cast(base_ext_copack_cost as number(38,10) ) as base_ext_copack_cost  ,
        --additional fields
        cast(trans_ext_ing_cost as number(38,10) ) as trans_ext_ing_cost  ,
        cast(trans_ext_pkg_cost as number(38,10) ) as trans_ext_pkg_cost  ,
        cast(trans_ext_lbr_cost as number(38,10) ) as trans_ext_lbr_cost  ,
        cast(trans_ext_boughtin_cost as number(38,10) ) as trans_ext_boughtin_cost  ,
        cast(trans_ext_oth_cost as number(38,10) ) as trans_ext_oth_cost  ,
        cast(trans_ext_copack_cost as number(38,10) ) as trans_ext_copack_cost  ,

        cast(phi_ext_ing_cost as number(38,10) ) as phi_ext_ing_cost  ,
        cast(phi_ext_pkg_cost as number(38,10) ) as phi_ext_pkg_cost  ,
        cast(phi_ext_lbr_cost as number(38,10) ) as phi_ext_lbr_cost  ,
        cast(phi_ext_boughtin_cost as number(38,10) ) as phi_ext_boughtin_cost  ,
        cast(phi_ext_oth_cost as number(38,10) ) as phi_ext_oth_cost  ,
        cast(phi_ext_copack_cost as number(38,10) ) as phi_ext_copack_cost  ,

        cast(pcomp_ext_ing_cost as number(38,10) ) as pcomp_ext_ing_cost  ,
        cast(pcomp_ext_pkg_cost as number(38,10) ) as pcomp_ext_pkg_cost  ,
        cast(pcomp_ext_lbr_cost as number(38,10) ) as pcomp_ext_lbr_cost  ,
        cast(pcomp_ext_boughtin_cost as number(38,10) ) as pcomp_ext_boughtin_cost  ,
        cast(pcomp_ext_oth_cost as number(38,10) ) as pcomp_ext_oth_cost  ,
        cast(pcomp_ext_copack_cost as number(38,10) ) as pcomp_ext_copack_cost  ,
        --ends here
        cast(trans_invoice_disc_amt as number(38,10) ) as trans_invoice_disc_amt  ,
        cast(base_invoice_disc_amt as number(38,10) ) as base_invoice_disc_amt  ,
        cast(phi_invoice_disc_amt as number(38,10) ) as phi_invoice_disc_amt  ,
        cast(pcomp_invoice_disc_amt as number(38,10) ) as pcomp_invoice_disc_amt  ,
        cast(substring(delivery_instruction,1,255) as text(255) ) as delivery_instruction  ,
        cast(substring(cust_order_number,1,30) as text(30) ) as cust_order_number  ,
        cast(item_shelf_life as number(38,0) ) as item_shelf_life  ,
        cast(substring(picking_route,1,10) as text(10) ) as picking_route  ,
        cast(trans_line_requested_date as date) as trans_line_requested_date  ,
        cast(unique_key as text(255) ) as unique_key ,
        cast(source_legacy as text(15)) as source_legacy
    from currency_conv
)
select * from final qualify row_number() over (partition by unique_key order by unique_key desc)=1