{{
    config(
        materialized = env_var('DBT_MAT_INCREMENTAL'),
        transient = false,
        unique_key = 'UNIQUE_KEY',
        on_schema_change='sync_all_columns',
        tags="rdm_core"
    )
}}

/*union logic with history has been shifted to immidiate upstream model as it was required for address model in enterprise*/

with Final as (
    select * from {{ ref('int_d_wbx_supplier') }}
),

Cast_Final as (
    select
        CAST (SUPPLIER_ADDRESS_NUMBER_GUID_OLD AS NUMBER (38,0)) AS SUPPLIER_ADDRESS_NUMBER_GUID_OLD,
        CAST (SUBSTRING (SUPPLIER_ADDRESS_NUMBER_GUID,1,255) AS VARCHAR2 (255)) AS SUPPLIER_ADDRESS_NUMBER_GUID,
        CAST (SUBSTRING (SOURCE_SYSTEM_ADDRESS_NUMBER,1,255) AS VARCHAR2 (255)) AS SOURCE_SYSTEM_ADDRESS_NUMBER,
        CAST(GENERIC_ADDRESS_TYPE AS VARCHAR(255))                              AS GENERIC_ADDRESS_TYPE,
        CAST (SUBSTRING (PAYMENT_INSTRUMENT_CODE     ,1,255) AS VARCHAR2 (255)) AS PAYMENT_INSTRUMENT_CODE,
        CAST (SUBSTRING (PAYMENT_INSTRUMENT_NAME     ,1,255) AS VARCHAR2 (255)) AS PAYMENT_INSTRUMENT_NAME,
        CAST (SUBSTRING (UNIFIED_SUPPLIER_NAME       ,1,255) AS VARCHAR2 (255)) AS UNIFIED_SUPPLIER_NAME,
        CAST (SUBSTRING (SOURCE_SUPPLIER_TYPE        ,1,255) AS VARCHAR2 (255)) AS SOURCE_SUPPLIER_TYPE,
        CAST (SUBSTRING (PHI_SUPPLIER_SUBTYPE        ,1,255) AS VARCHAR2 (255)) AS PHI_SUPPLIER_SUBTYPE,
        CAST (SUBSTRING (PAYMENT_TERMS_CODE          ,1,255) AS VARCHAR2 (255)) AS PAYMENT_TERMS_CODE,
        CAST (SUBSTRING (PAYMENT_TERMS_DESCRIPTION   ,1,255) AS VARCHAR2 (255)) AS PAYMENT_TERMS_DESCRIPTION,
        CAST (SUBSTRING (PHI_SUPPLIER_TYPE           ,1,255) AS VARCHAR2 (255)) AS PHI_SUPPLIER_TYPE,
        CAST (SUBSTRING (TRANSPORT_MODE              ,1,255) AS VARCHAR2 (255)) AS TRANSPORT_MODE,
        CAST (SUBSTRING (CURRENCY_CODE               ,1,255) AS VARCHAR2 (255)) AS CURRENCY_CODE,
        CAST (SUBSTRING (SHIPPING_TERMS              ,1,255) AS VARCHAR2 (255)) AS SHIPPING_TERMS,
        CAST (SUBSTRING (SOURCE_SYSTEM               ,1,255) AS VARCHAR2 (255)) AS SOURCE_SYSTEM,
        CAST (SUBSTRING (SUPPLIER_NAME               ,1,255) AS VARCHAR2 (255)) AS SUPPLIER_NAME,
        CAST (SUBSTRING (DATE_INSERTED               ,1,255) AS VARCHAR2 (255)) AS DATE_INSERTED,
        CAST (SUBSTRING (DATE_UPDATED               ,1,255) AS VARCHAR2 (255))  AS DATE_UPDATED,
        CAST (VOUCHER_DATE                          AS TIMESTAMP_NTZ(9))        AS VOUCHER_DATE,
        CAST (SUBSTRING (UNIQUE_KEY                  ,1,255) AS VARCHAR2 (255)) AS UNIQUE_KEY,
        CAST (SUBSTRING (COMPANY_CODE               ,1,255) AS VARCHAR2 (255)) AS COMPANY_CODE,
        CAST (SUBSTRING (COMPANY_ADDRESS_GUID               ,1,255) AS VARCHAR2 (255)) AS COMPANY_ADDRESS_GUID
    from Final
)

select * from Cast_Final