{{
    config(
    materialized = env_var('DBT_MAT_TABLE'),
    tags=["ax_hist_fact","ax_hist_sales_order"]
    )
}}

with old_fct as (
    select *
    from {{ source('WBX_PROD_FACT','fct_wbx_sls_order') }}
    where {{ env_var("DBT_PICK_FROM_CONV") }} = 'Y'
),

old_plant as (
    select
        source_business_unit_code_new,
        source_business_unit_code,
        plantdc_address_guid_new,
        plantdc_address_guid
    from {{ ref('conv_dim_wbx_plant_dc') }}
),

old_account as (
    select distinct
        source_object_id,
        source_object_id_old,
        source_account_identifier,
        source_company_code
    from {{ ref('conv_dim_wbx_account') }}
),

old_payment as (
    select
        source_payment_terms_code_new,
        source_payment_terms_code_old,
        payment_terms_guid,
        payment_terms_guid_old
    from {{ ref('conv_xref_wbx_payment_terms') }}
),

converted_fct as (
    select
        source_system,
        sales_line_number,
        sales_order_number,
        source_sales_order_type,
        sales_order_type,
        sales_order_company,
        source_employee_code,
        employee_guid,
        source_line_type_code,
        line_type_code,
        line_type_desc,
        line_status_code,
        line_status_desc,
        ship_source_customer_code,
        {{ dbt_utils.surrogate_key(['source_system','ship_source_customer_code',"'CUSTOMER_MAIN'","sales_order_company"]) }} AS ship_customer_address_guid,
        bill_source_customer_code,
        {{ dbt_utils.surrogate_key(['source_system','ship_source_customer_code',"'CUSTOMER_MAIN'","sales_order_company"]) }} AS bill_customer_address_guid,
        a.source_business_unit_code as ship_source_business_unit_code_old,
        plnt.source_business_unit_code_new as ship_source_business_unit_code,
        ship_business_unit_guid,
        default_company_code,
        source_item_identifier,
        item_guid,
        division,
        org_unit_code,
        invoice_document_company,
        invoice_document_number,
        invoice_document_type,
        source_location_code,
        location_guid, -----Hardcoded to all null in Sales order int map so no conversion applied
        source_lot_code,
        lot_guid,-------Hardcoded to all null in Sales order int map so no conversion applied
        lot_status_code,
        line_ordered_date,
        line_sch_pick_up_date,
        line_prom_ship_date,
        line_cancelled_date,
        line_invoice_date,
        line_requested_date,
        line_original_promised_date,
        line_promised_delivery_date,
        line_gl_date,
        required_delivery_date,
        lead_time,
        gl_offset_code,
        early_flag,
        late_flag,
        a.source_business_unit_code as source_business_unit_code_old,
        plnt.source_business_unit_code_new as source_business_unit_code,
        a.business_unit_address_guid as business_unit_address_guid_old,
        plnt.plantdc_address_guid_new as business_unit_address_guid,
        original_document_company,
        original_document_number,
        original_document_type,
        original_line_number,
        transfer_po_order_company,
        transfer_po_order_number,
        transfer_po_order_type,
        transfer_po_line_number,
        customer_po_number,
        vendor_ref_code,
        kit_source_item_identifier,
        kit_item_guid,
        kit_line_number,
        kit_component_number,
        component_line_no,
        base_open_amt,
        price_override_flag,
        cost_override_flag,
        a.source_payment_terms_code as source_payment_terms_code_old,
        pymt.source_payment_terms_code_new as source_payment_terms_code,
        a.payment_terms_guid as payment_terms_guid_old,
        pymt.payment_terms_guid as payment_terms_guid,
        source_payment_instr_code,
        target_payment_instr_code,
        payment_instr_desc,
        price_adj_schd_code,
        item_price_grp_code,
        pick_slip_no,
        source_freight_handling_code,
        source_freight_handling_desc,
        serial_no,
        basket_price_code,
        transaction_quantity_uom,
        primary_uom,
        transaction_price_uom,
        unit_weight,
        weight_uom,
        unit_volume,
        volume_uom,
        gross_weight,
        gross_weight_uom,
        net_weight,
        net_kg_weight,
        gross_kg_weight,
        short_prim_quantity,
        ordered_prim_quantity,
        shipped_prim_quantity,
        backorder_prim_quantity,
        cancelled_prim_quantity,
        ordered_cwt_quantity,
        shipped_cwt_quantity,
        backord_cwt_quantity,
        cancel_cwt_quantity,
        short_cwt_quantity,
        ordered_ca_quantity,
        shipped_ca_quantity,
        backord_ca_quantity,
        cancel_ca_quantity,
        short_ca_quantity,
        ordered_tran_quantity,
        shipped_tran_quantity,
        cancel_tran_quantity,
        short_tran_quantity,
        backord_tran_quantity,
        ordered_ul_quantity,
        shipped_ul_quantity,
        short_ul_quantity,
        backord_ul_quantity,
        cancel_ul_quantity,
        ordered_kg_quantity,
        shipped_kg_quantity,
        cancel_kg_quantity,
        backord_kg_quantity,
        short_kg_quantity,
        base_currency,
        phi_currency,
        phi_conv_rt,
        mth_phi_conv_rt,
        division_currency,
        pcomp_currency,
        pcomp_conv_rt,
        mth_pcomp_conv_rt,
        base_unit_prim_price,
        base_list_prim_price,
        base_extend_tran_price,
        base_unit_prim_cost,
        base_extend_tran_cost,
        base_rpt_grs_prim_price,
        base_rpt_grs_prim_amt,
        base_rpt_net_prim_price,
        base_rpt_net_prim_amt,
        phi_rpt_grs_prim_amt,
        phi_rpt_grs_prim_price,
        phi_rpt_net_prim_amt,
        phi_rpt_net_prim_price,
        pcomp_rpt_grs_prim_amt,
        pcomp_rpt_grs_prim_price,
        pcomp_rpt_net_prim_amt,
        pcomp_rpt_net_prim_price,
        phi_m_grs_prim_amt,
        phi_m_grs_prim_price,
        phi_m_net_prim_amt,
        phi_m_net_prim_price,
        pcomp_m_grs_prim_amt,
        pcomp_m_grs_prim_price,
        pcomp_m_net_prim_amt,
        pcomp_m_net_prim_price,
        base_rpt_grs_kg_price,
        base_rpt_net_kg_price,
        base_rpt_grs_ca_price,
        base_rpt_net_ca_price,
        phi_rpt_grs_kg_price,
        phi_rpt_net_kg_price,
        phi_rpt_grs_ca_price,
        phi_rpt_net_ca_price,
        pcomp_rpt_grs_kg_price,
        pcomp_rpt_net_kg_price,
        pcomp_rpt_grs_ca_price,
        pcomp_rpt_net_ca_price,
        source_foreign_conv_rt,
        source_updated_d_id,
        source_updated_time,
        short_reason_code,
        short_reason_desc,
        bracket_price,
        list_price_uom,
        load_date,
        update_date,
        transaction_currency,
        trans_conv_rt,
        trans_rpt_grs_amt,
        trans_rpt_grs_price,
        trans_rpt_net_amt,
        trans_rpt_net_price,
        line_item_desc,
        open_prim_quantity,
        open_cwt_quantity,
        open_tran_quantity,
        open_ul_quantity,
        open_kg_quantity,
        mth_trans_conv_rt,
        trans_unit_tran_price,
        trans_list_tran_price,
        trans_extend_tran_price,
        tran_unit_tran_cost,
        trans_extend_tran_cost,
        trans_deduction_01_amt,
        trans_deduction_02_amt,
        trans_deduction_03_amt,
        sales_prim_quantity,
        sales_cwt_quantity,
        sales_ca_quantity,
        sales_tran_quantity,
        sales_ul_quantity,
        sales_kg_quantity,
        line_actual_ship_date,
        edi_indicator,
        base_deduction_01_amt,
        base_deduction_02_amt,
        base_deduction_03_amt,
        phi_deduction_01_amt,
        phi_deduction_02_amt,
        phi_deduction_03_amt,
        pcomp_deduction_01_amt,
        pcomp_deduction_02_amt,
        pcomp_deduction_03_amt,
        cancel_reason_code,
        cancel_reason_desc,
        trans_quantity_confirmed,
        trans_salesprice_confirmed,
        trans_lineamount_confirmed,
        trans_confirmdate_confirmed,
        trans_uom_confirmed,
        trans_currency_confirmed,
        prim_quantity_confirmed,
        cwt_quantity_confirmed,
        ul_quantity_confirmed,
        kg_quantity_confirmed,
        ca_quantity_confirmed,
        base_lineamount_confirmed,
        phi_lineamount_confirmed,
        pcomp_lineamount_confirmed,
        a.source_account_identifier,--Hardcoded to all null in Sales order int map so no conversion applied
        a.source_object_id as source_object_id_old,
        acnt.source_object_id as source_object_id,
        cost_centre,
        account_guid,--Hardcoded to all null in Sales order int map so no conversion applied
        trans_invoice_grs_amt,
        trans_invoice_net_amt,
        base_invoice_grs_amt,
        base_invoice_net_amt,
        phi_invoice_grs_amt,
        phi_invoice_net_amt,
        pcomp_invoice_grs_amt,
        pcomp_invoice_net_amt,
        variant_code,
        open_ca_quantity,
        base_ext_ing_cost,
        base_ext_pkg_cost,
        base_ext_lbr_cost,
        base_ext_boughtin_cost,
        base_ext_oth_cost,
        base_ext_copack_cost,
        trans_invoice_disc_amt,
        base_invoice_disc_amt,
        phi_invoice_disc_amt,
        pcomp_invoice_disc_amt,
        delivery_instruction,
        cust_order_number,
        item_shelf_life,
        picking_route,
        trans_line_requested_date,
        unique_key,
        'AX' as source_legacy
    from old_fct as a
    left join
        old_plant as plnt
        on a.business_unit_address_guid = plnt.plantdc_address_guid
    left join old_account acnt on a.source_object_id=acnt.source_object_id_old and a.sales_order_company=acnt.source_company_code
    left join
        old_payment as pymt
        on a.payment_terms_guid = pymt.payment_terms_guid_old

)

select 
        cast(substring(source_system,1,255) as text(255) ) as source_system  ,
        cast(substring(sales_line_number,1,255) as text(255) ) as sales_line_number  ,
        cast(substring(sales_order_number,1,255) as text(255) ) as sales_order_number  ,
        cast(substring(source_sales_order_type,1,30) as text(30) ) as source_sales_order_type  ,
        cast(substring(sales_order_type,1,30) as text(30) ) as sales_order_type  ,
        cast(substring(sales_order_company,1,20) as text(20) ) as sales_order_company  ,
        cast(substring(source_employee_code,1,255) as text(255) ) as source_employee_code  ,
        cast(employee_guid as text(255) ) as employee_guid  ,
        cast(substring(source_line_type_code,1,255) as text(255) ) as source_line_type_code  ,
        cast(substring(line_type_code,1,255) as text(255) ) as line_type_code  ,
        cast(substring(line_type_desc,1,255) as text(255) ) as line_type_desc  ,
        cast(line_status_code as number(38,0) ) as line_status_code  ,
        cast(substring(line_status_desc,1,255) as text(255) ) as line_status_desc  ,
        cast(substring(ship_source_customer_code,1,255) as text(255) ) as ship_source_customer_code  ,
        cast(ship_customer_address_guid as text(255) ) as ship_customer_address_guid  ,
        cast(substring(bill_source_customer_code,1,255) as text(255) ) as bill_source_customer_code  ,
        cast(bill_customer_address_guid as text(255) ) as bill_customer_address_guid  ,
		cast(substring(ship_source_business_unit_code_old,1,255) as text(255) ) as ship_source_business_unit_code_old,
        cast(substring(ship_source_business_unit_code,1,255) as text(255) ) as ship_source_business_unit_code  ,
        cast(ship_business_unit_guid as text(255) ) as ship_business_unit_guid  ,
        cast(substring(default_company_code,1,255) as text(255) ) as default_company_code  ,
        cast(substring(source_item_identifier,1,255) as text(255) ) as source_item_identifier  ,
        cast(item_guid as text(255) ) as item_guid  ,
        cast(substring(division,1,255) as text(255) ) as division  ,
        cast(substring(org_unit_code,1,255) as text(255) ) as org_unit_code  ,
        cast(substring(invoice_document_company,1,255) as text(255) ) as invoice_document_company  ,
        cast(substring(invoice_document_number,1,255) as text(255) ) as invoice_document_number  ,
        cast(substring(invoice_document_type,1,255) as text(255) ) as invoice_document_type  ,
        cast(substring(source_location_code,1,255) as text(255) ) as source_location_code  ,
        cast(location_guid as text(255) ) as location_guid  ,
        cast(substring(source_lot_code,1,255) as text(255) ) as source_lot_code  ,
        cast(lot_guid as text(255) ) as lot_guid  ,
        cast(substring(lot_status_code,1,255) as text(255) ) as lot_status_code  ,
        cast(line_ordered_date as timestamp_ntz(9) ) as line_ordered_date  ,
        cast(line_sch_pick_up_date as timestamp_ntz(9) ) as line_sch_pick_up_date  ,
        cast(line_prom_ship_date as timestamp_ntz(9) ) as line_prom_ship_date  ,
        cast(line_cancelled_date as timestamp_ntz(9) ) as line_cancelled_date  ,
        cast(line_invoice_date as timestamp_ntz(9) ) as line_invoice_date  ,
        cast(line_requested_date as timestamp_ntz(9) ) as line_requested_date  ,
	    cast(line_original_promised_date as timestamp_ntz(9) ) as line_original_promised_date  ,
        cast(line_promised_delivery_date as timestamp_ntz(9) ) as line_promised_delivery_date  ,
        cast(line_gl_date as timestamp_ntz(9) ) as line_gl_date  ,
        cast(required_delivery_date as timestamp_ntz(9) ) as required_delivery_date  ,
        cast(lead_time as number(38,0) ) as lead_time  ,
        cast(substring(gl_offset_code,1,255) as text(255) ) as gl_offset_code  ,
        cast(substring(early_flag,1,255) as text(255) ) as early_flag  ,
        cast(substring(late_flag,1,255) as text(255) ) as late_flag  ,
		cast(substring(source_business_unit_code_old,1,255) as text(255) ) as source_business_unit_code_old  ,															 
        cast(substring(source_business_unit_code,1,255) as text(255) ) as source_business_unit_code  ,
		cast(business_unit_address_guid_old as text(255) ) as business_unit_address_guid_old  ,
        cast(business_unit_address_guid as text(255) ) as business_unit_address_guid  ,
        cast(substring(original_document_company,1,255) as text(255) ) as original_document_company  ,
        cast(substring(original_document_number,1,255) as text(255) ) as original_document_number  ,
        cast(substring(original_document_type,1,255) as text(255) ) as original_document_type  ,
        cast(substring(original_line_number,1,255) as text(255) ) as original_line_number  ,
        cast(substring(transfer_po_order_company,1,255) as text(255) ) as transfer_po_order_company  ,
        cast(substring(transfer_po_order_number,1,255) as text(255) ) as transfer_po_order_number  ,
        cast(substring(transfer_po_order_type,1,255) as text(255) ) as transfer_po_order_type  ,
        cast(substring(transfer_po_line_number,1,255) as text(255) ) as transfer_po_line_number  ,
        cast(substring(customer_po_number,1,255) as text(255) ) as customer_po_number  ,
        cast(substring(vendor_ref_code,1,255) as text(255) ) as vendor_ref_code  ,
        cast(substring(kit_source_item_identifier,1,255) as text(255) ) as kit_source_item_identifier  ,
        cast(kit_item_guid as text(255) ) as kit_item_guid  ,
        cast(substring(kit_line_number,1,255) as text(255) ) as kit_line_number  ,
        cast(substring(kit_component_number,1,255) as text(255) ) as kit_component_number  ,
        cast(substring(component_line_no,1,255) as text(255) ) as component_line_no  ,
        cast(base_open_amt as number(38,0) ) as base_open_amt  ,
        cast(substring(price_override_flag,1,4) as text(4) ) as price_override_flag  ,
        cast(substring(cost_override_flag,1,4) as text(4) ) as cost_override_flag  ,
		cast(substring(source_payment_terms_code_old,1,255) as text(255) ) as source_payment_terms_code_old,		   
		cast(substring(source_payment_terms_code,1,255) as text(255) ) as source_payment_terms_code  ,
		cast(payment_terms_guid_old as text(255) ) as payment_terms_guid_old,
        cast(payment_terms_guid as text(255) ) as payment_terms_guid  ,
        cast(substring(source_payment_instr_code,1,60) as text(60) ) as source_payment_instr_code  ,
        cast(substring(target_payment_instr_code,1,60) as text(60) ) as target_payment_instr_code  ,
        cast(substring(payment_instr_desc,1,255) as text(255) ) as payment_instr_desc  ,
        cast(substring(price_adj_schd_code,1,8) as text(8) ) as price_adj_schd_code  ,
        cast(substring(item_price_grp_code,1,30) as text(30) ) as item_price_grp_code  ,
        cast(substring(pick_slip_no,1,30) as text(30) ) as pick_slip_no  ,
        cast(substring(source_freight_handling_code,1,20) as text(20) ) as source_freight_handling_code  ,
        cast(substring(source_freight_handling_desc,1,255) as text(255) ) as source_freight_handling_desc  ,
        cast(substring(serial_no,1,30) as text(30) ) as serial_no  ,
        cast(substring(basket_price_code,1,30) as text(30) ) as basket_price_code  ,
        cast(substring(transaction_quantity_uom,1,15) as text(15) ) as transaction_quantity_uom  ,
        cast(substring(primary_uom,1,255) as text(255) ) as primary_uom  ,
        cast(substring(transaction_price_uom,1,255) as text(255) ) as transaction_price_uom  ,
        cast(unit_weight as number(38,0) ) as unit_weight  ,
        cast(substring(weight_uom,1,255) as text(255) ) as weight_uom  ,
        cast(unit_volume as number(38,0) ) as unit_volume  ,
        cast(substring(volume_uom,1,16) as text(16) ) as volume_uom  ,
        cast(gross_weight as number(38,10) ) as gross_weight  ,
        cast(substring(gross_weight_uom,1,15) as text(15) ) as gross_weight_uom  ,
        cast(net_weight as number(38,10) ) as net_weight  ,
        cast(net_kg_weight as number(38,10) ) as net_kg_weight  ,
        cast(gross_kg_weight as number(38,10) ) as gross_kg_weight  ,
        cast(short_prim_quantity as number(19,2) ) as short_prim_quantity  ,
		cast(ordered_prim_quantity as number(19,2) ) as ordered_prim_quantity  ,
        cast(shipped_prim_quantity as number(19,2) ) as shipped_prim_quantity  ,
        cast(backorder_prim_quantity as number(19,2) ) as backorder_prim_quantity  ,
        cast(cancelled_prim_quantity as number(19,2) ) as cancelled_prim_quantity  ,
        cast(ordered_cwt_quantity as number(19,2) ) as ordered_cwt_quantity  ,
        cast(shipped_cwt_quantity as number(19,2) ) as shipped_cwt_quantity  ,
        cast(backord_cwt_quantity as number(19,2) ) as backord_cwt_quantity  ,
        cast(cancel_cwt_quantity as number(19,2) ) as cancel_cwt_quantity  ,
        cast(short_cwt_quantity as number(19,2) ) as short_cwt_quantity  ,
        cast(ordered_ca_quantity as number(19,2) ) as ordered_ca_quantity  ,
        cast(shipped_ca_quantity as number(19,2) ) as shipped_ca_quantity  ,
        cast(backord_ca_quantity as number(19,2) ) as backord_ca_quantity  ,
        cast(cancel_ca_quantity as number(19,2) ) as cancel_ca_quantity  ,
        cast(short_ca_quantity as number(19,2) ) as short_ca_quantity  ,
        cast(ordered_tran_quantity as number(19,2) ) as ordered_tran_quantity  ,
        cast(shipped_tran_quantity as number(19,2) ) as shipped_tran_quantity  ,
        cast(cancel_tran_quantity as number(19,2) ) as cancel_tran_quantity  ,
        cast(short_tran_quantity as number(19,2) ) as short_tran_quantity  ,
        cast(backord_tran_quantity as number(19,2) ) as backord_tran_quantity  ,
        cast(ordered_ul_quantity as number(19,2) ) as ordered_ul_quantity  ,
        cast(shipped_ul_quantity as number(19,2) ) as shipped_ul_quantity  ,
        cast(short_ul_quantity as number(19,2) ) as short_ul_quantity  ,
        cast(backord_ul_quantity as number(19,2) ) as backord_ul_quantity  ,
        cast(cancel_ul_quantity as number(19,2) ) as cancel_ul_quantity  ,
        cast(ordered_kg_quantity as number(19,2) ) as ordered_kg_quantity  ,
        cast(shipped_kg_quantity as number(19,2) ) as shipped_kg_quantity  ,
        cast(cancel_kg_quantity as number(19,2) ) as cancel_kg_quantity  ,
        cast(backord_kg_quantity as number(19,2) ) as backord_kg_quantity  ,
        cast(short_kg_quantity as number(19,2) ) as short_kg_quantity  ,
        cast(substring(base_currency,1,6) as text(6) ) as base_currency  ,
        cast(substring(phi_currency,1,6) as text(6) ) as phi_currency  ,
        cast(phi_conv_rt as number(29,7) ) as phi_conv_rt  ,
        cast(mth_phi_conv_rt as number(29,7) ) as mth_phi_conv_rt  ,
        cast(substring(division_currency,1,6) as text(6) ) as division_currency  ,
        cast(substring(pcomp_currency,1,6) as text(6) ) as pcomp_currency  ,
        cast(pcomp_conv_rt as number(29,7) ) as pcomp_conv_rt  ,
        cast(mth_pcomp_conv_rt as number(29,7) ) as mth_pcomp_conv_rt  ,
        cast(base_unit_prim_price as number(21,4) ) as base_unit_prim_price  ,
        cast(base_list_prim_price as number(21,4) ) as base_list_prim_price  ,
        cast(base_extend_tran_price as number(21,4) ) as base_extend_tran_price  ,
        cast(base_unit_prim_cost as number(21,4) ) as base_unit_prim_cost  ,
        cast(base_extend_tran_cost as number(21,4) ) as base_extend_tran_cost  ,
        cast(base_rpt_grs_prim_price as number(21,4) ) as base_rpt_grs_prim_price  ,
        cast(base_rpt_grs_prim_amt as number(21,4) ) as base_rpt_grs_prim_amt  ,
        cast(base_rpt_net_prim_price as number(21,4) ) as base_rpt_net_prim_price  ,
        cast(base_rpt_net_prim_amt as number(21,4) ) as base_rpt_net_prim_amt  ,
        cast(phi_rpt_grs_prim_amt as number(21,4) ) as phi_rpt_grs_prim_amt  ,
        cast(phi_rpt_grs_prim_price as number(21,4) ) as phi_rpt_grs_prim_price  ,
        cast(phi_rpt_net_prim_amt as number(21,4) ) as phi_rpt_net_prim_amt  ,
        cast(phi_rpt_net_prim_price as number(21,4) ) as phi_rpt_net_prim_price  ,
        cast(pcomp_rpt_grs_prim_amt as number(21,4) ) as pcomp_rpt_grs_prim_amt  ,
        cast(pcomp_rpt_grs_prim_price as number(21,4) ) as pcomp_rpt_grs_prim_price  ,
        cast(pcomp_rpt_net_prim_amt as number(21,4) ) as pcomp_rpt_net_prim_amt  ,
        cast(pcomp_rpt_net_prim_price as number(21,4) ) as pcomp_rpt_net_prim_price  ,
        cast(phi_m_grs_prim_amt as number(21,4) ) as phi_m_grs_prim_amt  ,
        cast(phi_m_grs_prim_price as number(21,4) ) as phi_m_grs_prim_price  ,
        cast(phi_m_net_prim_amt as number(21,4) ) as phi_m_net_prim_amt  ,
        cast(phi_m_net_prim_price as number(21,4) ) as phi_m_net_prim_price  ,
        cast(pcomp_m_grs_prim_amt as number(21,4) ) as pcomp_m_grs_prim_amt  ,
        cast(pcomp_m_grs_prim_price as number(21,4) ) as pcomp_m_grs_prim_price  ,
        cast(pcomp_m_net_prim_amt as number(21,4) ) as pcomp_m_net_prim_amt  ,
        cast(pcomp_m_net_prim_price as number(21,4) ) as pcomp_m_net_prim_price  ,
        cast(base_rpt_grs_kg_price as number(21,4) ) as base_rpt_grs_kg_price  ,
        cast(base_rpt_net_kg_price as number(21,4) ) as base_rpt_net_kg_price  ,
        cast(base_rpt_grs_ca_price as number(21,4) ) as base_rpt_grs_ca_price  ,
        cast(base_rpt_net_ca_price as number(21,4) ) as base_rpt_net_ca_price  ,
        cast(phi_rpt_grs_kg_price as number(21,4) ) as phi_rpt_grs_kg_price  ,
        cast(phi_rpt_net_kg_price as number(21,4) ) as phi_rpt_net_kg_price  ,
        cast(phi_rpt_grs_ca_price as number(21,4) ) as phi_rpt_grs_ca_price  ,
        cast(phi_rpt_net_ca_price as number(21,4) ) as phi_rpt_net_ca_price  ,
        cast(pcomp_rpt_grs_kg_price as number(21,4) ) as pcomp_rpt_grs_kg_price  ,
        cast(pcomp_rpt_net_kg_price as number(21,4) ) as pcomp_rpt_net_kg_price  ,
        cast(pcomp_rpt_grs_ca_price as number(21,4) ) as pcomp_rpt_grs_ca_price  ,
        cast(pcomp_rpt_net_ca_price as number(21,4) ) as pcomp_rpt_net_ca_price  ,
        cast(source_foreign_conv_rt as number(38,0) ) as source_foreign_conv_rt  ,
        cast(source_updated_d_id as number(38,0) ) as source_updated_d_id  ,
        cast(source_updated_time as timestamp_ntz(9) ) as source_updated_time  ,
        cast(substring(short_reason_code,1,5) as text(5) ) as short_reason_code  ,
        cast(substring(short_reason_desc,1,6) as text(6) ) as short_reason_desc  ,
        cast(bracket_price as number(38,0) ) as bracket_price  ,
        cast(substring(list_price_uom,1,6) as text(6) ) as list_price_uom  ,
        cast(load_date as date) as load_date  ,
        cast(update_date as date) as update_date  ,
        cast(substring(transaction_currency,1,6) as text(6) ) as transaction_currency  ,
        cast(trans_conv_rt as number(38,10) ) as trans_conv_rt  ,
        cast(trans_rpt_grs_amt as number(38,10) ) as trans_rpt_grs_amt  ,
        cast(trans_rpt_grs_price as number(38,10) ) as trans_rpt_grs_price  ,
        cast(trans_rpt_net_amt as number(38,10) ) as trans_rpt_net_amt  ,
        cast(trans_rpt_net_price as number(38,10) ) as trans_rpt_net_price  ,
        cast(substring(line_item_desc,1,50) as text(50) ) as line_item_desc  ,
        cast(open_prim_quantity as number(19,2) ) as open_prim_quantity  ,
        cast(open_cwt_quantity as number(19,2) ) as open_cwt_quantity  ,
        cast(open_tran_quantity as number(19,2) ) as open_tran_quantity  ,
        cast(open_ul_quantity as number(19,2) ) as open_ul_quantity  ,
        cast(open_kg_quantity as number(19,2) ) as open_kg_quantity  ,
        cast(mth_trans_conv_rt as number(29,7) ) as mth_trans_conv_rt  ,
        cast(trans_unit_tran_price as number(21,4) ) as trans_unit_tran_price  ,
        cast(trans_list_tran_price as number(21,4) ) as trans_list_tran_price  ,
        cast(trans_extend_tran_price as number(21,4) ) as trans_extend_tran_price  ,
        cast(tran_unit_tran_cost as number(21,4) ) as tran_unit_tran_cost  ,
        cast(trans_extend_tran_cost as number(21,4) ) as trans_extend_tran_cost  ,
        cast(trans_deduction_01_amt as number(38,10) ) as trans_deduction_01_amt  ,
        cast(trans_deduction_02_amt as number(38,10) ) as trans_deduction_02_amt  ,
        cast(trans_deduction_03_amt as number(38,10) ) as trans_deduction_03_amt  ,
        cast(sales_prim_quantity as number(19,2) ) as sales_prim_quantity  ,
        cast(sales_cwt_quantity as number(19,2) ) as sales_cwt_quantity  ,
        cast(sales_ca_quantity as number(19,2) ) as sales_ca_quantity  ,
        cast(sales_tran_quantity as number(19,2) ) as sales_tran_quantity  ,
        cast(sales_ul_quantity as number(19,2) ) as sales_ul_quantity  ,
        cast(sales_kg_quantity as number(19,2) ) as sales_kg_quantity  ,
        cast(line_actual_ship_date as timestamp_ntz(9) ) as line_actual_ship_date  ,
        cast(substring(edi_indicator,1,1) as text(1) ) as edi_indicator  ,
        cast(base_deduction_01_amt as number(38,10) ) as base_deduction_01_amt  ,
        cast(base_deduction_02_amt as number(38,10) ) as base_deduction_02_amt  ,
        cast(base_deduction_03_amt as number(38,10) ) as base_deduction_03_amt  ,
        cast(phi_deduction_01_amt as number(38,10) ) as phi_deduction_01_amt  ,
        cast(phi_deduction_02_amt as number(38,10) ) as phi_deduction_02_amt  ,
        cast(phi_deduction_03_amt as number(38,10) ) as phi_deduction_03_amt  ,
        cast(pcomp_deduction_01_amt as number(38,10) ) as pcomp_deduction_01_amt  ,
        cast(pcomp_deduction_02_amt as number(38,10) ) as pcomp_deduction_02_amt  ,
        cast(pcomp_deduction_03_amt as number(38,10) ) as pcomp_deduction_03_amt  ,
        cast(substring(cancel_reason_code,1,10) as text(10) ) as cancel_reason_code  ,
        cast(substring(cancel_reason_desc,1,60) as text(60) ) as cancel_reason_desc  ,
        cast(trans_quantity_confirmed as number(38,10) ) as trans_quantity_confirmed  ,
        cast(trans_salesprice_confirmed as number(38,10) ) as trans_salesprice_confirmed  ,
        cast(trans_lineamount_confirmed as number(38,10) ) as trans_lineamount_confirmed  ,
        cast(trans_confirmdate_confirmed as date) as trans_confirmdate_confirmed  ,
        cast(substring(trans_uom_confirmed,1,20) as text(20) ) as trans_uom_confirmed  ,
        cast(substring(trans_currency_confirmed,1,20) as text(20) ) as trans_currency_confirmed  ,
        cast(prim_quantity_confirmed as number(38,10) ) as prim_quantity_confirmed  ,
        cast(cwt_quantity_confirmed as number(38,10) ) as cwt_quantity_confirmed  ,
        cast(ul_quantity_confirmed as number(38,10) ) as ul_quantity_confirmed  ,
        cast(kg_quantity_confirmed as number(38,10) ) as kg_quantity_confirmed  ,
        cast(ca_quantity_confirmed as number(38,10) ) as ca_quantity_confirmed  ,
        cast(base_lineamount_confirmed as number(38,10) ) as base_lineamount_confirmed  ,
        cast(phi_lineamount_confirmed as number(38,10) ) as phi_lineamount_confirmed  ,
        cast(pcomp_lineamount_confirmed as number(38,10) ) as pcomp_lineamount_confirmed  ,
        cast(substring(source_account_identifier,1,255) as text(255) ) as source_account_identifier  ,
		cast(substring(source_object_id_old,1,255) as text(255) ) as source_object_id_old,										   
        cast(substring(source_object_id,1,255) as text(255) ) as source_object_id  ,
        cast(substring(cost_centre,1,255) as text(255) ) as cost_centre  ,
        cast(account_guid as text(255) ) as account_guid  ,
        cast(trans_invoice_grs_amt as number(38,10) ) as trans_invoice_grs_amt  ,
        cast(trans_invoice_net_amt as number(38,10) ) as trans_invoice_net_amt  ,
        cast(base_invoice_grs_amt as number(38,10) ) as base_invoice_grs_amt  ,
        cast(base_invoice_net_amt as number(38,10) ) as base_invoice_net_amt  ,
        cast(phi_invoice_grs_amt as number(38,10) ) as phi_invoice_grs_amt  ,
        cast(phi_invoice_net_amt as number(38,10) ) as phi_invoice_net_amt  ,
        cast(pcomp_invoice_grs_amt as number(38,10) ) as pcomp_invoice_grs_amt  ,
        cast(pcomp_invoice_net_amt as number(38,10) ) as pcomp_invoice_net_amt  ,
        cast(substring(variant_code,1,255) as text(255) ) as variant_code  ,
        cast(open_ca_quantity as number(19,2) ) as open_ca_quantity  ,
        cast(base_ext_ing_cost as number(38,10) ) as base_ext_ing_cost  ,
        cast(base_ext_pkg_cost as number(38,10) ) as base_ext_pkg_cost  ,
        cast(base_ext_lbr_cost as number(38,10) ) as base_ext_lbr_cost  ,
        cast(base_ext_boughtin_cost as number(38,10) ) as base_ext_boughtin_cost  ,
        cast(base_ext_oth_cost as number(38,10) ) as base_ext_oth_cost  ,
        cast(base_ext_copack_cost as number(38,10) ) as base_ext_copack_cost  ,
        cast(trans_invoice_disc_amt as number(38,10) ) as trans_invoice_disc_amt  ,
        cast(base_invoice_disc_amt as number(38,10) ) as base_invoice_disc_amt  ,
        cast(phi_invoice_disc_amt as number(38,10) ) as phi_invoice_disc_amt  ,
        cast(pcomp_invoice_disc_amt as number(38,10) ) as pcomp_invoice_disc_amt  ,
        cast(substring(delivery_instruction,1,255) as text(255) ) as delivery_instruction  ,
        cast(substring(cust_order_number,1,30) as text(30) ) as cust_order_number  ,
        cast(item_shelf_life as number(38,0) ) as item_shelf_life  ,
        cast(substring(picking_route,1,10) as text(10) ) as picking_route  ,
        cast(trans_line_requested_date as date) as trans_line_requested_date  ,
        cast(unique_key as text(255) ) as unique_key ,
        cast(source_legacy as text(15)) as source_legacy
    from converted_fct