{{
    config(
    materialized = env_var('DBT_MAT_TABLE'),
    tags=["ax_hist_fact","ax_hist_finance"]
    )
}}

with
old_fct as (
    select *
    from {{ source("WBX_PROD_FACT", "fct_wbx_fin_ar_receipt_detail") }}
    where {{ env_var("DBT_PICK_FROM_CONV") }} = 'Y'
),

/* For AR Receipt Detail conversion of AX History, the following dimension fields are possible for "conversion".
    -Cost Center (aka Plant Dim): source_business_unit_code and plantdc_address_guid
    -Account Dim: source_object_id, account_guid, source_account_identifier

    There are also several different "account" groups of fields for this model: discount, writeoff, chargeback, and deduction.
    Of those, only discount has some values populated so the discount related columns need to be converted using the old_account conversion as well.
*/

old_plant as (
    select
        source_business_unit_code_new,
        source_business_unit_code,
        plantdc_address_guid_new,
        plantdc_address_guid
    from {{ ref('conv_dim_wbx_plant_dc') }}
),

old_account as (
    select
        source_object_id,
        source_object_id_old,
        source_company_code,
        account_guid,
        account_guid_old,
        source_account_identifier,
        source_account_identifier_old
    from {{ ref('conv_dim_wbx_account') }}
),

converted_fct as (
    select
        source_system,
        payment_identifier,
        line_number,
        receipt_number,
        document_number,
        document_type,
        document_company,
        document_pay_item,
        gl_date,
        posted_flag,
        cast(acnt.source_account_identifier as varchar(255)) as source_account_identifier,
        cast(acnt.source_account_identifier_old as varchar(255)) as source_account_identifier_old,
        target_account_identifier,
        acnt.account_guid,
        a.account_guid as account_guid_old,
        company_code,
        foreign_transaction_flag,
        acnt_discount.source_account_identifier as discount_src_accnt_identifier,
        acnt_discount.source_account_identifier_old as discount_src_accnt_identifier_old,
        discount_trgt_accnt_identifier,
        acnt_discount.account_guid as discount_account_guid,
        acnt_discount.account_guid_old as discount_account_guid_old,
        writeoff_reason_code,
        writeoff_src_accnt_identifier,
        writeoff_trgt_accnt_identifier,
        writeoff_account_guid,
        chargeback_reason_code,
        chargeback_src_accnt_idntifier,
        chargeback_trgt_accnt_idntifer,
        chargeback_account_guid,
        deduction_reason_code,
        deduction_src_accnt_idntifer,
        deduction_trgt_accnt_idntifer,
        deduction_account_guid,
        plnt.source_business_unit_code_new as source_business_unit_code,
        plnt.source_business_unit_code as source_business_unit_code_old,
        plnt.plantdc_address_guid_new as business_unit_address_guid,
        plnt.plantdc_address_guid as business_unit_address_guid_old,
        remark_txt,
        deduction_document_number,
        deduction_document_type,
        deduction_document_company,
        deduction_document_pay_item,
        journal_document_number,
        journal_document_type,
        journal_document_company,
        void_date,
        void_reason_code,
        net_due_date,
        discount_date,
        inv_jrnl_date,
        reference_txt,
        source_customer_identifier,
        customer_address_number_guid,
        source_payor_identifier,
        payor_address_number_guid,
        source_payment_instr_code,
        target_payment_instr_code,
        payment_instr_desc,
        transaction_currency,
        base_currency,
        phi_currency,
        pcomp_currency,
        txn_conv_rt,
        base_conv_rt,
        phi_conv_rt,
        pcomp_conv_rt,
        txn_payment_amt,
        txn_discount_avail_amt,
        txn_discount_taken_amt,
        txn_writeoff_amt,
        txn_chargeback_amt,
        txn_deduction_amt,
        txn_gain_loss_amt,
        base_payment_amt,
        base_discount_avail_amt,
        base_discount_taken_amt,
        base_writeoff_amt,
        base_chargeback_amt,
        base_deduction_amt,
        base_gain_loss_amt,
        phi_payment_amt,
        phi_discount_avail_amt,
        phi_discount_taken_amt,
        phi_writeoff_amt,
        phi_chargeback_amt,
        phi_deduction_amt,
        phi_gain_loss_amt,
        pcomp_payment_amt,
        pcomp_discount_avail_amt,
        pcomp_discount_taken_amt,
        pcomp_writeoff_amt,
        pcomp_chargeback_amt,
        pcomp_deduction_amt,
        pcomp_gain_loss_amt,
        intercompany_flag,
        source_date_updated,
        load_date,
        update_date,
        source_updated_d_id,
        batch_type,
        batch_number,
        batch_date,
        deduction_document_guid,
        ar_custinv_hdr_unique_key,
        unique_key
    from old_fct as a
    left join
        old_plant as plnt
        on a.business_unit_address_guid = plnt.plantdc_address_guid
    left join old_account as acnt on a.account_guid = acnt.account_guid_old
    left join old_account as acnt_discount on a.discount_account_guid = acnt_discount.account_guid_old
)

select 
    cast(substring(source_system,1,255) as text(255) ) as source_system  ,
    cast(substring(payment_identifier,1,255) as text(255) ) as payment_identifier  ,
    cast(line_number as number(38,10) ) as line_number  ,
    cast(substring(receipt_number,1,255) as text(255) ) as receipt_number  ,
    cast(substring(document_number,1,255) as text(255) ) as document_number  ,
    cast(substring(document_type,1,255) as text(255) ) as document_type  ,
    cast(substring(document_company,1,255) as text(255) ) as document_company  ,
    cast(substring(document_pay_item,1,255) as text(255) ) as document_pay_item  ,
    cast(gl_date as timestamp_ntz(9) ) as gl_date  ,
    cast(substring(posted_flag,1,6) as text(6) ) as posted_flag  ,
    cast(substring(source_account_identifier,1,255) as text(255) ) as source_account_identifier  ,
    cast(substring(source_account_identifier_old,1,255) as text(255) ) as source_account_identifier_old  ,
    cast(substring(target_account_identifier,1,255) as text(255) ) as target_account_identifier  ,
    cast(substring(account_guid,1,255) as text(255) ) as account_guid  ,
    cast(substring(account_guid_old,1,255) as text(255) ) as account_guid_old  ,
    cast(substring(company_code,1,255) as text(255) ) as company_code  ,
    cast(substring(foreign_transaction_flag,1,20) as text(20) ) as foreign_transaction_flag  ,
    cast(substring(discount_src_accnt_identifier,1,255) as text(255) ) as discount_src_accnt_identifier  ,
    cast(substring(discount_src_accnt_identifier_old,1,255) as text(255) ) as discount_src_accnt_identifier_old  ,
    cast(substring(discount_trgt_accnt_identifier,1,255) as text(255) ) as discount_trgt_accnt_identifier  ,
    cast(substring(discount_account_guid,1,255) as text(255) ) as discount_account_guid  ,
    cast(substring(discount_account_guid_old,1,255) as text(255) ) as discount_account_guid_old  ,
    cast(substring(writeoff_reason_code,1,255) as text(255) ) as writeoff_reason_code  ,
    cast(substring(writeoff_src_accnt_identifier,1,255) as text(255) ) as writeoff_src_accnt_identifier  ,
    cast(substring(writeoff_trgt_accnt_identifier,1,255) as text(255) ) as writeoff_trgt_accnt_identifier  ,
    cast(substring(writeoff_account_guid,1,255) as text(255) ) as writeoff_account_guid  ,
    cast(substring(chargeback_reason_code,1,255) as text(255) ) as chargeback_reason_code  ,
    cast(substring(chargeback_src_accnt_idntifier,1,255) as text(255) ) as chargeback_src_accnt_idntifier  ,
    cast(substring(chargeback_trgt_accnt_idntifer,1,255) as text(255) ) as chargeback_trgt_accnt_idntifer  ,
    cast(substring(chargeback_account_guid,1,255) as text(255) ) as chargeback_account_guid  ,
    cast(substring(deduction_reason_code,1,255) as text(255) ) as deduction_reason_code  ,
    cast(substring(deduction_src_accnt_idntifer,1,255) as text(255) ) as deduction_src_accnt_idntifer  ,
    cast(substring(deduction_trgt_accnt_idntifer,1,255) as text(255) ) as deduction_trgt_accnt_idntifer  ,
    cast(substring(deduction_account_guid,1,255) as text(255) ) as deduction_account_guid  ,
    cast(substring(source_business_unit_code,1,255) as text(255) ) as source_business_unit_code  ,
    cast(substring(source_business_unit_code_old,1,255) as text(255) ) as source_business_unit_code_old  ,
    cast(substring(business_unit_address_guid,1,255) as text(255) ) as business_unit_address_guid  ,
    cast(substring(business_unit_address_guid_old,1,255) as text(255) ) as business_unit_address_guid_old  ,
    cast(substring(remark_txt,1,255) as text(255) ) as remark_txt  ,
    cast(substring(deduction_document_number,1,255) as text(255) ) as deduction_document_number  ,
    cast(substring(deduction_document_type,1,255) as text(255) ) as deduction_document_type  ,
    cast(substring(deduction_document_company,1,255) as text(255) ) as deduction_document_company  ,
    cast(substring(deduction_document_pay_item,1,255) as text(255) ) as deduction_document_pay_item  ,
    cast(substring(journal_document_number,1,255) as text(255) ) as journal_document_number  ,
    cast(substring(journal_document_type,1,255) as text(255) ) as journal_document_type  ,
    cast(substring(journal_document_company,1,255) as text(255) ) as journal_document_company  ,
    cast(void_date as timestamp_ntz(9) ) as void_date  ,
    cast(substring(void_reason_code,1,255) as text(255) ) as void_reason_code  ,
    cast(net_due_date as timestamp_ntz(9) ) as net_due_date  ,
    cast(discount_date as timestamp_ntz(9) ) as discount_date  ,
    cast(inv_jrnl_date as timestamp_ntz(9) ) as inv_jrnl_date  ,
    cast(substring(reference_txt,1,255) as text(255) ) as reference_txt  ,
    cast(substring(source_customer_identifier,1,255) as text(255) ) as source_customer_identifier  ,
    cast(substring(customer_address_number_guid,1,255) as text(255) ) as customer_address_number_guid  ,
    cast(substring(source_payor_identifier,1,255) as text(255) ) as source_payor_identifier  ,
    cast(substring(payor_address_number_guid,1,255) as text(255) ) as payor_address_number_guid  ,
    cast(substring(source_payment_instr_code,1,255) as text(255) ) as source_payment_instr_code  ,
    cast(substring(target_payment_instr_code,1,255) as text(255) ) as target_payment_instr_code  ,
    cast(substring(payment_instr_desc,1,255) as text(255) ) as payment_instr_desc  ,
    cast(substring(transaction_currency,1,255) as text(255) ) as transaction_currency  ,
    cast(substring(base_currency,1,255) as text(255) ) as base_currency  ,
    cast(substring(phi_currency,1,255) as text(255) ) as phi_currency  ,
    cast(substring(pcomp_currency,1,255) as text(255) ) as pcomp_currency  ,
    cast(txn_conv_rt as number(29,9) ) as txn_conv_rt  ,
    cast(base_conv_rt as number(29,9) ) as base_conv_rt  ,
    cast(phi_conv_rt as number(29,9) ) as phi_conv_rt  ,
    cast(pcomp_conv_rt as number(29,9) ) as pcomp_conv_rt  ,
    cast(txn_payment_amt as number(38,10) ) as txn_payment_amt  ,
    cast(txn_discount_avail_amt as number(38,10) ) as txn_discount_avail_amt  ,
    cast(txn_discount_taken_amt as number(38,10) ) as txn_discount_taken_amt  ,
    cast(txn_writeoff_amt as number(38,10) ) as txn_writeoff_amt  ,
    cast(txn_chargeback_amt as number(38,10) ) as txn_chargeback_amt  ,
    cast(txn_deduction_amt as number(38,10) ) as txn_deduction_amt  ,
    cast(txn_gain_loss_amt as number(38,10) ) as txn_gain_loss_amt  ,
    cast(base_payment_amt as number(38,10) ) as base_payment_amt  ,
    cast(base_discount_avail_amt as number(38,10) ) as base_discount_avail_amt  ,
    cast(base_discount_taken_amt as number(38,10) ) as base_discount_taken_amt  ,
    cast(base_writeoff_amt as number(38,10) ) as base_writeoff_amt  ,
    cast(base_chargeback_amt as number(38,10) ) as base_chargeback_amt  ,
    cast(base_deduction_amt as number(38,10) ) as base_deduction_amt  ,
    cast(base_gain_loss_amt as number(38,10) ) as base_gain_loss_amt  ,
    cast(phi_payment_amt as number(38,10) ) as phi_payment_amt  ,
    cast(phi_discount_avail_amt as number(38,10) ) as phi_discount_avail_amt  ,
    cast(phi_discount_taken_amt as number(38,10) ) as phi_discount_taken_amt  ,
    cast(phi_writeoff_amt as number(38,10) ) as phi_writeoff_amt  ,
    cast(phi_chargeback_amt as number(38,10) ) as phi_chargeback_amt  ,
    cast(phi_deduction_amt as number(38,10) ) as phi_deduction_amt  ,
    cast(phi_gain_loss_amt as number(38,10) ) as phi_gain_loss_amt  ,
    cast(pcomp_payment_amt as number(38,10) ) as pcomp_payment_amt  ,
    cast(pcomp_discount_avail_amt as number(38,10) ) as pcomp_discount_avail_amt  ,
    cast(pcomp_discount_taken_amt as number(38,10) ) as pcomp_discount_taken_amt  ,
    cast(pcomp_writeoff_amt as number(38,10) ) as pcomp_writeoff_amt  ,
    cast(pcomp_chargeback_amt as number(38,10) ) as pcomp_chargeback_amt  ,
    cast(pcomp_deduction_amt as number(38,10) ) as pcomp_deduction_amt  ,
    cast(pcomp_gain_loss_amt as number(38,10) ) as pcomp_gain_loss_amt  ,
    cast(substring(intercompany_flag,1,1) as text(1) ) as intercompany_flag  ,
    cast(source_date_updated as timestamp_ntz(9) ) as source_date_updated  ,
    cast(load_date as timestamp_ntz(9) ) as load_date  ,
    cast(update_date as timestamp_ntz(9) ) as update_date  ,
    cast(source_updated_d_id as number(38,0) ) as source_updated_d_id  ,
    cast(substring(batch_type,1,4) as text(4) ) as batch_type  ,
    cast(substring(batch_number,1,255) as text(255) ) as batch_number  ,
    cast(batch_date as timestamp_ntz(9) ) as batch_date  ,
    cast(substring(deduction_document_guid,1,255) as text(255) ) as deduction_document_guid  ,
    cast(substring(ar_custinv_hdr_unique_key,1,255) as text(255) ) as ar_custinv_hdr_unique_key  ,
    cast(substring(unique_key,1,255) as text(255) ) as unique_key
from converted_fct

