{{
    config(
    materialized = env_var('DBT_MAT_TABLE'),
    tags=["ax_hist_dim"]
    )
}}

WITH old_dim AS 
(
    SELECT 'CUSTOMER_MAIN' as GENERIC_ADDRESS_TYPE,* FROM {{source('WBX_PROD','dim_wbx_customer_ext')}} where {{env_var("DBT_PICK_FROM_CONV")}}='Y'
),

converted_dim as (
SELECT
Unique_key,  
SOURCE_SYSTEM,
CUSTOMER_ADDRESS_NUMBER_GUID_old,
{{ dbt_utils.surrogate_key(['source_system','source_system_address_number','GENERIC_ADDRESS_TYPE','company_code']) }} AS CUSTOMER_ADDRESS_NUMBER_GUID,
COMPANY_ADDRESS_GUID,
SOURCE_SYSTEM_ADDRESS_NUMBER,
COMPANY_CODE,
MARKET_CODE,
MARKET_DESC,
MARKET_CODE_SEQ,
SUB_MARKET_CODE,
SUB_MARKET_DESC,
SUB_MARKET_CODE_SEQ,
TRADE_CLASS_CODE,
TRADE_CLASS_DESC,
TRADE_CLASS_SEQ,
TRADE_GROUP_CODE,
TRADE_GROUP_DESC,
TRADE_GROUP_SEQ,
TRADE_TYPE_CODE,
TRADE_TYPE_DESC,
TRADE_TYPE_SEQ,
TRADE_SECTOR_CODE,
TRADE_SECTOR_DESC,
TRADE_SECTOR_SEQ,
PRICE_GROUP,
TOTAL_SO_QTY_DISCOUNT,
ADDITIONAL_DISCOUNT,
CUSTOMER_REBATE_GROUP,
CURRENCY,
VAT_GROUP,
DATE_INSERTED,
DATE_UPDATED,
MIN_ORDER_QTY_CA,
MIN_ORDER_QTY_PALLETS,
FULL_PALLET_FLAG,
MAX_ORDER_QTY_CA,
MAX_ORDER_QTY_PALLETS,
FIN_DIM_COST_CENTRE,
FIN_DIM_CUSTOMER,
FIN_DIM_DEPARTMENT,
FIN_DIM_SITE
FROM old_dim
)

Select * from converted_dim