with d365source as (
    select *
    from {{ source("D365S", "vendtable") }}
    where
        _fivetran_deleted = 'FALSE'
        and upper(dataareaid) in {{ env_var("DBT_D365_COMPANY_FILTER") }}

),

renamed as (
    select
        'D365S' as source,
        accountnum as accountnum,
        invoiceaccount as invoiceaccount,
        vendgroup as vendgroup,
        paymtermid as paymtermid,
        null as cashdisc,
        currency as currency,
        null as linedisc,
        null as enterprisenumber,
        blocked as blocked,
        onetimevendor as onetimevendor,
        null as pricegroup,
        null as multilinedisc,
        null as enddisc,
        null as paymid,
        vatnum as vatnum,
        inventlocation as inventlocation,
        null as youraccountnum,
        dlvterm as dlvterm,
        dlvmode as dlvmode,
        null as bankaccount,
        paymmode as paymmode,
        null as paymspec,
        null as markupgroup,
        null as clearingperiod,
        null as companyidsiret,
        taxgroup as taxgroup,
        null as freightzone,
        minorityowned as minorityowned,
        femaleowned as femaleowned,
        null as creditrating,
        creditmax as creditmax,
        tax_1099_reports as tax1099reports,
        null as tax1099regnum,
        null as paymsched,
        null as itembuyergroupid,
        null as contactpersonid,
        purchpoolid as purchpoolid,
        purchamountpurchaseorder as purchamountpurchaseorder,
        incltax as incltax,
        null as venditemgroupid,
        null as numbersequencegroup,
        null as paymdayid,
        null as destinationcodeid,
        lineofbusinessid as lineofbusinessid,
        null as suppitemgroupid,
        null as bankcentralbankpurposetext,
        null as bankcentralbankpurposecode,
        offsetaccounttype as offsetaccounttype,
        null as purchcalendarid,
        null as organizationnumber,
        null as fiscalcode,
        taxwithholdcalculate as taxwithholdcalculate,
        null as taxwithholdgroup,
        null as birthdate,
        null as birthplace,
        null as residenceforeigncntyregid,
        null as namecontrol,
        foreignentityindicator as foreignentityindicator,
        taxidtype as taxidtype,
        null as dba,
        tax_1099_namechoice as tax1099namechoice,
        secondtin as secondtin,
        inventsiteid as inventsiteid,
        segmentid as segmentid,
        subsegmentid as subsegmentid,
        companychainid as companychainid,
        null as vendpricetolerancegroupid,
        null as memo,
        smallbusiness as smallbusiness,
        locallyowned as locallyowned,
        bidonly as bidonly,
        w_9 as w9,
        null as orgid,
        null as factoringaccount,
        matchingpolicy as matchingpolicy,
        cast(blockedreleasedate as TIMESTAMP_NTZ) as blockedreleasedate,
        null as blockedreleasedatetzid,
        w_9_included as w9included,
        vendexceptiongroup as vendexceptiongroup,
        party as party,
        defaultdimension as defaultdimension,
        offsetledgerdimension as offsetledgerdimension,
        null as birthcountycode_it,
        heir_it as heir_it,
        changerequestenabled as changerequestenabled,
        changerequestallowoverride as changerequestallowoverride,
        changerequestoverride as changerequestoverride,
        companynafcode as companynafcode,
        vendinvoicedeclaration_is as vendinvoicedeclaration_is,
        tax_1099_fields as tax1099fields,
        vendortype_mx as vendortype_mx,
        null as foreigntaxregistration_mx,
        null as nationality_mx,
        null as diotcountrycode_mx,
        operationtype_mx as operationtype_mx,
        maincontactworker as maincontactworker,
        companytype_mx as companytype_mx,
        null as rfc_mx,
        null as curp_mx,
        null as stateinscription_mx,
        null as ccmnum_br,
        null as ienum_br,
        null as cnpjcpfnum_br,
        null as vendincomecode_br,
        nontaxable_br as nontaxable_br,
        vendconsumption_br as vendconsumption_br,
        null as nit_br,
        null as insscei_br,
        null as cnae_br,
        icmscontributor_br as icmscontributor_br,
        servicecodeondlvaddress_br as servicecodeondlvaddress_br,
        null as interestcode_br,
        null as finecode_br,
        vattaxagent_ru as vattaxagent_ru,
        taxwithholdvendortype_th as taxwithholdvendortype_th,
        null as vatoperationcode_ru,
        vatpartnerkind_ru as vatpartnerkind_ru,
        inventprofiletype_ru as inventprofiletype_ru,
        null as inventprofileid_ru,
        unitedvatinvoice_lt as unitedvatinvoice_lt,
        consday_jp as consday_jp,
        null as structdepartment_ru,
        null as bankcentralbanktranstypecur_ru,
        null as bankorderofpayment_ru,
        null as enterprisecode,
        null as regnum_w,
        null as commercialregistersection,
        null as commercialregisterinsetnumber,
        null as commercialregister,
        isresident_lv as isresident_lv,
        null as intbank_lv,
        null as ciscompanyregnum,
        null as cisnationalinsurancenum,
        cisstatus as cisstatus,
        null as cisuniquetaxpayerref,
        cast(cisverificationdate as TIMESTAMP_NTZ) as cisverificationdate,
        null as cisverificationnum,
        null as defaultinventstatusid,
        disabledowned as disabledowned,
        null as ethnicoriginid,
        foreignresident_ru as foreignresident_ru,
        hubzone as hubzone,
        ispaymfeecovered_jp as ispaymfeecovered_jp,
        lvpaymtranscodes as lvpaymtranscodes,
        mandatoryvatdate_pl as mandatoryvatdate_pl,
        null as separatedivisionid_ru,
        null as tamrebategroupid,
        null as taxperiodpaymentcode_pl,
        usecashdisc as usecashdisc,
        veteranowned as veteranowned,
        null as vendpaymfeegroup_jp,
        null as foreignerid_br,
        presencetype_br as presencetype_br,
        vendorportaladministratorrecid as vendorportaladministratorrecid,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        null as biseanbarcodesetupid,
        null as biseancodeid,
        null as bisedipartner,
        null as bisitemcoding,
        null as bisitemcodingbarcodesetupid,
        null as bisitemcodinggtinsetup,
        fatcafilingrequirement as fatcafilingrequirement

    from d365source
)

select * from renamed
