with d365_source as (
        select *
        from {{ source("D365S", "vendinvoicejour") }} where _FIVETRAN_DELETED='FALSE' and upper(dataareaid) in {{env_var("DBT_D365_COMPANY_FILTER")}}

    ),

renamed as (

    select
        'D365S' as source,
        vendgroup as vendgroup,
        purchid as purchid,
        orderaccount as orderaccount,
        invoiceaccount as invoiceaccount,
        invoiceid as invoiceid,
        cast(invoicedate as TIMESTAMP_NTZ) as invoicedate,
        cast(duedate as TIMESTAMP_NTZ) as duedate,
        cashdisc as cashdisc,
        cast(cashdiscdate as TIMESTAMP_NTZ) as cashdiscdate,
        qty as qty,
        volume as volume,
        weight as weight,
        sumlinedisc as sumlinedisc,
        prepayment as prepayment,
        salesbalance as salesbalance,
        enddisc as enddisc,
        invoiceamount as invoiceamount,
        currencycode as currencycode,
        exchrate as exchrate,
        null as enterprisenumber,
        null as returnitemnum,
        taxroundoff as taxroundoff,
        ledgervoucher as ledgervoucher,
        taxprintoninvoice as taxprintoninvoice,
        taxspecifybyline as taxspecifybyline,
        null as documentnum,
        cast(documentdate as TIMESTAMP_NTZ) as documentdate,
        countryregionid as countryregionid,
        intrastatdispatch as intrastatdispatch,
        invoiceroundoff as invoiceroundoff,
        summarkup as summarkup,
        null as paymid,
        taxgroup as taxgroup,
        null as cashdisccode,
        cashdiscpercent as cashdiscpercent,
        payment as payment,
        postingprofile as postingprofile,
        null as paymentsched,
        intercompanyposted as intercompanyposted,
        purchasetype as purchasetype,
        sumtax as sumtax,
        parmid as parmid,
        exchratesecondary as exchratesecondary,
        triangulation as triangulation,
        null as itembuyergroupid,
        vatnum as vatnum,
        internalinvoiceid as internalinvoiceid,
        null as numbersequencegroup,
        incltax as incltax,
        null as paymdayid,
        dlvterm as dlvterm,
        dlvmode as dlvmode,
        cast(fixedduedate as TIMESTAMP_NTZ) as fixedduedate,
        intercompanycompanyid as intercompanycompanyid,
        null as intercompanysalesid,
        null as intercompanyledgervoucher,
        proforma as proforma,
        languageid as languageid,
        invoiceamountmst as invoiceamountmst,
        summarkupmst as summarkupmst,
        enddiscmst as enddiscmst,
        null as reversecharge_uk,
        documentorigin as documentorigin,
        null as vendinvoicegroup,
        null as vendpaymentgroup,
        defaultdimension as defaultdimension,
        description as description,
        null as contractnum_sa,
        remittanceaddress as remittanceaddress,
        vendinvoicedeclaration_is as vendinvoicedeclaration_is,
        costledgervoucher as costledgervoucher,
        sourcedocumentheader as sourcedocumentheader,
        sourcedocumentline as sourcedocumentline,
        operationtype_mx as operationtype_mx,
        listcode as listcode,
        null as eusaleslist,
        null as vendorrequestedworkeremail,
        logisticselectronicaddress as logisticselectronicaddress,
        banklcimportline as banklcimportline,
        invoicetype as invoicetype,
        deliveryname as deliveryname,
        cast(deliverydate_es as TIMESTAMP_NTZ) as deliverydate_es,
        cast(purchreceiptdate_w as TIMESTAMP_NTZ) as purchreceiptdate_w,
        vatonpayment_ru as vatonpayment_ru,
        correct_ru as correct_ru,
        whoisauthor_lt as whoisauthor_lt,
        null as invoicestatus_lt,
        inventprofiletype_ru as inventprofiletype_ru,
        null as taxinvoicepurchid,
        null as numbersequencecode_lt,
        cast(correctedinvoicedate_ru as TIMESTAMP_NTZ) as correctedinvoicedate_ru,
        vatamount_in as vatamount_in,
        taxwithholdamount_in as taxwithholdamount_in,
        vendconsinvoice_jp as vendconsinvoice_jp,
        null as deliveryname_lt,
        null as deliveryaddress_lt,
        cast(intrastatfulfillmentdate_hu as TIMESTAMP_NTZ) as intrastatfulfillmentdate_hu,
        unitedvatinvoice_lt as unitedvatinvoice_lt,
        nonrealrevenue_ru as nonrealrevenue_ru,
        null as offsessionid_ru,
        null as consigneeaccount_ru,
        null as consignoraccount_ru,
        facturedfully_ru as facturedfully_ru,
        null as attorneyissuedname_ru,
        null as attorneyid_ru,
        cast(attorneydate_ru as TIMESTAMP_NTZ) as attorneydate_ru,
        stateinvoiceprinted_lv as stateinvoiceprinted_lv,
        null as dlvaddress_lv,
        intrastataddvalue_lv as intrastataddvalue_lv,
        null as invoiceregister_lt,
        purchagreementheader_psn as purchagreementheader_psn,
        constarget_jp as constarget_jp,
        null as correctedinvoiceid_ru,
        correctiontype_ru as correctiontype_ru,
        deliverypostaladdress as deliverypostaladdress,
        fiscaldocumenttype_br as fiscaldocumenttype_br,
        null as inventbaileereceiptreportid_ru,
        reasontableref_br as reasontableref_br,
        salespurchoperationtype_br as salespurchoperationtype_br,
        servicecodeondlvaddress_br as servicecodeondlvaddress_br,
        null as taxsetoffvoucher_in,
        null as transitcontrolvoucher_br,
        transportationdocument as transportationdocument,
        vendfinaluser_br as vendfinaluser_br,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        createdby as createdby,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        null as cfdiuuid_mx,
        null as invoiceseries_mx,
        null as invoiceidentification_in

from d365_source

)

select * from renamed
