with
d365source as (

    select *
    from {{ source("D365S", "custtable") }}
    where
        upper(trim(dataareaid)) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
        and _fivetran_deleted = 'FALSE'
),

renamed as (
    select
        'D365S' as source,
        accountnum as accountnum,
        invoiceaccount as invoiceaccount,
        custgroup as custgroup,
        linedisc as linedisc,
        paymtermid as paymtermid,
        null as cashdisc,
        currency as currency,
        intercompanyautocreateorders as intercompanyautocreateorders,
        null as salesgroup,
        blocked as blocked,
        onetimecustomer as onetimecustomer,
        accountstatement as accountstatement,
        creditmax as creditmax,
        mandatorycreditlimit as mandatorycreditlimit,
        vendaccount as vendaccount,
        pricegroup as pricegroup,
        null as multilinedisc,
        null as enddisc,
        vatnum as vatnum,
        inventlocation as inventlocation,
        dlvterm as dlvterm,
        dlvmode as dlvmode,
        markupgroup as markupgroup,
        null as clearingperiod,
        null as freightzone,
        null as creditrating,
        taxgroup as taxgroup,
        null as statisticsgroup,
        paymmode as paymmode,
        null as commissiongroup,
        null as bankaccount,
        null as paymsched,
        null as contactpersonid,
        invoiceaddress as invoiceaddress,
        null as ouraccountnum,
        salespoolid as salespoolid,
        incltax as incltax,
        null as custitemgroupid,
        null as numbersequencegroup,
        null as paymdayid,
        null as lineofbusinessid,
        null as destinationcodeid,
        girotype as girotype,
        null as suppitemgroupid,
        girotypeinterestnote as girotypeinterestnote,
        null as taxlicensenum,
        websalesorderdisplay as websalesorderdisplay,
        null as paymspec,
        null as bankcentralbankpurposetext,
        null as bankcentralbankpurposecode,
        null as intercoallowindirectcreation,
        null as packmaterialfeelicensenum,
        null as taxbordernumber_fi,
        null as einvoiceeannum,
        null as fiscalcode,
        null as dlvreason,
        forecastdmpinclude as forecastdmpinclude,
        girotypecollectionletter as girotypecollectionletter,
        null as salescalendarid,
        custclassificationid as custclassificationid,
        intercompanydirectdelivery as intercompanydirectdelivery,
        null as enterprisenumber,
        null as shipcarrieraccount,
        girotypeprojinvoice as girotypeprojinvoice,
        inventsiteid as inventsiteid,
        null as orderentrydeadlinegroupid,
        null as shipcarrierid,
        shipcarrierfuelsurcharge as shipcarrierfuelsurcharge,
        shipcarrierblindshipment as shipcarrierblindshipment,
        null as shipcarrieraccountcode,
        girotypefreetextinvoice as girotypefreetextinvoice,
        null as syncentityid,
        null as syncversion,
        null as memo,
        null as salesdistrictid,
        null as segmentid,
        null as subsegmentid,
        rfiditemtagging as rfiditemtagging,
        rfidcasetagging as rfidcasetagging,
        rfidpallettagging as rfidpallettagging,
        companychainid as companychainid,
        null as companyidsiret,
        party as party,
        null as identificationnumber,
        null as partycountry,
        null as partystate,
        null as orgid,
        null as paymidtype,
        null as factoringaccount,
        defaultdimension as defaultdimension,
        custexcludecollectionfee as custexcludecollectionfee,
        custexcludeinterestcharges as custexcludeinterestcharges,
        companynafcode as companynafcode,
        bankcustpaymidtable as bankcustpaymidtable,
        girotypeaccountstatement as girotypeaccountstatement,
        maincontactworker as maincontactworker,
        creditcardaddressverification as creditcardaddressverification,
        creditcardcvc as creditcardcvc,
        null as creditcardaddressverivoid,
        null as creditcardaddressverilevel,
        companytype_mx as companytype_mx,
        null as rfc_mx,
        null as curp_mx,
        null as stateinscription_mx,
        null as residenceforeignctryregid_it,
        null as birthcountycode_it,
        null as birthdate_it,
        null as birthplace_it,
        einvoice as einvoice,
        einvoiceregister_it as einvoiceregister_it,
        null as ccmnum_br,
        null as cnpjcpfnum_br,
        null as pbacustgroupid,
        null as ienum_br,
        null as suframanumber_br,
        suframa_br as suframa_br,
        custfinaluser_br as custfinaluser_br,
        null as interestcode_br,
        null as finecode_br,
        suframapiscofins_br as suframapiscofins_br,
        taxwithholdcalculate_th as taxwithholdcalculate_th,
        null as taxwithholdgroup_th,
        consday_jp as consday_jp,
        null as nit_br,
        null as insscei_br,
        null as cnae_br,
        icmscontributor_br as icmscontributor_br,
        servicecodeondlvaddress_br as servicecodeondlvaddress_br,
        inventprofiletype_ru as inventprofiletype_ru,
        null as inventprofileid_ru,
        taxwithholdcalculate_in as taxwithholdcalculate_in,
        unitedvatinvoice_lt as unitedvatinvoice_lt,
        null as foreignerid_br,
        null as enterprisecode,
        null as commercialregistersection,
        null as commercialregisterinsetnumber,
        null as commercialregister,
        null as regnum_w,
        isresident_lv as isresident_lv,
        null as intbank_lv,
        null as paymentreference_ee,
        packagedepositexcempt_pl as packagedepositexcempt_pl,
        fednonfedindicator as fednonfedindicator,
        irs_1099_cindicator as irs1099cindicator,
        null as agencylocationcode,
        null as federalcomments,
        usepurchrequest as usepurchrequest,
        null as mcrmergedparent,
        null as mcrmergedroot,
        affiliated_ru as affiliated_ru,
        cashdiscbasedays as cashdiscbasedays,
        custtradingpartnercode as custtradingpartnercode,
        custwhtcontributiontype_br as custwhtcontributiontype_br,
        null as daxintegrationid,
        defaultdirectdebitmandate as defaultdirectdebitmandate,
        null as defaultinventstatusid,
        entrycertificaterequired_w as entrycertificaterequired_w,
        exportsales_pl as exportsales_pl,
        expressbilloflading as expressbilloflading,
        fiscaldoctype_pl as fiscaldoctype_pl,
        foreignresident_ru as foreignresident_ru,
        null as generateincomingfiscaldoc_br,
        invoicepostingtype_ru as invoicepostingtype_ru,
        issueownentrycertificate_w as issueownentrycertificate_w,
        null as issuercountry_hu,
        lvpaymtranscodes as lvpaymtranscodes,
        mandatoryvatdate_pl as mandatoryvatdate_pl,
        null as passportno_hu,
        null as pdscustrebategroupid,
        pdsfreightaccrued as pdsfreightaccrued,
        null as pdsrebatetmagroup,
        null as taxperiodpaymentcode_pl,
        usecashdisc as usecashdisc,
        null as authorityoffice_it,
        presencetype_br as presencetype_br,
        taxgstreliefgroupheading_my as taxgstreliefgroupheading_my,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        upper(trim(dataareaid)) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        null as foreigntaxregistration_mx,
        null as biseancodeid,
        null as bisedipartner,
        null as bisitemcoding,
        null as bisitemcodingbarcodesetupid,
        null as bisitemcodinggtinsetup,
        null as biseanbarcodesetupid,
        null as allowzeroprices,
        null as salestradegroupid,
        null as salestradesectorid,
        null as satpurpose_mx,
        null as satpaymmethod_mx,
        wbxmarket,
        wbxsubmarket,
        wbxtradeclass as wbxtrade_class,
        wbxtradetype as wbxtrade_type,
        wbxtradegroup as wbxtrade_group,
        wbxtradesector as wbxtrade_sector,
        wbxoneproductperpallet as wbxone_product_per_pallet,
        wbxcontractorindicator as wbxcontractor_indicator,
        wbxdeliveryinstructions as wbxdelivery_instructions,
        wbxrequestedreceipttime as wbxrequested_receipt_time,
        wbxedifti,
        wbxedicreditnote as wbxedicredit_note,
        wbxedisalesinvoice as wbxedisales_invoice,
        wbxglninvoicelocation as wbxglninvoice_location,
        wbxglnseller,
        wbxpodrequired,
        wbxpoddelayindays as wbxpoddelay_in_days,
        wbxasnrequired,
        wbxoverridedeliverycontrol as wbxoverride_delivery_control,
        wbxexcludefromallocation as wbxexclude_from_allocation,
        wbxaccountnumber as wbxaccount_number,
        wbxdeliverydatecontroltype as wbxdelivery_date_control_type,
        wbxfullpallet as wbxfull_pallet,
        wbxglndepartment,
        wbxglngoodsreceipt as wbxglngoods_receipt,
        wbxglnpaymentreceiver as wbxglnpayment_receiver,
        wbxglnorderlocation as wbxglnorder_location,
        wbxglnpayer as wbxglnpayer

    from d365source

)

select *
from renamed
qualify
    row_number() over (partition by accountnum, dataareaid order by source desc)
    = 1
