with d365source as (
    select *
    from {{ source("D365S", "vendtrans") }}
    where
        _fivetran_deleted = 'FALSE'
        and upper(dataareaid) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
),

renamed as (
    select
        'D365S' as source,
        accountnum as accountnum,
        cast(transdate as TIMESTAMP_NTZ) as transdate,
        voucher as voucher,
        invoice as invoice,
        txt as txt,
        amountcur as amountcur,
        settleamountcur as settleamountcur,
        amountmst as amountmst,
        settleamountmst as settleamountmst,
        currencycode as currencycode,
        cast(duedate as TIMESTAMP_NTZ) as duedate,
        lastsettlevoucher as lastsettlevoucher,
        cast(lastsettledate as TIMESTAMP_NTZ) as lastsettledate,
        cast(closed as TIMESTAMP_NTZ) as closed,
        transtype as transtype,
        approved as approved,
        paymtermid as paymid,   --field fixed
        exchadjustment as exchadjustment,
        null as documentnum,
        cast(documentdate as TIMESTAMP_NTZ) as documentdate,
        arrival as arrival,
        cast(lastexchadj as TIMESTAMP_NTZ) as lastexchadj,
        correct as correct,
        null as lastexchadjvoucher,
        lastexchadjrate as lastexchadjrate,
        postingprofile as postingprofile,
        settlement as settlement,
        cancel as cancel,
        null as postingprofileclose,
        null as postingprofileapprove,
        null as postingprofilecancel,
        null as postingprofilereopen,
        null as thirdpartybankaccountid,
        companybankaccountid as companybankaccountid,
        null as paymreference,
        paymmode as paymmode,
        cast(tax_1099_date as TIMESTAMP_NTZ) as tax1099date,
        tax_1099_amount as tax1099amount,
        null as tax1099num,
        offsetrecid as offsetrecid,
        journalnum as journalnum,
        eurotriangulation as eurotriangulation,
        null as cashdisccode,
        prepayment as prepayment,
        null as paymspec,
        vendexchadjustmentrealized as vendexchadjustmentrealized,
        vendexchadjustmentunrealized as vendexchadjustmentunrealized,
        cast(approveddate as TIMESTAMP_NTZ) as approveddate,
        null as promissorynoteid,
        promissorynotestatus as promissorynotestatus,
        promissorynoteseqnum as promissorynoteseqnum,
        null as bankremittancefileid,
        fixedexchrate as fixedexchrate,
        null as bankcentralbankpurposetext,
        null as bankcentralbankpurposecode,
        null as tax1099state,
        tax_1099_stateamount as tax1099stateamount,
        settletax_1099_amount as settletax1099amount,
        settletax_1099_stateamount as settletax1099stateamount,
        defaultdimension as defaultdimension,
        exchratesecond as exchratesecond,
        exchrate as exchrate,
        lastsettleaccountnum as lastsettleaccountnum,
        lastsettlecompany as lastsettlecompany,
        invoiceproject as invoiceproject,
        reasonrefrecid as reasonrefrecid,
        null as releasedatecomment,
        cast(invoicereleasedate as TIMESTAMP_NTZ) as invoicereleasedate,
        null as invoicereleasedatetzid,
        null as vendpaymentgroup,
        remittancelocation as remittancelocation,
        remittanceaddress as remittanceaddress,
        tax_1099_fields as tax1099fields,
        banklcimportline as banklcimportline,
        accountingevent as accountingevent,
        approver as approver,
        reportingcurrencyamount as reportingcurrencyamount,
        --field fixed
        reportingexchadjustmentrealized as reportingexchadjustmentrlzed,
        --field fixed
        reportingexchadjustmentunrealized as reportingexchadjustmentunrlzed,
        lastexchadjratereporting as lastexchadjratereporting,
        reportingcurrencycrossrate as reportingcurrencycrossrate,
        exchadjustmentreporting as exchadjustmentreporting,
        settleamountreporting as settleamountreporting,
        null as taxinvoicepurchid,
        tax_1099_recid as tax1099recid,
        null as consessionsettlementid,
        rbovendtrans as rbovendtrans,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        modifiedtransactionid as modifiedtransactionid,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        createdtransactionid as createdtransactionid,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid

    from d365source

)

select * from renamed
