with d365_source as (

    select *
    from {{ source("D365S", "purchparmtable") }}
    where
        _fivetran_deleted = 'FALSE'
        and upper(trim(dataareaid)) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
),

renamed as (
    select
        'D365S' as source,
        deliveryname as deliveryname,
        purchid as purchid,
        ordering as ordering,
        batchadministration as batchadministration,
        cast(transdate as TIMESTAMP_NTZ) as transdate,
        num as num,
        cast(documentdate as TIMESTAMP_NTZ) as documentdate,
        null as documentnum,
        null as paymid,
        cashdisc as cashdisc,
        invoiceroundoff as invoiceroundoff,
        taxroundoff as taxroundoff,
        enddisc as enddisc,
        purchname as purchname,
        orderaccount as orderaccount,
        cast(cashdiscdate as TIMESTAMP_NTZ) as cashdiscdate,
        storno as storno,
        invoiceaccount as invoiceaccount,
        null as description,
        parmjobstatus as parmjobstatus,
        currencycode as currencycode,
        parmid as parmid,
        log as log,
        payment as payment,
        hold as hold,
        vendinvoicesavestatus as vendinvoicesavestatus,
        null as paymentsched,
        null as paymmode,
        null as paymspec,
        recalculate as recalculate,
        null as vendbankaccountid,
        fixedexchrate as fixedexchrate,
        eurotriangulation as eurotriangulation,
        exchrate as exchrate,
        exchratesecondary as exchratesecondary,
        cast(fixedduedate as TIMESTAMP_NTZ) as fixedduedate,
        tablerefid as tablerefid,
        null as cashdisccode,
        documentorigin as documentorigin,
        cashdiscpercent as cashdiscpercent,
        null as taxgroup,
        null as vatnum,
        null as releasedatecomment,
        cast(invoicereleasedate as TIMESTAMP_NTZ) as invoicereleasedate,
        null as invoicereleasedatetzid,
        incltax as incltax,
        null as postingprofile,
        null as enterprisenumber,
        cast(enddatetime as TIMESTAMP_NTZ) as enddatetime,
        null as enddatetimetzid,
        cast(startdatetime as TIMESTAMP_NTZ) as startdatetime,
        null as startdatetimetzid,
        varianceapproved as varianceapproved,
        cast(varianceapproveddatetime as TIMESTAMP_NTZ)
            as varianceapproveddatetime,
        null as varianceapproveddatetimetzid,
        null as variancecomment,
        settlevoucher as settlevoucher,
        null as numbersequencegroup,
        null as transactioncode,
        null as transport,
        null as port,
        null as statprocid,
        null as countyorigdest,
        null as vendinvoicegroup,
        null as vendpaymentgroup,
        lastmatchvariance as lastmatchvariance,
        deliverypostaladdress as deliverypostaladdress,
        remittancelocation as remittancelocation,
        ignorecalculatedsalestax as ignorecalculatedsalestax,
        workflowstate as workflowstate,
        banklcimportline as banklcimportline,
        electronicinvoice_br as electronicinvoice_br,
        inventprofiletype_ru as inventprofiletype_ru,
        taxinformation_in as taxinformation_in,
        null as customsbillofentrynumtbl_in,
        null as customsimportinvoicenumtbl_in,
        null as consignmentnotenum_in,
        null as offsessionid_ru,
        offreporttype_ru as offreporttype_ru,
        null as packingslipidforupdate_w,
        null as docregister_lt,
        null as fiscaldocumentseries_br,
        null as fiscaldocumentmodel_br,
        fiscaldocumentspecie_br as fiscaldocumentspecie_br,
        fiscaldocumenttype_br as fiscaldocumenttype_br,
        reasontableref_br as reasontableref_br,
        servicecodeondlvaddress_br as servicecodeondlvaddress_br,
        stornophysical_ru as stornophysical_ru,
        vendfinaluser_br as vendfinaluser_br,
        vendpackingslipjour as vendpackingslipjour,
        presencetype_br as presencetype_br,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        createdby as createdby,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid
    from d365_source

)

select *
from renamed
