with d365_source as (

    select *
    from {{ source("D365S", "purchparmline") }}
    where
        _fivetran_deleted = 'FALSE'
        and upper(trim(dataareaid)) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
),

renamed as (
    select
        'D365S' as source,
        remainbeforeinvent as remainbeforeinvent,
        remainafterinvent as remainafterinvent,
        inventnow as inventnow,
        remainafter as remainafter,
        remainbefore as remainbefore,
        receivenow as receivenow,
        linenum as linenum,
        itemid as itemid,
        deliveryname as deliveryname,
        linepercent as linepercent,
        purchmarkup as purchmarkup,
        priceunit as priceunit,
        multilndisc as multilndisc,
        linedisc as linedisc,
        purchprice as purchprice,
        multilnpercent as multilnpercent,
        lineamount as lineamount,
        orderaccount as orderaccount,
        purchlinerecid as purchlinerecid,
        invoiceaccount as invoiceaccount,
        parmid as parmid,
        closed as closed,
        changedmanually as changedmanually,
        currencycode as currencycode,
        inventtransid as inventtransid,
        inventdimid as inventdimid,
        origpurchid as origpurchid,
        null as invoiceinfotablerefid,
        tablerefid as tablerefid,
        tax_1099_amount as tax1099amount,
        null as tax1099state,
        tax_1099_stateamount as tax1099stateamount,
        null as taxitemgroup,
        null as taxgroup,
        null as description,
        reasontableref as reasontableref,
        procurementcategory as procurementcategory,
        remainbeforeinventphysical as remainbeforeinventphysical,
        tax_1099_fields as tax1099fields,
        deliverypostaladdress as deliverypostaladdress,
        purchaselinelinenumber as purchaselinelinenumber,
        previousreceivenow as previousreceivenow,
        previousinventnow as previousinventnow,
        null as postingprofile_ru,
        inventprofiletype_ru as inventprofiletype_ru,
        null as customsimportinvoicenumtbl_in,
        null as customsbillofentrynumtbl_in,
        null as receivedqty_in,
        null as acceptedqty_in,
        null as rejectedqty_in,
        null as assessablevalue_in,
        null as maximumretailprice_in,
        null as customsinvoiceregnrecid_in,
        deviationqty_ru as deviationqty_ru,
        cfoptable_br as cfoptable_br,
        null as pdscountryoforigin1,
        null as pdscountryoforigin2,
        pdscwpreviousreceivenow as pdscwpreviousreceivenow,
        pdscwreceivenow as pdscwreceivenow,
        pdscwremainafterinvent as pdscwremainafterinvent,
        pdscwremainbeforeinvent as pdscwremainbeforeinvent,
        pdsusevendbatchdate as pdsusevendbatchdate,
        pdsusevendbatchexp as pdsusevendbatchexp,
        cast(pdsvendbatchdate as TIMESTAMP_NTZ) as pdsvendbatchdate,
        null as pdsvendbatchid,
        cast(pdsvendexpirydate as TIMESTAMP_NTZ) as pdsvendexpirydate,
        previousdeviationqty as previousdeviationqty,
        null as taxservicecode_br,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid
    from d365_source
)

select *
from renamed
