
with d365source as (

    select *
    from {{ source("D365S", "custtrans") }}
    where
        upper(trim(dataareaid)) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
        and _fivetran_deleted = 'FALSE'

),

renamed as (


    select
        'D365S' as source,
        accountnum as accountnum,
        cast(transdate as TIMESTAMP_NTZ) as transdate,
        voucher as voucher,
        invoice as invoice,
        txt as txt,
        amountcur as amountcur,
        settleamountcur as settleamountcur,
        amountmst as amountmst,
        settleamountmst as settleamountmst,
        currencycode as currencycode,
        cast(duedate as TIMESTAMP_NTZ) as duedate,
        lastsettlevoucher as lastsettlevoucher,
        cast(lastsettledate as TIMESTAMP_NTZ) as lastsettledate,
        null as lastexchadjvoucher,
        cast(closed as TIMESTAMP_NTZ) as closed,
        transtype as transtype,
        approved as approved,
        exchadjustment as exchadjustment,
        null as documentnum,
        cast(documentdate as TIMESTAMP_NTZ) as documentdate,
        lastexchadjrate as lastexchadjrate,
        fixedexchrate as fixedexchrate,
        cast(lastexchadj as TIMESTAMP_NTZ) as lastexchadj,
        correct as correct,
        null as bankcentralbankpurposecode,
        null as bankcentralbankpurposetext,
        settlement as settlement,
        interest as interest,
        collectionletter as collectionletter,
        defaultdimension as defaultdimension,
        null as postingprofileclose,
        exchratesecond as exchratesecond,
        banklcexportline as banklcexportline,
        accountingevent as accountingevent,
        exchrate as exchrate,
        lastsettleaccountnum as lastsettleaccountnum,
        companybankaccountid as companybankaccountid,
        null as thirdpartybankaccountid,
        paymmode as paymmode,
        paymreference as paymreference,
        paymmethod as paymmethod,
        cashpayment as cashpayment,
        null as controlnum,
        deliverymode as deliverymode,
        postingprofile as postingprofile,
        offsetrecid as offsetrecid,
        eurotriangulation as eurotriangulation,
        orderaccount as orderaccount,
        null as cashdisccode,
        prepayment as prepayment,
        null as paymspec,
        custexchadjustmentrealized as custexchadjustmentrealized,
        custexchadjustmentunrealized as custexchadjustmentunrealized,
        null as paymmanlackdate,
        null as paymmanbatch,
        null as paymid,
        null as billofexchangeid,
        billofexchangestatus as billofexchangestatus,
        billofexchangeseqnum as billofexchangeseqnum,
        null as bankremittancefileid,
        collectionlettercode as collectionlettercode,
        invoiceproject as invoiceproject,
        lastsettlecompany as lastsettlecompany,
        cancelledpayment as cancelledpayment,
        reasonrefrecid as reasonrefrecid,
        reportingcurrencyamount as reportingcurrencyamount,
        null as reportingexchadjustmentreal,
        null as reportingexchadjustmentunreal,
        lastexchadjratereporting as lastexchadjratereporting,
        reportingcurrencycrossrate as reportingcurrencycrossrate,
        exchadjustmentreporting as exchadjustmentreporting,
        settleamountreporting as settleamountreporting,
        approver as approver,
        null as taxinvoicesalesid,
        null as concessioncontractid,
        null as concessionsettlementid,
        retailcusttrans as retailcusttrans,
        null as retailstoreid,
        null as retailterminalid,
        null as retailtransactionid,
        custbillingclassification as custbillingclassification,
        mcrpaymorderid as mcrpaymorderid,
        directdebitmandate as directdebitmandate,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        modifiedtransactionid as modifiedtransactionid,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        createdtransactionid as createdtransactionid,
        upper(trim(dataareaid)) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        null as paymschedid
    from d365source

)

select *
from renamed
