
with d365_source as (
    select *
    from {{ source("D365S", "custinvoicejour") }}
    where
        trim(upper(dataareaid)) in {{ env_var("DBT_D365_COMPANY_FILTER") }}
        and _fivetran_deleted = 'FALSE'
),

renamed as (
    select
        'D365S' as source,
        custgroup as custgroup,
        refnum as refnum,
        salesid as salesid,
        orderaccount as orderaccount,
        invoiceaccount as invoiceaccount,
        cast(invoicedate as TIMESTAMP_NTZ) as invoicedate,
        cast(duedate as TIMESTAMP_NTZ) as duedate,
        cashdisc as cashdisc,
        cast(cashdiscdate as TIMESTAMP_NTZ) as cashdiscdate,
        qty as qty,
        volume as volume,
        weight as weight,
        sumlinedisc as sumlinedisc,
        salesbalance as salesbalance,
        enddisc as enddisc,
        invoiceamount as invoiceamount,
        currencycode as currencycode,
        exchrate as exchrate,
        invoiceid as invoiceid,
        ledgervoucher as ledgervoucher,
        updated as updated,
        onaccountamount as onaccountamount,
        taxprintoninvoice as taxprintoninvoice,
        listcode as listcode,
        null as documentnum,
        cast(documentdate as TIMESTAMP_NTZ) as documentdate,
        cashdiscpercent as cashdiscpercent,
        null as intrastatdispatch,
        deliveryname as deliveryname,
        null as enterprisenumber,
        purchaseorder as purchaseorder,
        dlvterm as dlvterm,
        dlvmode as dlvmode,
        payment as payment,
        null as cashdisccode,
        invoiceroundoff as invoiceroundoff,
        summarkup as summarkup,
        covstatus as covstatus,
        returnitemnum as returnitemnum,
        postingprofile as postingprofile,
        backorder as backorder,
        prepayment as prepayment,
        taxgroup as taxgroup,
        null as taxitemgroup,
        taxspecifybyline as taxspecifybyline,
        einvoicelinespecific as einvoicelinespecific,
        onetimecustomer as onetimecustomer,
        null as paymentsched,
        sumtax as sumtax,
        salestype as salestype,
        null as einvoiceaccountcode,
        intercompanyposted as intercompanyposted,
        parmid as parmid,
        returnreasoncodeid as returnreasoncodeid,
        eusaleslist as eusaleslist,
        exchratesecondary as exchratesecondary,
        triangulation as triangulation,
        customerref as customerref,
        vatnum as vatnum,
        null as numbersequencegroup,
        languageid as languageid,
        incltax as incltax,
        null as log,
        null as paymdayid,
        invoicingname as invoicingname,
        girotype as girotype,
        null as contactpersonid,
        salesoriginid as salesoriginid,
        null as billofladingid,
        inventlocationid as inventlocationid,
        cast(fixedduedate as TIMESTAMP_NTZ) as fixedduedate,
        invoiceamountmst as invoiceamountmst,
        invoiceroundoffmst as invoiceroundoffmst,
        summarkupmst as summarkupmst,
        sumlinediscmst as sumlinediscmst,
        enddiscmst as enddiscmst,
        salesbalancemst as salesbalancemst,
        sumtaxmst as sumtaxmst,
        printmgmtsiteid as printmgmtsiteid,
        returnstatus as returnstatus,
        null as intercompanycompanyid,
        null as intercompanypurchid,
        printedoriginals as printedoriginals,
        proforma as proforma,
        null as rcsaleslist_uk,
        null as reversecharge_uk,
        deliverypostaladdress as deliverypostaladdress,
        invoicepostaladdress as invoicepostaladdress,
        sourcedocumentheader as sourcedocumentheader,
        defaultdimension as defaultdimension,
        banklcexportline as banklcexportline,
        workersalestaker as workersalestaker,
        reversedrecid as reversedrecid,
        cast(receiptdateconfirmed_es as TIMESTAMP_NTZ)
            as receiptdateconfirmed_es,
        null as paymid,
        null as taxinvoicesalesid,
        cast(intrastatfulfillmentdate_hu as TIMESTAMP_NTZ)
            as intrastatfulfillmentdate_hu,
        mcremail as mcremail,
        mcrpaymamount as mcrpaymamount,
        mcrdueamount as mcrdueamount,
        cast(cashdiscbasedate as TIMESTAMP_NTZ) as cashdiscbasedate,
        directdebitmandate as directdebitmandate,
        iscorrection as iscorrection,
        reasontableref as reasontableref,
        sourcedocumentline as sourcedocumentline,
        transportationdocument as transportationdocument,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        upper(trim(dataareaid)) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        null as bisediprocess,
        provisionalassessment_in as provisionalassessment_in,
        null as invoiceidentification_in
    from d365_source

)

select * from renamed

