with d365_source as (
        select *
        from {{ source("D365S", "projtable") }} where _FIVETRAN_DELETED='FALSE'
    ),

    renamed as (

       
        select
            'D365S' as source,
            projgroupid as projgroupid,
            projid as projid,
            name as name,
            projledgerposting as projledgerposting,
            cast(created as TIMESTAMP_NTZ) as created,
            cast(startdate as TIMESTAMP_NTZ) as startdate,
            cast(enddate as TIMESTAMP_NTZ) as enddate,
            custaccount as custaccount,
            dlvname as dlvname,
            projinvoiceprojid as projinvoiceprojid,
            email as email,
            null as parentid,
            header as header,
            taxgroupid as taxgroupid,
            format as format,
            checkbudget as checkbudget,
            null as sortingid,
            null as sortingid2_,
            null as sortingid3_,
            null as synclasttransid,
            status as status,
            wipproject as wipproject,
            type as type,
            template as template,
            validateprojcategory as validateprojcategory,
            projlinepropertysearch as projlinepropertysearch,             
            deliverylocation as deliverylocation,             
            defaultdimension as defaultdimension,
            null as subject_sa,
            cast(contractdate_sa as TIMESTAMP_NTZ) as contractdate_sa,
            contractvalue_sa as contractvalue_sa,
            contractamendment_sa as contractamendment_sa,
            null as contractperiod_sa,
            requireactivityhourtrx as requireactivityhourtrx,
            requireactivityexpensetrx as requireactivityexpensetrx,
            requireactivityitemtrx as requireactivityitemtrx,
            requireactivityhourforecast as requireactivityhourforecast,
            requireactivityexpenseforecast as requireactivityexpenseforecast,
            requireactivityitemforecast as requireactivityitemforecast,
            usebudgeting as usebudgeting,
            usealternateproject as usealternateproject,
            projpricegroup as projpricegroup,
            projbudgetoverrunoption as projbudgetoverrunoption,
            null as syncentityid,
            null as syncversion,
            projbudgetarycontrolon as projbudgetarycontrolon,
            null as synccreatedbyexternal,
            null as assetid,
            cast(projectedstartdate as TIMESTAMP_NTZ) as projectedstartdate,
            cast(projectedenddate as TIMESTAMP_NTZ) as projectedenddate,
            cast(extensiondate as TIMESTAMP_NTZ) as extensiondate,
            null as alternatebudgetproject,
            projbudgetinterval as projbudgetinterval,
            timepostdetailsummary as timepostdetailsummary,
            mintimeincrement as mintimeincrement,
            projcarryforwardremainingbudget as projcarryforwardremainingbudget,
            projcarryforwardnegativebudget as projcarryforwardnegativebudget,             
            workerresponsiblefinancial as workerresponsiblefinancial,             
            workerresponsible as workerresponsible,             
            workerresponsiblesales as workerresponsiblesales,
            bankdocumenttype as bankdocumenttype,
            jobid as jobid,
            jobpaytype as jobpaytype,
            null as psaprojtask,
            null as psaunitid,
            null as psatimemeasure,
            null as psatrackcost,
            null as psaforecastmodelid,
            psainvoicemethod as psainvoicemethod,
            null as psareadyforinvoicing,
            psadoinvoicecost as psadoinvoicecost,
            null as psanotes,
            psaprojstatus as psaprojstatus,
            null as psaforecastmodelidexternal,
            null as psaphone,
            null as psatelefax,
            null as psapreqitemvalidate,
            null as psapreqhourvalidate,
            null as psapreqcontrol,
            psaschedmilestone as psaschedmilestone,
            cast(psaschedstartdate as TIMESTAMP_NTZ) as psaschedstartdate,
            cast(psaschedenddate as TIMESTAMP_NTZ) as psaschedenddate,
            psaschedduration as psaschedduration,
            psascheduseduration as psascheduseduration,
            psaschedcalendarid as psaschedcalendarid,
            psaschedignorecalendar as psaschedignorecalendar,
            null as psaschedconstrainttype,
            null as psaschedconstraintdate,
            psaschedscheduled as psaschedscheduled,
            null as psaretainscheduleid,
            null as psaretainpercent,
            null as psaretainincludelower,
            psaschedeffort as psaschedeffort,
            psaschedfromtime as psaschedfromtime,
            psaschedtotime as psaschedtotime,
            null as psascheddefaultdate,
            psaresschedstatus as psaresschedstatus,
            completescheduled as completescheduled,
            ocip as ocip,
            certifiedpayroll as certifiedpayroll,
            ocipgl as ocipgl,
            workerpsaarchitect as workerpsaarchitect,
            projbudgetmanagement as projbudgetmanagement,
            null as synctocrm,
            cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
            upper(dataareaid) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid
        from d365_source where upper(dataareaid) in {{env_var("DBT_D365_COMPANY_FILTER")}}

    )

select * from renamed
