with d365source as (
    select *
    from {{ source("D365S", "salestable") }}
    where
        _fivetran_deleted = 'FALSE'
        and upper(dataareaid) in {{ env_var("DBT_D365_COMPANY_FILTER") }}


),

renamed as (
    select
        'D365S' as source,
        salesid as salesid,
        salesname as salesname,
        reservation as reservation,
        custaccount as custaccount,
        invoiceaccount as invoiceaccount,
        cast(deliverydate as TIMESTAMP_NTZ) as deliverydate,
        null as url,
        purchorderformnum as purchorderformnum,
        null as salesgroup,
        freightsliptype as freightsliptype,
        documentstatus as documentstatus,
        null as intercompanyoriginalsalesid,
        currencycode as currencycode,
        payment as payment,
        null as cashdisc,
        taxgroup as taxgroup,
        linedisc as linedisc,
        custgroup as custgroup,
        discpercent as discpercent,
        null as intercooriginalcustaccount,
        pricegroupid as pricegroupid,
        null as multilinedisc,
        null as enddisc,
        cast(customerref as VARCHAR(255)) as customerref,
        null as countyorigdest,
        listcode as listcode,
        dlvterm as dlvterm,
        dlvmode as dlvmode,
        null as purchid,
        salesstatus as salesstatus,
        markupgroup as markupgroup,
        salestype as salestype,
        null as salespoolid,
        postingprofile as postingprofile,
        null as transactioncode,
        intercompanyautocreateorders as intercompanyautocreateorders,
        intercompanydirectdelivery as intercompanydirectdelivery,
        intercompanydirectdeliveryorig as intercompanydirectdeliveryorig,
        settlevoucher as settlevoucher,
        null as enterprisenumber,
        intercompanyallowindirectcreation as intercoallowindirectcreation,
        intercompanyallowindirectcreationorig as intercoallowindirectcreatorig,
        deliveryname as deliveryname,
        onetimecustomer as onetimecustomer,
        covstatus as covstatus,
        null as commissiongroup,
        null as paymentsched,
        intercompanyorigin as intercompanyorigin,
        email as email,
        null as freightzone,
        returnitemnum as returnitemnum,
        cashdiscpercent as cashdiscpercent,
        null as contactpersonid,
        cast(deadline as TIMESTAMP_NTZ) as deadline,
        null as projid,
        inventlocationid as inventlocationid,
        addressreftableid as addressreftableid,
        vatnum as vatnum,
        null as port,
        incltax as incltax,
        einvoicelinespec as einvoicelinespec,
        null as numbersequencegroup,
        fixedexchrate as fixedexchrate,
        languageid as languageid,
        autosummarymoduletype as autosummarymoduletype,
        girotype as girotype,
        salesoriginid as salesoriginid,
        estimate as estimate,
        null as transport,
        paymmode as paymmode,
        null as paymspec,
        cast(fixedduedate as TIMESTAMP_NTZ) as fixedduedate,
        null as exportreason,
        null as statprocid,
        null as bankcentralbankpurposetext,
        intercompanycompanyid as intercompanycompanyid,
        intercompanypurchid as intercompanypurchid,
        intercompanyorder as intercompanyorder,
        null as dlvreason,
        null as quotationid,
        cast(receiptdaterequested as TIMESTAMP_NTZ) as receiptdaterequested,
        cast(receiptdateconfirmed as TIMESTAMP_NTZ) as receiptdateconfirmed,
        cast(shippingdaterequested as TIMESTAMP_NTZ) as shippingdaterequested,
        cast(shippingdateconfirmed as TIMESTAMP_NTZ) as shippingdateconfirmed,
        null as bankcentralbankpurposecode,
        null as einvoiceaccountcode,
        itemtagging as itemtagging,
        casetagging as casetagging,
        pallettagging as pallettagging,
        addressrefrecid as addressrefrecid,
        null as custinvoiceid,
        inventsiteid as inventsiteid,
        defaultdimension as defaultdimension,
        creditcardcustrefid as creditcardcustrefid,
        null as shipcarrieraccount,
        null as shipcarrierid,
        null as shipcarrierfuelsurcharge,
        shipcarrierblindshipment as shipcarrierblindshipment,
        null as shipcarrierdeliverycontact,
        creditcardapprovalamount as creditcardapprovalamount,
        null as creditcardauthorization,
        cast(returndeadline as TIMESTAMP_NTZ) as returndeadline,
        null as returnreplacementid,
        returnstatus as returnstatus,
        returnreasoncodeid as returnreasoncodeid,
        creditcardauthorizationerror as creditcardauthorizationerror,
        null as shipcarrieraccountcode,
        returnreplacementcreated as returnreplacementcreated,
        shipcarrierdlvtype as shipcarrierdlvtype,
        deliverydatecontroltype as deliverydatecontroltype,
        null as shipcarrierexpeditedshipment,
        shipcarrierresidential as shipcarrierresidential,
        matchingagreement as matchingagreement,
        systementrysource as systementrysource,
        systementrychangepolicy as systementrychangepolicy,
        manualentrychangepolicy as manualentrychangepolicy,
        deliverypostaladdress as deliverypostaladdress,
        shipcarrierpostaladdress as shipcarrierpostaladdress,
        null as shipcarriername,
        workersalestaker as workersalestaker,
        sourcedocumentheader as sourcedocumentheader,
        bankdocumenttype as bankdocumenttype,
        null as salesunitid,
        smmsalesamounttotal as smmsalesamounttotal,
        null as smmcampaignid,
        customsexportorder_in as customsexportorder_in,
        customsshippingbill_in as customsshippingbill_in,
        null as tdsgroup_in,
        null as tcsgroup_in,
        natureofassessee_in as natureofassessee_in,
        constarget_jp as constarget_jp,
        cast(intrastatfulfillmentdate_hu as TIMESTAMP_NTZ)
            as intrastatfulfillmentdate_hu,
        unitedvatinvoice_lt as unitedvatinvoice_lt,
        intrastataddvalue_lv as intrastataddvalue_lv,
        invoiceautonumbering_lt as invoiceregister_lt,
        packingslipautonumbering_lt as packingslipregister_lt,
        null as bankaccount_lv,
        cast(cashdiscbasedate as TIMESTAMP_NTZ) as cashdiscbasedate,
        cashdiscbasedays as cashdiscbasedays,
        creditnotereasoncode as creditnotereasoncode,
        null as curbankaccount_lv,
        null as custbankaccount_lv,
        null as daxintegrationid,
        directdebitmandate as directdebitmandate,
        fiscaldoctype_pl as fiscaldoctype_pl,
        mcrorderstopped as mcrorderstopped,
        pdsbatchattribautores as pdsbatchattribautores,
        null as pdscustrebategroupid,
        null as pdsrebateprogramtmagroup,
        releasestatus as releasestatus,
        null as taxperiodpaymentcode_pl,
        transportationdocument as transportationdocument,
        workersalesresponsible as workersalesresponsible,
        cast(modifieddatetime as TIMESTAMP_NTZ) as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        modifiedtransactionid as modifiedtransactionid,
        cast(createddatetime as TIMESTAMP_NTZ) as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        createdtransactionid as createdtransactionid,
        upper(dataareaid) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid,
        cast(wbxaccountnumber as VARCHAR(255)) as wbxaccountnumber,
        null as wbxcancelreasoncode,
        null as wbxcontractnumber,
        wbxcontractorindicator as wbxcontractorindicator,
        wbxedideliveryinstructions as wbxdeliveryinstruction,
        null as wbxfullpallet,
        wbxoneproductperpallet as wbxoneproductperpallet,
        null as wbxordercreationtype,
        wbxrequestedreceipttime as wbxrequestedreceipttime,
        cast(wbxsenddateandtime as TIMESTAMP_NTZ) as wbxsenddatetime,
        --wbxsenddateandtimetzid as wbxsenddatetimetzid,
        null as wbxshelflife,
        null as wbxshelflifecheckneeded,
        wbxorderwaved as wbxwaved,
        wbxpodrequired as wbxpodrequired,
        null as wbxtotalsoqtydisc,
        null as wbxadditionaldisc,
        null as bisediconfirmation,
        null as bisedidelivery,
        null as bisediinvoice,
        null as bisedireturn,
        null as bisedipicking,
        retailchanneltable as retailchanneltable,
        null as ecommerceoperator_in,
        null as ecommerceoperatorgstin_in,
        null as ecommercesale_in,
        null as merchantid_in,
        null as provisionalassessment_in,
        null as allowzeropriceapprovedby,
        null as allowzeropriceapproveddate,
        null as allowzeroprices,
        null as pricecalculated,
        null as einvoicecfdiconfirmnumber_mx,
        null as satpaymmethod_mx,
        null as satpurpose_mx
    from d365source

)

select * from renamed
