with BH as(
select * from {{ ref('src_bank_holidays') }}
),

Date as(
   select * from {{ ref('src_dim_date') }} 
),

wbx as(
   select * from {{ ref('src_wbix_tbldimdate') }} 
),

calendar_flags as (                                   
select DAYNAME(CALENDAR_DATE) AS DAYS,
CALENDAR_DATE,
case when DAYNAME(CALENDAR_DATE) in('Sat','Sun') then 0 else 1 end as weekday_flag,
CASE WHEN BH.DATE IS NULL OR DAYNAME(BH.DATE) IN ('Sat','Sun')  THEN 0 ELSE 1 END AS Holiday_flag,
case when DAYNAME(CALENDAR_DATE) in('Sat','Sun') OR BH.DATE IS NOT NULL then 0 else 1 end as business_day_flag
from date LEFT JOIN 
BH ON BH.DATE=TO_DATE(CALENDAR_DATE)
),

business_calendar_fields as (
select calendar_date, days as day_of_week, weekday_flag,
holiday_flag, DATE_PART('day',CALENDAR_DATE) AS DAYS_IN_MONTH_TO_DATE,
sum(business_day_flag) over (PARTITION BY date_trunc('month',calendar_flags.calendar_date)) as BUSINESS_DAYS_IN_MONTH,
sum(business_day_flag) over (PARTITION BY date_trunc('month',calendar_flags.calendar_date) order by calendar_date rows between unbounded preceding and current row) as DAY_OF_MONTH_BUSINESS
FROM calendar_flags
),

STG as
(
select 100000 + (DATE_PART('year',DD_DATETIME)-2000) + (DD_WBXYEARDAYNUMBER) as FISCAL_DATE_ID,
DD_FYPERIOD as FISCAL_PERIOD_NO,
DD_FYYYYYPP as FISCAL_YEAR_PERIOD_NO,
DD_PLANYYYYQQ as FISCAL_PERIOD_DESC, 
DATE_TRUNC('month',DD_DATETIME) as FISCAL_PERIOD_BEGIN_DT,
DATEADD('day',-1,DATE_TRUNC('month',DATEADD('month',1,DD_DATETIME))) as FISCAL_PERIOD_END_DT,
DD_FYQTRINT as FISCAL_YEAR_QUARTER_NO,
DD_FYYYYYQX as FISCAL_QUARTER_DESC,
MIN(DD_DATETIME) OVER (PARTITION BY DD_FYQTRINT) AS FISCAL_QUARTER_START_DT,
MAX(DD_DATETIME) OVER (PARTITION BY DD_FYQTRINT) AS FISCAL_QUARTER_END_DT,
DD_FY as FISCAL_YEAR,
MIN(DD_DATETIME) OVER (PARTITION BY DD_FY) AS FISCAL_YEAR_BEGIN_DT,
MAX(DD_DATETIME) OVER (PARTITION BY DD_FY) AS FISCAL_YEAR_END_DT,
DD_SUNTOSAT as FISCAL_YEAR_WEEK_NO,
100000 + (DATE_PART('year',DD_DATETIME)-2000) + (DD_WBXYEARDAYNUMBER) as CALENDAR_DATE_ID,
DD_DDMMYYYY as  CALENDAR_DATE,
decode(upper(DD_DDD),'MON','Monday','TUE','Tuesday','WED','Wednesday','THU','Thursday','FRI','Friday','SAT','Saturday','SUN','Sunday') as calendar_day_of_week  ,
DD_CY as CALENDAR_YEAR,
DATE_TRUNC('year',DD_DATETIME) as CALENDAR_YEAR_BEGIN_DT,
DATEADD('day',-1,DATE_TRUNC('year',DATEADD('year',1,DD_DATETIME))) as CALENDAR_YEAR_END_DT,
DD_QUARTERINT as CALENDAR_YEAR_QUARTER_NO,
DD_YYYYQX as CALENDAR_QUARTER_DESC,
MIN(DD_DATETIME) OVER (PARTITION BY DD_QUARTERINT) AS CALENDAR_QUARTER_START_DT,
MAX(DD_DATETIME) OVER (PARTITION BY DD_QUARTERINT) AS CALENDAR_QUARTER_END_DT,
DD_MONTHINT as CALENDAR_YEAR_MONTH_NO,
DATE_PART('month',DD_DATETIME) as CALENDAR_MONTH_NO,
DD_MONTHFULLDESC as CALENDAR_MONTH_NAME,
DD_WBXPERIODNAME as CALENDAR_MONTH_DESC,
DATE_TRUNC('month',DD_DATETIME) as CALENDAR_MONTH_START_DT,
DATEADD('day',-1,DATE_TRUNC('month',DATEADD('month',1,DD_DATETIME))) as CALENDAR_MONTH_END_DT,
((DD_CY * 100) + DD_CYWEEKNUM )as CALENDAR_YEAR_WEEK_NO,
DD_STARTDATEOFWEEK as CALENDAR_WEEK_BEGIN_DT,
DD_ENDOFDATEWEEK as CALENDAR_WEEK_END_DT,
 NULL as CALENDAR_BUSINESS_DAY_FLAG,
'DATABIXDWH' as SOURCE_IND,
CURRENT_DATE as LOAD_DATE ,  
CURRENT_DATE as UPDATE_DATE,
NULL AS REPORT_FISCAL_YEAR_PERIOD_NO,
NULL AS REPORT_FISCAL_YEAR,
'{{env_var("DBT_SOURCE_SYSTEM")}}' AS SOURCE_SYSTEM,
DD_PLANPERIODNAME ||  ' ' || DD_PLANYEAR AS OC_PERIOD_NAME,
DD_PLANYEAR AS OC_FISCAL_YEAR,
DD_PLANPERIOD AS OC_FISCAL_PERIOD_NO,
((DD_PLANYEAR * 100) + DD_PLANPERIOD ) AS  OC_FISCAL_YEAR_PERIOD_NO,
NULL AS OC_FISCAL_PERIOD_DESC,
MIN(DD_DATETIME) OVER (PARTITION BY (DD_PLANYEAR * 100) + DD_PLANPERIOD) AS OC_FISCAL_PERIOD_BEGIN_DT,
MAX(DD_DATETIME) OVER (PARTITION BY (DD_PLANYEAR * 100) + DD_PLANPERIOD) AS OC_FISCAL_PERIOD_END_DT,
BCF.HOLIDAY_FLAG AS UK_HOLIDAY_FLAG,
BCF.DAY_OF_MONTH_BUSINESS as DAY_OF_MONTH_BUSINESS,
BCF.DAYS_IN_MONTH_TO_DATE AS DAY_OF_MONTH_ACTUAL
FROM  wbx
LEFT JOIN business_calendar_fields BCF on DD_DDMMYYYY=BCF.calendar_Date WHERE SOURCE_SYSTEM='{{env_var("DBT_SOURCE_SYSTEM")}}' 
group by 
DD_DDMMYYYY,
DD_DATETIME,
DD_FYQTRINT,
DD_FY,
DD_QUARTERINT,
DD_PLANYEAR,
DD_PLANPERIOD,
DD_WBXYEARDAYNUMBER,
DD_FYPERIOD,
DD_FYYYYYPP,
DD_PLANYYYYQQ,
DD_FYYYYYQX,
DD_SUNTOSAT,
DD_DDD,DD_CY,
DD_YYYYQX,
DD_MONTHINT,
DD_MONTHFULLDESC,
DD_WBXPERIODNAME,
DD_CYWEEKNUM,
DD_STARTDATEOFWEEK,
DD_ENDOFDATEWEEK,
DD_PLANPERIODNAME,
BCF.HOLIDAY_FLAG, 
BCF.DAY_OF_MONTH_BUSINESS, 
BCF.DAYS_IN_MONTH_TO_DATE
order by DD_DDMMYYYY
)


select * from STG