{{
    config(
        tags=["inventory", "item_cost","inv_item_cost"]
    )
}}
 




with ID as 
(
select * from {{ref('src_inventdim')}}
),

IIP1 as 
(
    select * from {{ref('src_inventitemprice')}}
),

ITO as(
   select * from {{ref('src_inventtransorigin')}} 
),

IT as(
    select * from {{ref('src_inventtrans')}}
),

plant as(
    select * from {{ref('dim_wbx_plant_dc')}}
),

L as (
    select * from {{ref('src_ledger')}}
),
BU as(
    SELECT SOURCE_BUSINESS_UNIT_CODE, PLANTDC_ADDRESS_GUID AS BU_GUID, 
    CONSOLIDATED_SHIPMENT_DC_NAME AS SITE FROM 
    plant WHERE TYPE = 'WAREHOUSE'
),

Date as(
    select * from {{ref('src_dim_date')}}
),

COMBO_FILTER as(
    SELECT 
    DISTINCT UPPER(TRIM(IT.ITEMID)) AS ITEMID, 
    UPPER(TRIM(ID.INVENTLOCATIONID)) AS INVENTLOCATIONID
    FROM IT
    INNER JOIN ITO  ON IT.INVENTTRANSORIGIN = ITO.RECID
    INNER JOIN ID ON IT.INVENTDIMID = ID.INVENTDIMID
),

IIP as(
    SELECT DISTINCT 
    IIP1.PARTITION, 
    IIP1.DATAAREAID, 
    IIP1.ITEMID, 
    BU.SOURCE_BUSINESS_UNIT_CODE, 
    IIP1.PRICEUNIT, 
    IIP1.PRICE, 
    IIP1.MODIFIEDDATETIME,
    CASE WHEN SUBSTR(TRIM(IIP1.ITEMID),1,1)='P' and  trim(INVENTSIZEID)<>'' then trim(INVENTSIZEID) else '-' end as VARIANT_CODE
    from IIP1
    INNER JOIN ID
    ON IIP1.INVENTDIMID = ID.INVENTDIMID
    INNER JOIN  BU ON BU.SITE = UPPER(TRIM(ID.INVENTSITEID)) WHERE IIP1.PRICETYPE = 0
    ),

    B as(
        SELECT CALENDAR_DATE, CALENDAR_DATE_ID FROM DATE WHERE TO_DATE(CALENDAR_DATE) = TO_DATE(CONVERT_TIMEZONE('UTC',current_timestamp))
    ),

IIP_MAX as (
SELECT 
IIP1.PARTITION,
IIP1.DATAAREAID, 
IIP1.ITEMID, 
BU.SOURCE_BUSINESS_UNIT_CODE, 
MAX(IIP1.MODIFIEDDATETIME) AS MAX_ACT_DATE,
CASE  WHEN SUBSTR(TRIM(IIP1.ITEMID),1,1)='P' and  trim(INVENTSIZEID)<>'' then trim(INVENTSIZEID) else '-' end as VARIANT_CODE
FROM  IIP1
INNER JOIN ID ON IIP1.INVENTDIMID = ID.INVENTDIMID
INNER JOIN  BU ON BU.SITE = UPPER(TRIM(ID.INVENTSITEID))
WHERE IIP1.PRICETYPE = 0 
GROUP BY IIP1.PARTITION, IIP1.DATAAREAID, IIP1.ITEMID, BU.SOURCE_BUSINESS_UNIT_CODE,
CASE WHEN SUBSTR(TRIM(IIP1.ITEMID),1,1)='P' and  trim(INVENTSIZEID)<>'' then trim(INVENTSIZEID) else '-' end
),


Final as (
select 
'{{env_var("DBT_SOURCE_SYSTEM")}}'  AS SOURCE_SYSTEM
, TRIM(IIP.ITEMID) AS SOURCE_ITEM_IDENTIFIER
, IIP.SOURCE_BUSINESS_UNIT_CODE AS SOURCE_BUSINESS_UNIT_CODE
, '-' AS SOURCE_LOCATION_CODE
, '-' AS SOURCE_LOT_CODE
, '07' AS SOURCE_COST_METHOD_CODE
, IIP.PRICE / (CASE WHEN IIP.PRICEUNIT = 0 THEN 1 ELSE IIP.PRICEUNIT END) AS ITEM_UNIT_COST
, to_date(B.CALENDAR_DATE) AS EFF_DATE
, to_date('31-DEC-2050','DD-MON-YYYY') AS EXPIR_DATE
,to_date(IIP.MODIFIEDDATETIME) AS SOURCE_UPDATED_DATETIME
, L.ACCOUNTINGCURRENCY AS TRANSACTION_CURRENCY
,IIP.VARIANT_CODE

FROM 
IIP
INNER JOIN  L ON TRIM(UPPER(IIP.DATAAREAID)) = TRIM(UPPER(L.NAME))
INNER JOIN B ON 1=1
INNER JOIN COMBO_FILTER ON COMBO_FILTER.ITEMID = TRIM(IIP.ITEMID) AND COMBO_FILTER.INVENTLOCATIONID = IIP.SOURCE_BUSINESS_UNIT_CODE
INNER JOIN IIP_MAX ON IIP.PARTITION = IIP_MAX.PARTITION
AND UPPER(TRIM(IIP.DATAAREAID)) = UPPER(TRIM(IIP_MAX.DATAAREAID))
AND TRIM(IIP.ITEMID) = TRIM(IIP_MAX.ITEMID)
AND IIP.SOURCE_BUSINESS_UNIT_CODE = IIP_MAX.SOURCE_BUSINESS_UNIT_CODE
AND IIP.MODIFIEDDATETIME = IIP_MAX.MAX_ACT_DATE
AND IIP.VARIANT_CODE = IIP_MAX.VARIANT_CODE
)

select * from final