with DATAAREA as
(
    select * from {{ref('src_dataarea')}}
),

INVSITE as
(
    select * from {{ref('src_inventsite')}}
),

INVLOC as
(
    select * from {{ref('src_inventlocation')}}
),

INVLOCLOGLOC as
(
    select * from {{ref('src_inventlocationlogisticsloc')}}
),

LOGPOSTADD as
(
    select * from {{ref('src_logisticspostaladdress')}} WHERE CURRENT_TIMESTAMP BETWEEN VALIDFROM AND VALIDTO
),

LPA as
(
    SELECT ILLL.INVENTLOCATION, LPA1.* FROM INVLOCLOGLOC ILLL INNER JOIN LOGPOSTADD LPA1 ON ILLL.LOCATION = LPA1.LOCATION
),

DIMFINTAG as(
    select * from {{ref('src_dimensionfinancialtag')}}
),

DIRPARTAB as
(
    select * from {{ref('src_dirpartytable')}}
),

PART1_UNION as (
SELECT 
'{{env_var("DBT_SOURCE_SYSTEM")}}' AS SOURCE_SYSTEM,
UPPER (TRIM (SI.SITEID))        AS SOURCE_SYSTEM_ADDRESS_NUMBER,
UPPER (TRIM (SI.SITEID))        AS BUSINESS_UNIT,
SI.NAME                         AS BUSINESS_UNIT_NAME,
'SITE'                          AS TYPE,
UPPER (TRIM (TO_CHAR (DA.ID)))  AS PLAN_COMPANY,
'PHI'                           AS REGION,
'WEETABIX'                      AS SEGMENT ,
'-'                             AS REPRESENTATIVE_NAME,
'Y'                             AS ACTIVE_CC_FLAG,
NULL                            AS CONSOLIDATED_SHIPMENT_DC_NAME,
CAST (NULL AS VARCHAR2 (255))   AS ADDRESS_LINE_1,
CAST (NULL AS VARCHAR2 (255))   AS CITY,
CAST (NULL AS VARCHAR2 (255))   AS STATE_PROVINCE_CODE,
CAST (NULL AS VARCHAR2 (255))   AS STATE_PROVINCE,
CAST (NULL AS VARCHAR2 (255))   AS POSTAL_CODE,
CAST (NULL AS VARCHAR2 (255))   AS COUNTRY_CODE,
CAST (NULL AS VARCHAR2 (255))   AS COUNTRY,
CAST (NULL AS VARCHAR2 (255))   AS COUNTY,
'WEETABIX'                      AS OPERATING_COMPANY     
FROM INVSITE SI
inner join DATAAREA DA WHERE UPPER (TRIM (SI.DATAAREAID)) = UPPER (TRIM (DA.ID))
),

PART2_UNION as (
SELECT 
'{{env_var("DBT_SOURCE_SYSTEM")}}'       AS SOURCE_SYSTEM,
UPPER (TRIM (IL.INVENTLOCATIONID))       AS SOURCE_SYSTEM_ADDRESS_NUMBER,
UPPER (TRIM (IL.INVENTLOCATIONID))       AS BUSINESS_UNIT,
IL.NAME                                  AS BUSINESS_UNIT_NAME,
'WAREHOUSE'                              AS TYPE,
UPPER (TRIM (TO_CHAR (IL.DATAAREAID)))   AS PLAN_COMPANY,
'PHI'                                    AS REGION,
'WEETABIX'                               AS SEGMENT,
'-'                                      AS REPRESENTATIVE_NAME,
'Y'                                      AS ACTIVE_CC_FLAG,
IL.INVENTSITEID                          AS CONSOLIDATED_SHIPMENT_DC_NAME,    
CAST (LPA.STREET AS VARCHAR2 (255))      AS ADDRESS_LINE_1,
CAST (LPA.CITY AS VARCHAR2 (255))        AS CITY,
CAST (LPA.STATE AS VARCHAR2 (255))       AS STATE_PROVINCE_CODE,
CAST (LPA.STATE AS VARCHAR2 (255))       AS STATE_PROVINCE,
CAST (LPA.ZIPCODE AS VARCHAR2 (255))     AS POSTAL_CODE,
CAST (LPA.COUNTRYREGIONID AS VARCHAR2 (255)) AS COUNTRY_CODE,
CAST (LPA.COUNTRYREGIONID AS VARCHAR2 (255)) AS COUNTRY,
CAST (LPA.COUNTY AS VARCHAR2 (255))          AS COUNTY,
'WEETABIX'                                   AS OPERATING_COMPANY
FROM INVLOC IL 
INNER JOIN DATAAREA DA ON UPPER (TRIM (IL.DATAAREAID)) = UPPER (TRIM (DA.ID)) 
LEFT JOIN LPA ON IL.RECID = LPA.INVENTLOCATION  where UPPER(TRIM(IL.INVENTLOCATIONID)) not in (select distinct UPPER(TRIM(SITEID)) FROM INVSITE )
-- Filter added to Load only 1 IRE value  20-11-2020
),

PART3_UNION as 
(
SELECT 
'{{env_var("DBT_SOURCE_SYSTEM")}}'      AS SOURCE_SYSTEM,
UPPER (TRIM (CC.OMOPERATINGUNITNUMBER)) AS SOURCE_SYSTEM_ADDRESS_NUMBER,
UPPER (TRIM (CC.OMOPERATINGUNITNUMBER)) AS BUSINESS_UNIT,
CC.NAME                                 AS BUSINESS_UNIT_NAME,
'COST CENTER'                           AS TYPE,
 NULL                                   AS PLAN_COMPANY,
'PHI'                                   AS REGION,
'WEETABIX'                              AS SEGMENT,
'-'                                     AS REPRESENTATIVE_NAME,
'Y'                                     AS ACTIVE_CC_FLAG,
NULL                                    AS CONSOLIDATED_SHIPMENT_DC_NAME,
CAST (NULL AS VARCHAR2 (255))           AS ADDRESS_LINE_1,
CAST (NULL AS VARCHAR2 (255))           AS CITY,
CAST (NULL AS VARCHAR2 (255))           AS STATE_PROVINCE_CODE,
CAST (NULL AS VARCHAR2 (255))           AS STATE_PROVINCE,
CAST (NULL AS VARCHAR2 (255))           AS POSTAL_CODE,
CAST (NULL AS VARCHAR2 (255))           AS COUNTRY_CODE,
CAST (NULL AS VARCHAR2 (255))           AS COUNTRY,
CAST (NULL AS VARCHAR2 (255))           AS COUNTY,
'WEETABIX' AS OPERATING_COMPANY FROM DIRPARTAB CC WHERE CC.INSTANCERELATIONTYPE = 2377 AND CC.OMOPERATINGUNITTYPE = '2'
),

PART4_UNION as
(
SELECT 
'{{env_var("DBT_SOURCE_SYSTEM")}}' AS SOURCE_SYSTEM,
UPPER (RTRIM (VALUE))              AS SOURCE_SYSTEM_ADDRESS_NUMBER,
UPPER (RTRIM (VALUE))              AS BUSINESS_UNIT,
DESCRIPTION                        AS BUSINESS_UNIT_NAME,
'SITE'                             AS TYPE,
'WBX'                              AS PLAN_COMPANY, --No Ashton (Ryecroft) in results from this query so all records are ""WBX""
'PHI'                              AS REGION,
'WEETABIX'                         AS SEGMENT, --No Ashton (Ryecroft) in results from this query so all records are ""WBX-BL"" or ""WBX-CBY'
'-'                                AS REPRESENTATIVE_NAME,
'Y'                                AS ACTIVE_CC_FLAG,
NULL                               AS CONSOLIDATED_SHIPMENT_DC_NAME,
CAST (NULL AS VARCHAR2 (255))      AS ADDRESS_LINE_1,
CAST (NULL AS VARCHAR2 (255))      AS CITY,
CAST (NULL AS VARCHAR2 (255))      AS STATE_PROVINCE_CODE,
CAST (NULL AS VARCHAR2 (255))      AS STATE_PROVINCE,
CAST (NULL AS VARCHAR2 (255))      AS POSTAL_CODE,
CAST (NULL AS VARCHAR2 (255))      AS COUNTRY_CODE,
CAST (NULL AS VARCHAR2 (255))      AS COUNTRY,
CAST (NULL AS VARCHAR2 (255))      AS COUNTY,
'WEETABIX'                         AS OPERATING_COMPANY
FROM DIMFINTAG WHERE FINANCIALTAGCATEGORY = 5637144577 
AND UPPER (TRIM (VALUE)) NOT IN (SELECT UPPER (TRIM (INVENTLOCATIONID)) FROM INVLOC)
AND UPPER (TRIM (VALUE)) NOT IN (SELECT UPPER (TRIM (SITEID)) FROM INVSITE)
),


PRE_FINAL as(

    select * from PART1_UNION
    union all
    select * from PART2_UNION
    union all
    select * from PART3_UNION
    union all
    select * from PART4_UNION
),

FINAL as (
    select
	SOURCE_SYSTEM,
	SOURCE_SYSTEM_ADDRESS_NUMBER,
	BUSINESS_UNIT,
	BUSINESS_UNIT_NAME,
	TYPE,
	PLAN_COMPANY,
	CASE WHEN PLAN_COMPANY IN('RFL','RFL-ASH') THEN 'RYECROFT FOODS LIMITED' WHEN PLAN_COMPANY='IBE' 
         then 'WEETABIX IBERICA SL' ELSE 'WEETABIX LIMITED' END AS PLAN_COMPANY_NAME,
	REGION,
	SEGMENT,
	REPRESENTATIVE_NAME,
	ACTIVE_CC_FLAG,
	CONSOLIDATED_SHIPMENT_DC_NAME,
	ADDRESS_LINE_1,
	CITY,
	STATE_PROVINCE_CODE,
	STATE_PROVINCE,
	POSTAL_CODE,
	COUNTRY_CODE,
	COUNTRY,
	COUNTY,
	OPERATING_COMPANY from PRE_FINAL
)

select * from FINAL