with IB as
(
    select * from {{ref('src_inventbatch')}} 
),

IT as(
     select * from {{ref('src_inventtrans')}}
),

ID as (
    select * from {{ref('src_inventdim')}}
),

ITO as (
    select * from {{ref('src_inventtransorigin')}}  
),

ITM_MAS as 
(
select * from {{ref('dim_wbx_item')}}  
),


COMBO as(
SELECT DISTINCT 
IT.DATAAREAID,
ID.INVENTBATCHID,
IT.ITEMID,
ID.INVENTLOCATIONID
FROM  IT
INNER JOIN ITO ON IT.INVENTTRANSORIGIN = ITO.RECID
INNER JOIN ID  ON IT.INVENTDIMID = ID.INVENTDIMID
),

IB_DERIVED as
(
SELECT INVENTBATCHID,
ITEMID,
DATAAREAID,
CAST (DESCRIPTION AS VARCHAR2 (255)) AS DESCRIPTION,
MAX (PDSDISPOSITIONCODE)           AS PDSDISPOSITIONCODE,
MAX (PDSVENDBATCHID)               AS PDSVENDBATCHID,
MAX (EXPDATE)                      AS EXPDATE,
MAX (PRODDATE)                     AS PRODDATE,
MAX (PDSBESTBEFOREDATE)            AS PDSBESTBEFOREDATE
FROM IB GROUP BY 
INVENTBATCHID,
ITEMID,
DATAAREAID,
CAST (DESCRIPTION AS VARCHAR2 (255))
),

Stg as
(
SELECT DISTINCT
'{{env_var("DBT_SOURCE_SYSTEM")}}'      AS SOURCE_SYSTEM,
UPPER (TRIM (COMBO.INVENTBATCHID))      AS SOURCE_LOT_CODE,
COMBO.ITEMID                            AS SOURCE_ITEM_IDENTIFIER,
UPPER (TRIM (COMBO.INVENTLOCATIONID))   AS SOURCE_BUSINESS_UNIT_CODE,
CAST (IB_DERIVED.DESCRIPTION AS VARCHAR2 (255)) AS LOT_DESC,
SUBSTR (IB_DERIVED.PDSDISPOSITIONCODE, 1, 2)    AS LOT_STATUS_CODE,
IB_DERIVED.PDSDISPOSITIONCODE                   AS LOT_STATUS_DESC,
'N'                                     AS QUARANTINE_FLAG,
IB_DERIVED.PDSVENDBATCHID                       AS SUPPLIER_LOT_CODE,
NULL                                    AS SOURCE_SUPPLIER_CODE_PRIMARY,
TO_DATE (IB_DERIVED.EXPDATE)                    AS LOT_EXPIRATION_DATE,
TO_DATE (IB_DERIVED.PRODDATE)                   AS LOT_ONHAND_DATE,
TO_DATE (IB_DERIVED.PDSBESTBEFOREDATE)          AS LOT_SELLBY_DATE,
DATEDIFF(DAY, TO_DATE (IB_DERIVED.PRODDATE), TO_DATE(CONVERT_TIMEZONE('UTC',current_timestamp)))   AS LOT_AGE_DAYS,
CASE WHEN TO_DATE (IB_DERIVED.EXPDATE) > TO_DATE(CONVERT_TIMEZONE('UTC',current_timestamp)) THEN 'N' ELSE 'Y' END AS LOT_EXPIRED_FLAG

FROM COMBO
LEFT JOIN IB_DERIVED on UPPER (TRIM (COMBO.DATAAREAID)) =UPPER (TRIM (IB_DERIVED.DATAAREAID))
AND UPPER (TRIM (COMBO.ITEMID)) = UPPER (TRIM (IB_DERIVED.ITEMID))
AND UPPER (TRIM (COMBO.INVENTBATCHID)) =UPPER (TRIM (IB_DERIVED.INVENTBATCHID))
WHERE TRIM (COMBO.INVENTLOCATIONID) IS NOT NULL AND TRIM (COMBO.INVENTBATCHID) IS NOT NULL
),


Final as(
    
select
NVL(NULLIF(TRIM(STG.SOURCE_BUSINESS_UNIT_CODE),''),'-')    AS SOURCE_BUSINESS_UNIT_CODE,
NVL(NULLIF(RTRIM(STG.SOURCE_LOT_CODE),''),'-')              AS SOURCE_LOT_CODE,
NVL(NULLIF(TRIM(STG.LOT_DESC),''),'-')    AS LOT_DESC,
NVL(NULLIF(TRIM(STG.LOT_STATUS_CODE),''),'-')    AS LOT_STATUS_CODE,
NVL(NULLIF(TRIM(STG.LOT_STATUS_DESC),''),'-')    AS LOT_STATUS_DESC,
NVL(NULLIF(TRIM(STG.QUARANTINE_FLAG),''),'-')    AS QUARANTINE_FLAG,
NVL(NULLIF(TRIM(STG.SUPPLIER_LOT_CODE),''),'-')    AS SUPPLIER_LOT_CODE,
NVL(NULLIF(TRIM(STG.SOURCE_SUPPLIER_CODE_PRIMARY),''),'-')    AS SOURCE_SUPPLIER_CODE_PRIMARY,
NVL(NULLIF(TRIM(STG.LOT_EXPIRED_FLAG),''),'-')    AS LOT_EXPIRED_FLAG,
NVL(NULLIF(TRIM(STG.SOURCE_ITEM_IDENTIFIER),''),'-')    AS SOURCE_ITEM_IDENTIFIER,
LOT_EXPIRATION_DATE,
LOT_ONHAND_DATE,
LOT_SELLBY_DATE,
LOT_AGE_DAYS,
SOURCE_SYSTEM,
'PLANT_DC'   AS GENERIC_ADDRESS_TYPE,
CURRENT_DATE as load_date,
CURRENT_DATE as update_date
from stg   
)


Select distinct
	SOURCE_LOT_CODE,
	SOURCE_ITEM_IDENTIFIER,
	SOURCE_BUSINESS_UNIT_CODE,
	SOURCE_SYSTEM,
	LOT_DESC,
	LOT_STATUS_CODE,
	LOT_STATUS_DESC,
	QUARANTINE_FLAG,
	SUPPLIER_LOT_CODE,
	SOURCE_SUPPLIER_CODE_PRIMARY,
	LOT_EXPIRATION_DATE,
	LOT_ONHAND_DATE,
	LOT_SELLBY_DATE,
	LOT_AGE_DAYS,
	LOT_EXPIRED_FLAG,
    GENERIC_ADDRESS_TYPE,
    load_date,
    update_date

    from final


