with ER as(
    select * from {{ref('src_exchangerate')}}
),

ERCP as(
    select * from {{ref('src_exchangeratecurrencypair')}}
),

ERT as(
    select * from {{ref('src_exchangeratetype')}}
),

A_FEED as(
SELECT 
ERCP.FROMCURRENCYCODE,
ERCP.TOCURRENCYCODE,
TO_DECIMAL(ER.EXCHANGERATE,20,7) / TO_DECIMAL(100,20,7) AS EXCHANGERATE,
TO_DECIMAL(100,20,7) / TO_DECIMAL(ER.EXCHANGERATE,20,7) AS EXCHANGERATE_I,
CASE WHEN ER.VALIDFROM < '01-JAN-2000'THEN TO_DATE ('01-JAN-2000','DD-MON-YYYY')
ELSE ER.VALIDFROM END AS VALIDFROM,
ER.VALIDTO
FROM ER,
ERCP,
ERT
WHERE  ER.EXCHANGERATECURRENCYPAIR =ERCP.RECID AND ERCP.EXCHANGERATETYPE = ERT.RECID AND ERT.NAME = 'Default'),

A as(
SELECT 
FROMCURRENCYCODE,
TOCURRENCYCODE,
EXCHANGERATE,
EXCHANGERATE_I,
VALIDFROM AS EFFECTIVE_DT_ID,
VALIDFROM AS EFFECTIVE_DT,
VALIDTO AS EXPIRATION_DT_ID,
VALIDTO AS EXPIRATION_DT
FROM A_FEED 
GROUP BY FROMCURRENCYCODE,
TOCURRENCYCODE,
EXCHANGERATE,
EXCHANGERATE_I,
VALIDFROM,
VALIDTO
),

B_FEED as
(
SELECT FROMCURRENCYCODE,
TOCURRENCYCODE,
MIN (VALIDFROM) AS mn_dt
FROM (
SELECT ERCP.FROMCURRENCYCODE,
ERCP.TOCURRENCYCODE,
TO_DECIMAL(ER.EXCHANGERATE,20,7) / TO_DECIMAL(100,20,7) AS EXCHANGERATE,
TO_DECIMAL(100,20,7) / TO_DECIMAL(ER.EXCHANGERATE,20,7) AS EXCHANGERATE_I,
CASE WHEN ER.VALIDFROM < '01-JAN-2000'
THEN TO_DATE ('01-JAN-2000',
'DD-MON-YYYY') ELSE ER.VALIDFROM END AS VALIDFROM,
ER.VALIDTO FROM ER,
 ERCP,
ERT
WHERE     ER.EXCHANGERATECURRENCYPAIR =ERCP.RECID
AND ERCP.EXCHANGERATETYPE = ERT.RECID
AND ERT.NAME = 'Default' 
)
GROUP BY FROMCURRENCYCODE, TOCURRENCYCODE
),

DT as(
    SELECT CURRENT_DATE - SEQ4() + 1 AS fill_dt
FROM TABLE(GENERATOR(ROWCOUNT => 10000)) WHERE CURRENT_DATE - SEQ4() + 1 >= '01-JAN-2000'
),

B as(
SELECT FROMCURRENCYCODE, TOCURRENCYCODE, fill_dt
FROM B_FEED,
dt WHERE fill_dt >= mn_dt
),




Final as(
select
    CURR_FROM_CODE,
	CURR_TO_CODE,
	CURR_CONV_RT,
	CURR_CONV_RT_I,
	EFF_D_ID,
	EFF_FROM_D,
	EXPIR_D_ID,
	EXPIR_TO_D,
	ROLLFWD_ROW
    from(
SELECT 
TRIM (b.FROMCURRENCYCODE)     CURR_FROM_CODE,
TRIM (b.TOCURRENCYCODE)              CURR_TO_CODE,
TO_DECIMAL (TRIM (SUBSTR (MAX (DECODE ( EXCHANGERATE, NULL, NULL, TO_CHAR ( TO_CHAR (fill_dt, 'YYYYMMDD') || EXCHANGERATE)))
OVER ( PARTITION BY B.FROMCURRENCYCODE, B.TOCURRENCYCODE ORDER BY fill_dt), 9)),20,7)  as CURR_CONV_RT,
TO_DECIMAL (TRIM (SUBSTR (MAX (DECODE ( EXCHANGERATE_I, NULL, NULL, TO_CHAR ( TO_CHAR (fill_dt, 'YYYYMMDD') || EXCHANGERATE_I)))
OVER ( PARTITION BY B.FROMCURRENCYCODE, B.TOCURRENCYCODE ORDER BY fill_dt), 9)),20,7) as CURR_CONV_RT_I,
TO_DECIMAL (1 || TO_CHAR (fill_dt, 'YY') || LPAD(DAYOFYEAR(fill_dt),3,'0') ) AS EFF_D_ID,
fill_dt  as EFF_FROM_D,
TO_DECIMAL (1 || TO_CHAR (fill_dt, 'YY') || LPAD(DAYOFYEAR(fill_dt),3,'0') ) AS EXPIR_D_ID,
fill_dt  as  EXPIR_TO_D,
CASE WHEN TO_DECIMAL (TRIM (SUBSTR (
MAX ( DECODE ( EXCHANGERATE, NULL, NULL, TO_CHAR ( TO_CHAR (fill_dt, 'YYYYMMDD') || EXCHANGERATE)))
OVER (PARTITION BY B.FROMCURRENCYCODE, B.TOCURRENCYCODE ORDER BY fill_dt), 1, 8))) = TO_CHAR (fill_dt, 'YYYYMMDD')
THEN NULL ELSE 'Y' END AS ROLLFWD_ROW
FROM
A,B 
WHERE b.fill_dt = a.EFFECTIVE_DT(+)
AND b.FROMCURRENCYCODE = a.FROMCURRENCYCODE(+)
AND b.TOCURRENCYCODE = a.TOCURRENCYCODE(+)
ORDER BY b.FROMCURRENCYCODE, b.TOCURRENCYCODE, b.fill_dt)
)

select * from final
       
       

    