with d365_source as (
        select *
        from {{ source("D365", "prod_table") }} where _FIVETRAN_DELETED='FALSE' AND upper(data_area_id) in {{env_var("DBT_D365_COMPANY_FILTER")}}

    ),

    renamed as (
        select
            'D365' as source,
            proj_linked_to_order as projlinkedtoorder,
            item_id as itemid,
            name as name,
            null as prodgroupid,
            prod_status as prodstatus,
            prod_prio as prodprio,
            prod_locked as prodlocked,
            prod_type as prodtype,
            sched_status as schedstatus,
            sched_date as scheddate,
            qty_sched as qtysched,
            qty_st_up as qtystup,
            dlv_date as dlvdate,
            st_up_date as stupdate,
            finished_date as finisheddate,
            sched_start as schedstart,
            sched_end as schedend,
            default_dimension as defaultdimension,
            height as height,
            width as width,
            depth as depth,
            density as density,
            qty_calc as qtycalc,
            real_date as realdate,
            reservation as reservation,
            prod_posting_type as prodpostingtype,
            invent_trans_id as inventtransid,
            invent_ref_type as inventreftype,
            null as inventrefid,
            null as inventreftransid,
            collect_ref_level as collectreflevel,
            collect_ref_prod_id as collectrefprodid,
            bomdate as bomdate,
            backorder_status as backorderstatus,
            null as prodpoolid,
            profit_set as profitset,
            calc_date as calcdate,
            route_jobs as routejobs,
            check_route as checkroute,
            null as propertyid,
            remain_invent_physical as remaininventphysical,
            bomid as bomid,
            route_id as routeid,
            req_plan_id_sched as reqplanidsched,
            req_poid as reqpoid,
            ref_look_up as reflookup,
            latest_sched_direction as latestscheddirection,
            latest_sched_date as latestscheddate,
            prod_id as prodid,
            invent_dim_id as inventdimid,
            sched_to_time as schedtotime,
            sched_from_time as schedfromtime,
            latest_sched_time as latestschedtime,
            dlv_time as dlvtime,
            null as prodorigid,
            gantt_color_id as ganttcolorid,
            null as projid,
            proj_posting_type as projpostingtype,
            null as projcategoryid,
            null as projlinepropertyid,
            null as projtransid,
            proj_cost_price as projcostprice,
            proj_cost_amount as projcostamount,
            null as projsalescurrencyid,
            null as projsalesunitid,
            proj_sales_price as projsalesprice,
            null as projtaxgroupid,
            null as projtaxitemgroupid,
            null as activitynumber,
            null as pricegroup_ru,
            null as currencycode_ru,
            null as pbaid,
            pmf_total_cost_allocation as pmftotalcostallocation,
            pds_cwbatch_est as pdscwbatchest,
            pds_cwbatch_sched as pdscwbatchsched,
            pds_cwbatch_size as pdscwbatchsize,
            pds_cwbatch_stup as pdscwbatchstup,
            pds_cwremain_invent_physical as pdscwremaininventphysical,
            pmf_bulk_ord as pmfbulkord,
            pmf_co_by_var_allow as pmfcobyvarallow,
            pmf_cons_ord_id as pmfconsordid,
            pmf_rework_batch as pmfreworkbatch,
            pmf_yield_pct as pmfyieldpct,
            prod_whsrelease_policy as prodwhsreleasepolicy,
            released_date as releaseddate,
            createddatetime as createddatetime,
            null as del_createdtime,
            createdby as createdby,
            upper(data_area_id) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid,
            null as prodimported,
            null as qtymade,
            null as statuschangedby

        from d365_source

    )

select * from renamed
