with source as (

    select * from {{ source('WEETABIX', 'EXC_Dim_Promotion_Statuses') }}

),

renamed as (

    select
STATUS_IDX,
STATUS_CODE,
STATUS_NAME,
STATUS_COLOUR,
STATUS_DESCRIPTION,
STATUS_SORT,
INCLUDEINLIVESCENARIO,
INCLUDEINUSERSCENARIO,
CREATEEVENTFORTHISSTATUS,
VERB,
AMENDABLE,
ISINFLIGHTTABAMENDABLE,
ISUSERCREATED,
ISENABLED,
INCLUDEINDPSQLUPLIFTMODEL,
MAINTAINBASE,
MAINTAINCALCSRC,
ISSTATUSAPPROVEDORABOVE,
ATTACHFUNDATTHISSTATUS,
FUNDREQUIREDFORTHISSTATUS,
INCLUDEINFUNDAPPROVED,
ISSTATUSCONFIRMEDORABOVE,
INCLUDEINFUNDDRAWN

    from source

)

select * from renamed