with
    d365_source as (
        select *
        from {{ source("D365", "invent_location") }} where _FIVETRAN_DELETED='FALSE' and upper(trim(data_area_id)) in {{env_var("DBT_D365_COMPANY_FILTER")}} 
    ),

    renamed as (

        select
            'D365' as source,
            invent_location_id as inventlocationid,
            name as name,
            manual as manual,
            null as emptypalletlocation,
            maxpickingroutevolume as maxpickingroutevolume,
            pickinglinetime as pickinglinetime,
            maxpickingroutetime as maxpickingroutetime,
            wmslocation_id_default_receipt as wmslocationiddefaultreceipt,
            wmslocation_id_default_issue as wmslocationiddefaultissue,
            null as inventlocationidreqmain,
            req_refill as reqrefill,
            invent_location_type as inventlocationtype,
            null as inventlocationidquarantine,
            invent_location_level as inventlocationlevel,
            null as reqcalendarid,
            wmsaisle_name_active as wmsaislenameactive,
            wmsrack_name_active as wmsracknameactive,
            null as wmsrackformat,
            wmslevel_name_active as wmslevelnameactive,
            null as wmslevelformat,
            wmsposition_name_active as wmspositionnameactive,
            null as wmspositionformat,
            usewmsorders as usewmsorders,
            invent_location_id_transit as inventlocationidtransit,
            null as vendaccount,
            null as branchnumber,
            invent_site_id as inventsiteid,
            invent_counting_group_br as inventcountinggroup_br,
            null as custaccount_br,
            invent_profile_type_ru as inventprofiletype_ru,
            null as inventprofileid_ru,
            null as inventlocidgoodsinroute_ru,
            null as wmslocidgoodsinroute_ru,
            null as activitytype_ru,
            null as numbersequencegroup_ru,
            retail_weight_ex_1 as retailweightex1,
            fshstore as fshstore,
            null as rbodefaultwmspalletid,
            null as rbodefaultwmslocationid,
            null as rbodefaultinventprofileid_ru,
            allow_labor_standards as allowlaborstandards,
            allow_marking_reservation_removal as allowmarkingreservationremoval,
            consolidateshipatrtw as consolidateshipatrtw,
            null as custaccount_hu,
            cycle_count_allow_pallet_move as cyclecountallowpalletmove,
            decrement_load_line as decrementloadline,
            null as dfltkanbanfinishedgoodsloc,
            DEFAULT_PRODUCTION_FINISH_GOODS_LOCATION as dfltproductionfinishgoodsloc,
            null as defaultshipmaintenanceloc,
            default_status_id as defaultstatusid,
            print_bolbefore_ship_confirm as printbolbeforeshipconfirm,
            prod_reserve_only_whse as prodreserveonlywhse,
            null as removeinventblockonstatchange,
            reserve_at_load_post as reserveatloadpost,
            retail_invent_neg_financial as retailinventnegfinancial,
            retail_invent_neg_physical as retailinventnegphysical,
            null as retailwmslociddefaultreturn,
            null as retailwmspalletiddfltreturn,
            unique_check_digits as uniquecheckdigits,
            null as vendaccountcustom_ru,
            null as warehouseautoreleaseres,
            whsenabled as whsenabled,
            null as defaultproductioninputloc,
            null as defaultreturncreditonlyloc,
            modifieddatetime as modifieddatetime,
            null as del_modifiedtime,
            modifiedby as modifiedby,
            createddatetime as createddatetime,
            null as del_createdtime,
            createdby as createdby,
            upper(data_area_id) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid,
            null as wbxtooutbound,
            null as wbxproposedefaultvariant,
            whsraw_material_policy as whsrawmaterialpolicy,
            null as wbxinventlocationid,
            null as wbxinventsiteid,
            null as wbxwmstransferenabled,
            null as biseancodeid,
            null as defaultcontainertypecode,
            null as defaultshipdirectlocation,
            null as includedemandforecast

        from d365_source

    )

select *
from renamed
