
with d365_source as (

        select *
        from {{ source("D365", "cust_trans") }} where upper(trim(data_area_id)) in {{env_var("DBT_D365_COMPANY_FILTER")}} and _FIVETRAN_DELETED='FALSE'
     
    ),

    renamed as (

        
        select
            'D365' as source,
            account_num as accountnum,
            trans_date as transdate,
            voucher as voucher,
            invoice as invoice,
            txt as txt,
            amount_cur as amountcur,
            settle_amount_cur as settleamountcur,
            amount_mst as amountmst,
            settle_amount_mst as settleamountmst,
            currency_code as currencycode,
            due_date as duedate,
            last_settle_voucher as lastsettlevoucher,
            last_settle_date as lastsettledate,
            null as lastexchadjvoucher,
            closed as closed,
            trans_type as transtype,
            approved as approved,
            exch_adjustment as exchadjustment,
            null as documentnum,
            document_date as documentdate,
            last_exch_adj_rate as lastexchadjrate,
            fixed_exch_rate as fixedexchrate,
            last_exch_adj as lastexchadj,
            correct as correct,
            null as bankcentralbankpurposecode,
            null as bankcentralbankpurposetext,
            settlement as settlement,
            interest as interest,
            collection_letter as collectionletter,
            default_dimension  as defaultdimension,
            null as postingprofileclose,
            exch_rate_second as exchratesecond,
            bank_lcexport_line as banklcexportline,
            accounting_event  as accountingevent,
            exch_rate as exchrate,
            last_settle_account_num as lastsettleaccountnum,
            company_bank_account_id as companybankaccountid,
            null as thirdpartybankaccountid,
            paym_mode as paymmode,
            paym_reference  as paymreference,
            paym_method as paymmethod,
            cash_payment as cashpayment,
            null as controlnum,
            delivery_mode as deliverymode,
            posting_profile as postingprofile,
            offset_recid   as offsetrecid,
            eurotriangulation as eurotriangulation,
            order_account as orderaccount,
            null as cashdisccode,
            prepayment as prepayment,
            null as paymspec,
            cust_exch_adjustment_realized as custexchadjustmentrealized,
            cust_exch_adjustment_unrealized as custexchadjustmentunrealized,
            null as paymmanlackdate,
            null as paymmanbatch,
            null as paymid,
            null as billofexchangeid,
            bill_of_exchange_status as billofexchangestatus,
            bill_of_exchange_seq_num as billofexchangeseqnum,
            null as bankremittancefileid,
            collection_letter_code as collectionlettercode,
            invoiceproject as invoiceproject,
            last_settle_company as lastsettlecompany,
            cancelled_payment as cancelledpayment,
            reason_ref_rec_id as reasonrefrecid,
            reporting_currency_amount as reportingcurrencyamount,
            null as reportingexchadjustmentreal,
            null as reportingexchadjustmentunreal,
            last_exch_adj_rate_reporting as lastexchadjratereporting,
            reporting_currency_cross_rate as reportingcurrencycrossrate,
            exch_adjustment_reporting as exchadjustmentreporting,
            settle_amount_reporting as settleamountreporting,
            approver as approver,
            null as taxinvoicesalesid,
            null as concessioncontractid,
            null as concessionsettlementid,
            retail_cust_trans as retailcusttrans,
            null as retailstoreid,
            null as retailterminalid,
            null as retailtransactionid,
            cust_billing_classification as custbillingclassification,
            mcrpaym_order_id as mcrpaymorderid,
            direct_debit_mandate as directdebitmandate,
            modifieddatetime as modifieddatetime,
            null as del_modifiedtime,
            modifiedby as modifiedby,
            modifiedtransactionid  as modifiedtransactionid,
            createddatetime as createddatetime,
            null as del_createdtime,
            createdby as createdby,
            createdtransactionid as createdtransactionid,
            upper(trim(data_area_id)) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid,
            null as paymschedid
        from d365_source

    )

select *
from renamed
