with
    d365_source as (
        select *
        from {{ source("D365", "cust_packing_slip_trans") }}
         where trim(upper(data_area_id)) in {{env_var("DBT_D365_COMPANY_FILTER")}} and _FIVETRAN_DELETED='FALSE' 
    ),
renamed as (
    select 
        'D365' as source,
        packing_slip_id as packingslipid,
        delivery_date as deliverydate,
        line_num as linenum,
        invent_trans_id as inventtransid,
        item_id as itemid,
        null as externalitemid,
        name as name,
        ordered as ordered,
        qty as qty,
        remain as remain,
        null as salesgroup,
        price_unit as priceunit,
        value_mst as valuemst,
        sales_id as salesid,
        sales_unit as salesunit,
        null as transactioncode,
        null as transport,
        country_region_of_shipment as countryregionofshipment,
        invent_ref_id as inventrefid,
        orig_sales_id as origsalesid,
        line_header as lineheader,
        invent_dim_id as inventdimid,
        null as statprocid,
        null as port,
        null as numbersequencegroup,
        null as intercompanyinventtransid,
        remain_invent as remaininvent,
        scrap as scrap,
        stat_value_mst as statvaluemst,
        null as intrastatdispatchid,
        invent_qty as inventqty,
        invent_ref_trans_id as inventreftransid,
        delivery_type as deliverytype,
        invent_ref_type as inventreftype,
        sales_category as salescategory,
        null as itemcodeid,
        null as origcountryregionid,
        null as origstateid,
        weight as weight,
        delivery_postal_address   as deliverypostaladdress,
        default_dimension  as defaultdimension,
        sales_line_shipping_date_requested as saleslineshippingdaterequested,
        sales_line_shipping_date_confirmed as saleslineshippingdateconfirmed,
        source_document_line  as sourcedocumentline,
        fully_matched as fullymatched,
        stocked_product as stockedproduct,
        ngpcodes_table_fr as ngpcodestable_fr,
        invoice_trans_ref_rec_id as invoicetransrefrecid,
        intrastat_fulfillment_date_hu as intrastatfulfillmentdate_hu,
        statistic_value_lt as statisticvalue_lt,
        amount_cur as amountcur,
        null as currencycode,
        dlv_term as dlvterm,
        pds_cwqty as pdscwqty,
        pds_cwremain as pdscwremain,
        createddatetime as createddatetime,
        null as del_createdtime,
        upper(data_area_id) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid
    from d365_source

)

select * from renamed
