with d365_source as (
        select *
        from {{ source("D365", "vend_trans") }} where _FIVETRAN_DELETED='FALSE' and upper(data_area_id) in {{env_var("DBT_D365_COMPANY_FILTER")}}
    ),

renamed as (
    select
        'D365' as source,
        account_num as accountnum,
        trans_date as transdate,
        voucher as voucher,
        invoice as invoice,
        txt as txt,
        amount_cur as amountcur,
        settle_amount_cur as settleamountcur,
        amount_mst as amountmst,
        settle_amount_mst as settleamountmst,
        currency_code as currencycode,
        due_date as duedate,
        last_settle_voucher as lastsettlevoucher,
        last_settle_date as lastsettledate,
        closed as closed,
        trans_type as transtype,
        approved as approved,
        paym_term_id as paymid,   --field fixed
        exch_adjustment as exchadjustment,
        null as documentnum,
        document_date as documentdate,
        arrival as arrival,
        last_exch_adj as lastexchadj,
        correct as correct,
        null as lastexchadjvoucher,
        last_exch_adj_rate as lastexchadjrate,
        posting_profile as postingprofile,
        settlement as settlement,
        cancel as cancel,
        null as postingprofileclose,
        null as postingprofileapprove,
        null as postingprofilecancel,
        null as postingprofilereopen,
        null as thirdpartybankaccountid,
        company_bank_account_id as companybankaccountid,
        null as paymreference,
        paym_mode as paymmode,
        tax_1099_date as tax1099date,
        tax_1099_amount as tax1099amount,
        null as tax1099num,
        offset_recid as offsetrecid,
        journal_num as journalnum,
        eurotriangulation as eurotriangulation,
        null as cashdisccode,
        prepayment as prepayment,
        null as paymspec,
        vend_exch_adjustment_realized as vendexchadjustmentrealized,
        vend_exch_adjustment_unrealized as vendexchadjustmentunrealized,
        approved_date as approveddate,
        null as promissorynoteid,
        promissory_note_status as promissorynotestatus,
        promissory_note_seq_num as promissorynoteseqnum,
        null as bankremittancefileid,
        fixed_exch_rate as fixedexchrate,
        null as bankcentralbankpurposetext,
        null as bankcentralbankpurposecode,
        null as tax1099state,
        tax_1099_state_amount as tax1099stateamount,
        settle_tax_1099_amount as settletax1099amount,
        settle_tax_1099_state_amount as settletax1099stateamount,
        default_dimension as defaultdimension,
        exch_rate_second as exchratesecond,
        exch_rate as exchrate,
        last_settle_account_num as lastsettleaccountnum,
        last_settle_company as lastsettlecompany,
        invoice_project as invoiceproject,
        reason_ref_rec_id as reasonrefrecid,
        null as releasedatecomment,
        invoice_release_date as invoicereleasedate,
        invoicereleasedatetzid as invoicereleasedatetzid,
        null as vendpaymentgroup,
        remittance_location as remittancelocation,
        remittance_address as remittanceaddress,
        tax_1099_fields as tax1099fields,
        bank_lcimport_line as banklcimportline,
        accounting_event as accountingevent,
        APPROVER as approver,
        reporting_currency_amount as reportingcurrencyamount,
        reporting_exch_adjustment_realized as reportingexchadjustmentrlzed,        --field fixed
        reporting_exch_adjustment_unrealized as reportingexchadjustmentunrlzed,    --field fixed
        last_exch_adj_rate_reporting as lastexchadjratereporting,
        reporting_currency_cross_rate as reportingcurrencycrossrate,
        exch_adjustment_reporting as exchadjustmentreporting,
        settle_amount_reporting as settleamountreporting,
        null as taxinvoicepurchid,
        tax_1099_rec_id as tax1099recid,
        null as consessionsettlementid,
        rbovend_trans as rbovendtrans,
        modifieddatetime as modifieddatetime,
        null as del_modifiedtime,
        modifiedby as modifiedby,
        modifiedtransactionid as modifiedtransactionid,
        createddatetime as createddatetime,
        null as del_createdtime,
        createdby as createdby,
        createdtransactionid as createdtransactionid,
        upper(data_area_id) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid

from d365_source

)

select * from renamed
