with d365_source as (
        select *
        from {{ source("D365", "proj_table") }} where _FIVETRAN_DELETED='FALSE'
    ),

    renamed as (

       
        select
            'D365' as source,
            proj_group_id as projgroupid,
            proj_id as projid,
            name as name,
            proj_ledger_posting as projledgerposting,
            created as created,
            start_date as startdate,
            end_date as enddate,
            cust_account as custaccount,
            dlv_name as dlvname,
            proj_invoice_proj_id as projinvoiceprojid,
            email as email,
            null as parentid,
            header as header,
            tax_group_id as taxgroupid,
            format as format,
            check_budget as checkbudget,
            null as sortingid,
            null as sortingid2_,
            null as sortingid3_,
            null as synclasttransid,
            status as status,
            wipproject as wipproject,
            type as type,
            template as template,
            validate_proj_category as validateprojcategory,
            proj_line_property_search as projlinepropertysearch,             
            delivery_location as deliverylocation,             
            default_dimension as defaultdimension,
            null as subject_sa,
            contract_date_sa as contractdate_sa,
            contract_value_sa as contractvalue_sa,
            contract_amendment_sa as contractamendment_sa,
            null as contractperiod_sa,
            require_activity_hour_trx as requireactivityhourtrx,
            require_activity_expense_trx as requireactivityexpensetrx,
            require_activity_item_trx as requireactivityitemtrx,
            require_activity_hour_forecast as requireactivityhourforecast,
            require_activity_expense_forecast as requireactivityexpenseforecast,
            require_activity_item_forecast as requireactivityitemforecast,
            use_budgeting as usebudgeting,
            use_alternate_project as usealternateproject,
            proj_price_group as projpricegroup,
            proj_budget_overrun_option as projbudgetoverrunoption,
            null as syncentityid,
            null as syncversion,
            proj_budgetary_control_on as projbudgetarycontrolon,
            null as synccreatedbyexternal,
            null as assetid,
            projected_start_date as projectedstartdate,
            projected_end_date as projectedenddate,
            extension_date as extensiondate,
            null as alternatebudgetproject,
            proj_budget_interval as projbudgetinterval,
            time_post_detail_summary as timepostdetailsummary,
            min_time_increment as mintimeincrement,
            proj_carry_forward_remaining_budget as projcarryforwardremainingbudget,
            proj_carry_forward_negative_budget as projcarryforwardnegativebudget,             
            worker_responsible_financial as workerresponsiblefinancial,             
            worker_responsible as workerresponsible,             
            worker_responsible_sales as workerresponsiblesales,
            bank_document_type as bankdocumenttype,
            job_id as jobid,
            job_pay_type as jobpaytype,
            null as psaprojtask,
            null as psaunitid,
            null as psatimemeasure,
            null as psatrackcost,
            null as psaforecastmodelid,
            psainvoice_method as psainvoicemethod,
            null as psareadyforinvoicing,
            psado_invoice_cost as psadoinvoicecost,
            null as psanotes,
            psaproj_status as psaprojstatus,
            null as psaforecastmodelidexternal,
            null as psaphone,
            null as psatelefax,
            null as psapreqitemvalidate,
            null as psapreqhourvalidate,
            null as psapreqcontrol,
            psaschedmilestone as psaschedmilestone,
            psasched_start_date as psaschedstartdate,
            psasched_end_date as psaschedenddate,
            psasched_duration as psaschedduration,
            psasched_use_duration as psascheduseduration,
            psasched_calendar_id as psaschedcalendarid,
            psasched_ignore_calendar as psaschedignorecalendar,
            null as psaschedconstrainttype,
            null as psaschedconstraintdate,
            psasched_scheduled as psaschedscheduled,
            null as psaretainscheduleid,
            null as psaretainpercent,
            null as psaretainincludelower,
            psasched_effort as psaschedeffort,
            psasched_from_time as psaschedfromtime,
            psasched_to_time as psaschedtotime,
            null as psascheddefaultdate,
            psares_sched_status as psaresschedstatus,
            complete_scheduled as completescheduled,
            ocip as ocip,
            certified_payroll as certifiedpayroll,
            ocipgl as ocipgl,
            worker_psaarchitect as workerpsaarchitect,
            proj_budget_management as projbudgetmanagement,
            null as synctocrm,
            modifieddatetime as modifieddatetime,
            upper(data_area_id) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid
        from d365_source where upper(dataareaid) in {{env_var("DBT_D365_COMPANY_FILTER")}}

    )

select * from renamed
