with d365_source as (
        select *
        from {{ source("D365", "vend_packing_slip_trans") }} where _FIVETRAN_DELETED='FALSE' and upper(data_area_id) in {{env_var("DBT_D365_COMPANY_FILTER")}}

    ),

renamed as (
select
        'D365' as source,
        packing_slip_id as packingslipid,
        delivery_date as deliverydate,
        line_num as linenum,
        invent_trans_id as inventtransid,
        dest_country_region_id as destcountryregionid,
        item_id as itemid,
        null as externalitemid,
        name as name,
        ordered as ordered,
        qty as qty,
        remain as remain,
        price_unit as priceunit,
        value_mst as valuemst,
        invent_ref_id as inventrefid,
        invent_ref_type as inventreftype,
        purch_unit as purchunit,
        null as transactioncode,
        invent_ref_trans_id as inventreftransid,
        inter_company_invent_trans_id as intercompanyinventtransid,
        dest_state as deststate,
        remain_invent as remaininvent,
        orig_purchid as origpurchid,
        return_action_id as returnactionid,
        null as transport,
        invent_dim_id as inventdimid,
        null as statprocid,
        null as port,
        invent_date as inventdate,
        null as numbersequencegroup,
        dest_county as destcounty,
        intrastat_dispatch_id as intrastatdispatchid,
        invent_qty as inventqty,
        reason_table_ref as reasontableref,
        procurement_category as procurementcategory,
        null as itemcodeid,
        null as origstateid,
        null as origcountryregionid,
        weight as weight,
        default_dimension as defaultdimension,
        source_document_line as sourcedocumentline,
        worker_purchaser as workerpurchaser,
        null as purchaselineexpecteddeldate,
        purchase_line_line_number as purchaselinelinenumber,
        vend_packing_slip_jour as vendpackingslipjour,
        fully_matched as fullymatched,
        cost_ledger_voucher as costledgervoucher,
        accounting_date as accountingdate,
        stocked_product as stockedproduct,
        ngpcodes_table_fr as ngpcodestable_fr,
        received_qty_in as receivedqty_in,
        rejected_qty_in as rejectedqty_in,
        accepted_qty_in as acceptedqty_in,
        invoice_trans_ref_rec_id as invoicetransrefrecid,
        intrastat_fulfillment_date_hu as intrastatfulfillmentdate_hu,
        currency_code_w as currencycode_w,
        deviation_qty_ru as deviationqty_ru,
        excise_value_ru as excisevalue_ru,
        vat_value_ru as vatvalue_ru,
        excise_amount_ru as exciseamount_ru,
        vatamount_ru as vatamount_ru,
        line_amount_w as lineamount_w,
        tax_amount_ru as taxamount_ru,
        null as taxitemgroup_ru,
        null as taxgroup_ru,
        statistic_value_lt as statisticvalue_lt,
        pds_cwordered as pdscwordered,
        pds_cwqty as pdscwqty,
        pds_cwremain as pdscwremain,
        upper(data_area_id) as dataareaid,
        recversion as recversion,
        partition as partition,
        recid as recid

    from d365_source

)

select * from renamed
