with d365_source as (

        select *
        from {{ source("D365", "purch_parm_line") }} where _FIVETRAN_DELETED='FALSE' AND upper(trim(data_area_id)) in {{env_var("DBT_D365_COMPANY_FILTER")}} 
    ),

    renamed as (
        select
            'D365' as source,
            remain_before_invent as remainbeforeinvent,
            remain_after_invent as remainafterinvent,
            invent_now as inventnow,
            remain_after as remainafter,
            remain_before as remainbefore,
            receive_now as receivenow,
            line_num as linenum,
            item_id as itemid,
            delivery_name as deliveryname,
            line_percent as linepercent,
            purch_markup as purchmarkup,
            price_unit as priceunit,
            multi_ln_disc as multilndisc,
            line_disc as linedisc,
            purch_price as purchprice,
            multi_ln_percent as multilnpercent,
            line_amount as lineamount,
            order_account as orderaccount,             
            purch_line_rec_id  as purchlinerecid,
            invoice_account as invoiceaccount,
            parm_id as parmid,
            closed as closed,
            changed_manually as changedmanually,
            currency_code as currencycode,
            invent_trans_id as inventtransid,
            invent_dim_id as inventdimid,
            orig_purch_id as origpurchid,
            null as invoiceinfotablerefid,
            table_ref_id as tablerefid,
            tax_1099_amount as tax1099amount,
            null as tax1099state,
            tax_1099_state_amount as tax1099stateamount,
            null as taxitemgroup,
            null as taxgroup,
            null as description,            
            reason_table_ref as reasontableref,             
            procurement_category as procurementcategory,
            remain_before_invent_physical as remainbeforeinventphysical,
            tax_1099_fields as tax1099fields,             
            delivery_postal_address as deliverypostaladdress,
            purchase_line_line_number as purchaselinelinenumber,
            previous_receive_now as previousreceivenow,
            previous_invent_now as previousinventnow,
            null as postingprofile_ru,
            invent_profile_type_ru as inventprofiletype_ru,
            null as customsimportinvoicenumtbl_in,
            null as customsbillofentrynumtbl_in,
            null as receivedqty_in,
            null as acceptedqty_in,
            null as rejectedqty_in,
            null as assessablevalue_in,
            null as maximumretailprice_in,
            null as customsinvoiceregnrecid_in,
            deviation_qty_ru as deviationqty_ru,
            cfoptable_br as cfoptable_br,
            null as pdscountryoforigin1,
            null as pdscountryoforigin2,
            pds_cwprevious_receive_now as pdscwpreviousreceivenow,
            pds_cwreceive_now as pdscwreceivenow,
            pds_cwremain_after_invent as pdscwremainafterinvent,
            pds_cwremain_before_invent as pdscwremainbeforeinvent,
            pds_use_vend_batch_date as pdsusevendbatchdate,
            pds_use_vend_batch_exp as pdsusevendbatchexp,
            pds_vend_batch_date as pdsvendbatchdate,
            null as pdsvendbatchid,
            pds_vend_expiry_date as pdsvendexpirydate,
            previous_deviation_qty as previousdeviationqty,
            null as taxservicecode_br,
            upper(data_area_id) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid
        from d365_source
    )

select *
from renamed
