with d365_source as (

        select *
        from {{ source("D365", "purch_parm_table") }} where _FIVETRAN_DELETED='FALSE' AND upper(trim(data_area_id)) in {{env_var("DBT_D365_COMPANY_FILTER")}} 
    ),
    renamed as (
        select
            'D365' as source,
            delivery_name as deliveryname,
            purch_id as purchid,
            ordering as ordering,
            batch_administration as batchadministration,
            trans_date as transdate,
            num as num,
            document_date as documentdate,
            null as documentnum,
            null as paymid,
            cash_disc as cashdisc,
            invoice_round_off as invoiceroundoff,
            tax_round_off as taxroundoff,
            end_disc as enddisc,
            purch_name as purchname,
            order_account as orderaccount,
            cash_disc_date as cashdiscdate,
            storno as storno,
            invoice_account as invoiceaccount,
            null as description,
            parm_job_status as parmjobstatus,
            currency_code as currencycode,
            parm_id as parmid,
            log as log,
            to_char(payment) as payment,
            hold as hold,
            vend_invoice_save_status as vendinvoicesavestatus,
            null as paymentsched,
            null as paymmode,
            null as paymspec,
            re_calculate as recalculate,
            null as vendbankaccountid,
            fixed_exch_rate as fixedexchrate,
            eurotriangulation as eurotriangulation,
            exch_rate as exchrate,
            exch_rate_secondary as exchratesecondary,
            fixed_due_date as fixedduedate,
            table_ref_id as tablerefid,
            null as cashdisccode,
            document_origin as documentorigin,
            cash_disc_percent as cashdiscpercent,
            null as taxgroup,
            null as vatnum,
            null as releasedatecomment,
            invoice_release_date as invoicereleasedate,
            invoicereleasedatetzid as invoicereleasedatetzid,
            incl_tax as incltax,
            null as postingprofile,
            null as enterprisenumber,
            end_date_time as enddatetime,
            enddatetimetzid as enddatetimetzid,
            start_date_time as startdatetime,
            startdatetimetzid as startdatetimetzid,
            variance_approved as varianceapproved,
            variance_approved_date_time as varianceapproveddatetime,
            varianceapproveddatetimetzid as varianceapproveddatetimetzid,
            null as variancecomment,
            settle_voucher as settlevoucher,
            null as numbersequencegroup,
            null as transactioncode,
            null as transport,
            null as port,
            null as statprocid,
            null as countyorigdest,
            null as vendinvoicegroup,
            null as vendpaymentgroup,
            last_match_variance as lastmatchvariance,             
            delivery_postal_address as deliverypostaladdress,
            remittance_location as remittancelocation,
            ignore_calculated_sales_tax as ignorecalculatedsalestax,
            workflow_state as workflowstate,
            bank_lcimport_line as banklcimportline,
            electronic_invoice_br as electronicinvoice_br,
            invent_profile_type_ru as inventprofiletype_ru,
            tax_information_in as taxinformation_in,
            null as customsbillofentrynumtbl_in,
            null as customsimportinvoicenumtbl_in,
            null as consignmentnotenum_in,
            null as offsessionid_ru,
            off_report_type_ru as offreporttype_ru,
            null as packingslipidforupdate_w,
            null as docregister_lt,
            null as fiscaldocumentseries_br,
            null as fiscaldocumentmodel_br,
            fiscal_document_specie_br as fiscaldocumentspecie_br,
            fiscal_document_type_br as fiscaldocumenttype_br,
            reason_table_ref_br as reasontableref_br,
            service_code_on_dlv_address_br as servicecodeondlvaddress_br,
            storno_physical_ru as stornophysical_ru,
            vend_final_user_br as vendfinaluser_br,             
            vend_packing_slip_jour as vendpackingslipjour,
            presence_type_br as presencetype_br,
            createddatetime as createddatetime,
            createdby as createdby,
            upper(data_area_id) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid
        from d365_source

    )

select *
from renamed
