with
    d365_source as (

        select *
        from {{ source("D365", "cust_table") }}
        where upper(trim(data_area_id)) in {{ env_var("DBT_D365_COMPANY_FILTER") }} and _FIVETRAN_DELETED='FALSE'
    ),

    renamed as (
        select
            'D365' as source,
            account_num as accountnum,
            invoice_account as invoiceaccount,
            cust_group as custgroup,
            line_disc as linedisc,
            paym_term_id as paymtermid,
            null as cashdisc,
            currency as currency,
            inter_company_auto_create_orders as intercompanyautocreateorders,
            null as salesgroup,
            blocked as blocked,
            one_time_customer as onetimecustomer,
            account_statement as accountstatement,
            credit_max as creditmax,
            mandatory_credit_limit as mandatorycreditlimit,
            vend_account as vendaccount,
            price_group as pricegroup,
            null as multilinedisc,
            null as enddisc,
            vatnum as vatnum,
            invent_location as inventlocation,
            dlv_term as dlvterm,
            dlv_mode as dlvmode,
            markup_group as markupgroup,
            null as clearingperiod,
            null as freightzone,
            null as creditrating,
            tax_group as taxgroup,
            null as statisticsgroup,
            paym_mode as paymmode,
            null as commissiongroup,
            null as bankaccount,
            null as paymsched,
            null as contactpersonid,
            invoice_address as invoiceaddress,
            null as ouraccountnum,
            sales_pool_id as salespoolid,
            incl_tax as incltax,
            null as custitemgroupid,
            null as numbersequencegroup,
            null as paymdayid,
            null as lineofbusinessid,
            null as destinationcodeid,
            giro_type as girotype,
            null as suppitemgroupid,
            giro_type_interest_note as girotypeinterestnote,
            null as taxlicensenum,
            web_sales_order_display as websalesorderdisplay,
            null as paymspec,
            null as bankcentralbankpurposetext,
            null as bankcentralbankpurposecode,
            null as intercoallowindirectcreation,
            null as packmaterialfeelicensenum,
            null as taxbordernumber_fi,
            null as einvoiceeannum,
            null as fiscalcode,
            null as dlvreason,
            forecast_dmpinclude as forecastdmpinclude,
            giro_type_collectionletter as girotypecollectionletter,
            null as salescalendarid,
            cust_classification_id as custclassificationid,
            inter_company_direct_delivery as intercompanydirectdelivery,
            null as enterprisenumber,
            null as shipcarrieraccount,
            giro_type_proj_invoice as girotypeprojinvoice,
            invent_site_id as inventsiteid,
            null as orderentrydeadlinegroupid,
            null as shipcarrierid,
            ship_carrier_fuel_surcharge as shipcarrierfuelsurcharge,
            ship_carrier_blind_shipment as shipcarrierblindshipment,
            null as shipcarrieraccountcode,
            giro_type_free_text_invoice as girotypefreetextinvoice,
            null as syncentityid,
            null as syncversion,
            null as memo,
            null as salesdistrictid,
            null as segmentid,
            null as subsegmentid,
            rfiditemtagging as rfiditemtagging,
            rfidcasetagging as rfidcasetagging,
            rfidpallettagging as rfidpallettagging,
            company_chain_id as companychainid,
            null as companyidsiret,
            party as party,
            null as identificationnumber,
            null as partycountry,
            null as partystate,
            null as orgid,
            null as paymidtype,
            null as factoringaccount,
            default_dimension   as defaultdimension,
            cust_exclude_collection_fee as custexcludecollectionfee,
            cust_exclude_interest_charges as custexcludeinterestcharges,
            company_nafcode as companynafcode,
            bank_cust_paym_id_table as bankcustpaymidtable,
            giro_type_account_statement as girotypeaccountstatement,
            main_contact_worker  as maincontactworker,
            credit_card_address_verification as creditcardaddressverification,
            credit_card_cvc as creditcardcvc,
            null as creditcardaddressverivoid,
            null as creditcardaddressverilevel,
            company_type_mx as companytype_mx,
            null as rfc_mx,
            null as curp_mx,
            null as stateinscription_mx,
            null as residenceforeignctryregid_it,
            null as birthcountycode_it,
            null as birthdate_it,
            null as birthplace_it,
            einvoice as einvoice,
            einvoice_register_it as einvoiceregister_it,
            null as ccmnum_br,
            null as cnpjcpfnum_br,
            null as pbacustgroupid,
            null as ienum_br,
            null as suframanumber_br,
            suframa_br as suframa_br,
            cust_final_user_br as custfinaluser_br,
            null as interestcode_br,
            null as finecode_br,
            suframa_piscofins_br as suframapiscofins_br,
            tax_withhold_calculate_th as taxwithholdcalculate_th,
            null as taxwithholdgroup_th,
            cons_day_jp as consday_jp,
            null as nit_br,
            null as insscei_br,
            null as cnae_br,
            icmscontributor_br as icmscontributor_br,
            service_code_on_dlv_address_br as servicecodeondlvaddress_br,
            invent_profile_type_ru as inventprofiletype_ru,
            null as inventprofileid_ru,
            tax_withhold_calculate_in as taxwithholdcalculate_in,
            united_vatinvoice_lt as unitedvatinvoice_lt,
            null as foreignerid_br,
            null as enterprisecode,
            null as commercialregistersection,
            null as commercialregisterinsetnumber,
            null as commercialregister,
            null as regnum_w,
            is_resident_lv as isresident_lv,
            null as intbank_lv,
            null as paymentreference_ee,
            package_deposit_excempt_pl as packagedepositexcempt_pl,
            fed_non_fed_indicator as fednonfedindicator,
            irs_1099_cindicator as irs1099cindicator,
            null as agencylocationcode,
            null as federalcomments,
            use_purch_request as usepurchrequest,
            null as mcrmergedparent,
            null as mcrmergedroot,
            affiliated_ru as affiliated_ru,
            cash_disc_base_days as cashdiscbasedays,
            cust_trading_partner_code as custtradingpartnercode,
            cust_wht_contribution_type_br as custwhtcontributiontype_br,
            null as daxintegrationid,
            default_direct_debit_mandate as defaultdirectdebitmandate,
            null as defaultinventstatusid,
            entry_certificate_required_w as entrycertificaterequired_w,
            export_sales_pl as exportsales_pl,
            express_bill_of_lading as expressbilloflading,
            fiscal_doc_type_pl as fiscaldoctype_pl,
            foreign_resident_ru as foreignresident_ru,
            null as generateincomingfiscaldoc_br,
            invoice_posting_type_ru as invoicepostingtype_ru,
            issue_own_entry_certificate_w as issueownentrycertificate_w,
            null as issuercountry_hu,
            lv_paym_trans_codes as lvpaymtranscodes,
            mandatory_vat_date_pl as mandatoryvatdate_pl,
            null as passportno_hu,
            null as pdscustrebategroupid,
            pds_freight_accrued as pdsfreightaccrued,
            null as pdsrebatetmagroup,
            null as taxperiodpaymentcode_pl,
            use_cash_disc as usecashdisc,
            null as authorityoffice_it,
            presence_type_br as presencetype_br,
            tax_gstrelief_group_heading_my as taxgstreliefgroupheading_my,
            modifieddatetime as modifieddatetime,
            null as del_modifiedtime,
            modifiedby as modifiedby,
            createddatetime as createddatetime,
            null as del_createdtime,
            upper(trim(data_area_id)) as dataareaid,
            recversion as recversion,
            partition as partition,
            recid as recid,
            null as foreigntaxregistration_mx,
            null as biseancodeid,
            null as bisedipartner,
            null as bisitemcoding,
            null as bisitemcodingbarcodesetupid,
            null as bisitemcodinggtinsetup,
            null as biseanbarcodesetupid,
            null as allowzeroprices,
            null as salestradegroupid,
            null as salestradesectorid,
            null as satpurpose_mx,
            null as satpaymmethod_mx,
            wbxmarket,
            wbxsubmarket,
            wbxtrade_class,
            wbxtrade_type,
            wbxtrade_group,
            wbxtrade_sector,
            wbxone_product_per_pallet,
            wbxcontractor_indicator,
            wbxdelivery_instructions,
            wbxrequested_receipt_time,
            wbxedifti,
            wbxedicredit_note,
            wbxedisales_invoice,
            wbxglninvoice_location,
            wbxglnseller,
            wbxpodrequired,
            wbxpoddelay_in_days,
            wbxasnrequired,
            wbxoverride_delivery_control,
            wbxexclude_from_allocation,
            wbxaccount_number,
            wbxdelivery_date_control_type,
            wbxfull_pallet,
            wbxglndepartment,
            wbxglngoods_receipt,
            wbxglnpayment_receiver,
            wbxglnorder_location,
            wbxglnpayer

        from d365_source

    )

select *
from renamed
qualify row_number() over (partition by accountnum, dataareaid order by source desc) = 1
