{{
    config(
        materialized="view",
        tags=["redzone", "OEE", "v_completeddataitem"],
    )
}}

with source as (

    select * from {{ source('weetabix-org', 'v_completeddataitem') }}

),

renamed as (

select
"productUnitOfMeasureName",
"lowerControlLimit",
"deactivatedTime",
"observationUserSignatureLastName",
"lowerReasonableLimit",
"dateYear",
"createdDate",
"placeType",
"runUUID",
"observationUserSignatureUUID",
"runId",
"placeName",
"lowerSpecLimit",
"siteId",
"completeTime",
"inputFormat",
"week",
"productMaterialCost",
"dataSheetTemplateUUID",
"description",
"quarter",
"dataItemName",
"target",
"placeUUID",
"dataItemTemplateUUID",
"productOverheadCost",
"productSku",
"siteUUID",
"upperControlLimit",
"observationUserSignatureFirstName",
"approvalUserSignatureUserName",
"dayName",
"assetTypeName",
"actionUUID",
"timeZoneId",
"assetName",
"dataSheetSectionId",
"dayOfWeekNumberIso",
"siteName",
"observationUserSignatureUserName",
"customReference",
"userSignatureUserName",
"productStandardRatePerMinute",
"userSignatureUUID",
"characteristicName",
"void",
"comment",
"dayOfWeekNumber",
"productName",
"approvalTime",
"subject",
"userSignatureLastName",
"productCost",
"dataSheetId",
"matchValues",
"processType",
"specStandard",
"userSignatureFirstName",
"hourOfDay",
"deactivatedUserSignatureLastName",
"aggregationMethod",
"auditScore",
"dataSheetSectionName",
"upperReasonableLimit",
"resultType",
"approvalUserSignatureUUID",
"draftTime",
"upperSpecLimit",
"cycleUUID",
"values",
"deactivatedUserSignatureFirstName",
"aggregate",
"deactivatedUserSignatureUUID",
"approvalUserSignatureFirstName",
"quarterName",
"updatedDate",
"approvalUserSignatureLastName",
"dataSheetName",
"monthName",
"entryConsoleType",
"shiftUUID",
"dateTimeNearestHour",
"monthNumber",
"deactivatedUserSignatureUserName",
"shiftName",
"observationTime",
"characteristicUUID",
"runName"
from source

)

select * from renamed
