{{ config(      materialized='view',tags=["redzone","OEE", 'v_losses'],    ) }}

with
    source as (select * from {{ source("weetabix-org", "v_losses") }}),

    renamed as (

        select

            "siteId",
            "problemID",
            "timeZoneId",
            "dateYear",
            "quarter",
            "quarterName",
            "monthNumber",
            "monthName",
            "week",
            "dayName",
            "dayOfWeekNumber",
            "dayOfWeekNumberIso",
            "hourOfDay",
            "dateTimeNearestHour",
            "startTime",
            "endTime",
            "secondsLost",
            "minutesLost",
            "hoursLost",
            "unitsLost",
            "potentialUnitsLost",
            "unitOfMeasureUUID",
            "unitOfMeasureName",
            "runUnitsLost",
            "runPotentialUnitsLost",
            "runUnitOfMeasureUUID",
            "runUnitOfMeasureName",
            "createdDate",
            "updatedDate",
            "locationUUID",
            "locationName",
            "problemTypeAssetTypeUUID",
            "problemTypeAssetTypeName",
            "problemTypeAssetUUID",
            "problemTypeAssetName",
            "areaUUID",
            "areaName",
            "siteUUID",
            "siteName",
            "problemTypeUUID",
            "problemTypeName",
            "problemGroupUUID",
            "problemGroupName",
            "problemReportGroup",
            "problemCategory",
            "problemPlanned",
            "problemCountRelationship",
            "clockType",
            "scheduledClockEndTime",
            "problemTypeAutoAssigned",
            "runUUID",
            "runName",
            "productTypeUUID",
            "customReference",
            "runId",
            "locked",
            "hasQualityChecks",
            "signatureOnHold",
            "runSignatureUsername",
            "runSignatureLastName",
            "runSignatureFirstName",
            "runSignatureTime",
            "runSignatureType",
            "productTypeName",
            "productTypeSKU",
            "productTypeLabelWeight",
            "manufacturingTypeUUID",
            "manufacturingTypeName",
            "shiftUUID",
            "shiftName",
            "productExternalId",
            "productUUID",
            "stationUUID",
            "stationName",
            "stepUUID",
            "stepName"

        from source

    )

select *
from renamed
