{{  config(      materialized='view',tags=["redzone","OEE", 'v_run'],    )}}

with source as (

    select * from {{ source('weetabix-org', 'v_run') }}

),

renamed as (

        select
        "siteId",
        "timeZoneId",
        "dateYear",
        "quarter",
        "quarterName",
        "monthNumber",
        "monthName",
        "week",
        "dayName",
        "dayOfWeekNumber",
        "dayOfWeekNumberIso",
        "hourOfDay",
        "dateTimeNearestHour",
        "areaUUID",
        "areaName",
        "siteUUID",
        "siteName",
        "siteUnitOfMeasureUUID",
        "siteUnitOfMeasureName",
        "runUUID",
        "runName",
        "runScheduledStartTime",
        "runStartTime",
        "runEndTime",
        "unitOfMeasureUUID",
        "unitOfMeasureName",
        "manufacturingTypeUUID",
        "manufacturingTypeName",
        "autoStopped",
        "averageCrewSize",
        "averageStandardRatePerMin",
        "averageStandardRatePerManHour",
        "plannedQuantity",
        "manHours",
        "productTypeUUID",
        "productTypeName",
        "productTypeSKU",
        "productTypeLabelWeight",
        "locationUUID",
        "locationName",
        "sensorConfigurationUUID",
        "sensorConfigurationMode",
        "sensorConfigurationName",
        "customReference",
        "productionType",
        "runId",
        "locked",
        "hasQualityChecks",
        "signatureOnHold",
        "splitSource",
        "splitRemainder",
        "runSignatureUsername",
        "runSignatureLastName",
        "runSignatureFirstName",
        "runSignatureTime",
        "runSignatureType",
        "inCount",
        "outCount",
        "siteOutputQuantity",
        "theoreticalQuantity",
        "oee",
        "target",
        "offsetTarget",
        "edgeUpTarget",
        "minimumTarget",
        "targetQuantity",
        "offsetTargetQuantity",
        "edgeUpTargetQuantity",
        "minimumTargetQuantity",
        "quality",
        "availability",
        "performance",
        "upSeconds",
        "downSeconds",
        "plannedDownSeconds",
        "leadOperatorUUID",
        "leadOperatorUsername",
        "leadOperatorFirstName",
        "leadOperatorLastName",
        "leadOperatorStartTime",
        "reportingInCount",
        "reportingOutCount",
        "reportingTheoreticalQuantity",
        "reportingTargetQuantity",
        "reportingOffsetTargetQuantity",
        "reportingEdgeUpTargetQuantity",
        "reportingMinimumTargetQuantity",
        "rolledThroughputYield"
        
    from source
    
)

select * from renamed
