{{  config(      materialized='view',tags=["redzone","OEE", 'v_shiftrunsegment'],    )}}

with source as (

    select * from {{ source('weetabix-org', 'v_shiftrunsegment') }}

),

renamed as (

select
        "siteId",
        "timeZoneId",
        "dateYear",
        "quarter",
        "quarterName",
        "monthNumber",
        "monthName",
        "week",
        "dayName",
        "dayOfWeekNumber",
        "dayOfWeekNumberIso",
        "hourOfDay",
        "dateTimeNearestHour",
        "areaUUID",
        "areaName",
        "siteUUID",
        "siteName",
        "siteUnitOfMeasureUUID",
        "siteUnitOfMeasureName",
        "shiftUUID",
        "shiftName",
        "startTime",
        "endTime",
        "runUnitOfMeasureUUID",
        "runUnitOfMeasureName",
        "shiftUnitOfMeasureUUID",
        "shiftUnitOfMeasureName",
        "locationUUID",
        "locationName",
        "productionType",
        "runUUID",
        "runName",
        "productTypeUUID",
        "customReference",
        "runId",
        "locked",
        "hasQualityChecks",
        "signatureOnHold",
        "runStandardRatePerMin",
        "productTypeName",
        "productTypeSKU",
        "productTypeLabelWeight",
        "manufacturingTypeUUID",
        "manufacturingTypeName",
        "runSignatureUsername",
        "runSignatureLastName",
        "runSignatureFirstName",
        "runSignatureTime",
        "runSignatureType",
        "inCount",
        "outCount",
        "siteOutputQuantity",
        "theoreticalQuantity",
        "oee",
        "target",
        "offsetTarget",
        "edgeUpTarget",
        "minimumTarget",
        "targetQuantity",
        "offsetTargetQuantity",
        "edgeUpTargetQuantity",
        "minimumTargetQuantity",
        "quality",
        "availability",
        "performance",
        "upSeconds",
        "downSeconds",
        "plannedDownSeconds",
        "manHours",
        "runInCount",
        "runOutCount",
        "runTheoreticalQuantity",
        "runTargetQuantity",
        "runOffsetTargetQuantity",
        "runEdgeUpTargetQuantity",
        "runMinimumTargetQuantity",
        "createdDate",
        "updatedDate",
        "leadOperatorUUID",
        "leadOperatorUsername",
        "leadOperatorFirstName",
        "leadOperatorLastName",
        "reportingInCount",
        "reportingOutCount",
        "reportingTheoreticalQuantity",
        "reportingTargetQuantity",
        "reportingOffsetTargetQuantity",
        "reportingEdgeUpTargetQuantity",
        "reportingMinimumTargetQuantity"
    from source
)

select * from renamed