

with source as (

    select * from {{ source('WEETABIX', 'prodtable') }}

),

renamed as (

    select
        projlinkedtoorder,
        itemid,
        name,
        prodgroupid,
        prodstatus,
        prodprio,
        prodlocked,
        prodtype,
        schedstatus,
        scheddate,
        qtysched,
        qtystup,
        dlvdate,
        stupdate,
        finisheddate,
        schedstart,
        schedend,
        defaultdimension,
        height,
        width,
        depth,
        density,
        qtycalc,
        realdate,
        reservation,
        prodpostingtype,
        inventtransid,
        inventreftype,
        inventrefid,
        inventreftransid,
        collectreflevel,
        collectrefprodid,
        bomdate,
        backorderstatus,
        prodpoolid,
        profitset,
        calcdate,
        routejobs,
        checkroute,
        propertyid,
        remaininventphysical,
        bomid,
        routeid,
        reqplanidsched,
        reqpoid,
        reflookup,
        latestscheddirection,
        latestscheddate,
        prodid,
        inventdimid,
        schedtotime,
        schedfromtime,
        latestschedtime,
        dlvtime,
        prodorigid,
        ganttcolorid,
        projid,
        projpostingtype,
        projcategoryid,
        projlinepropertyid,
        projtransid,
        projcostprice,
        projcostamount,
        projsalescurrencyid,
        projsalesunitid,
        projsalesprice,
        projtaxgroupid,
        projtaxitemgroupid,
        activitynumber,
        pricegroup_ru,
        currencycode_ru,
        pbaid,
        pmftotalcostallocation,
        pdscwbatchest,
        pdscwbatchsched,
        pdscwbatchsize,
        pdscwbatchstup,
        pdscwremaininventphysical,
        pmfbulkord,
        pmfcobyvarallow,
        pmfconsordid,
        pmfreworkbatch,
        pmfyieldpct,
        prodwhsreleasepolicy,
        releaseddate,
        createddatetime,
        del_createdtime,
        createdby,
        dataareaid,
        recversion,
        partition,
        recid,
        prodimported,
        qtymade,
        statuschangedby

    from source

)

select * from renamed
