

with source as (

    select * from {{ source('WEETABIX', 'inventlocation') }}

),

renamed as (

    select
        inventlocationid,
        name,
        manual,
        emptypalletlocation,
        maxpickingroutevolume,
        pickinglinetime,
        maxpickingroutetime,
        wmslocationiddefaultreceipt,
        wmslocationiddefaultissue,
        inventlocationidreqmain,
        reqrefill,
        inventlocationtype,
        inventlocationidquarantine,
        inventlocationlevel,
        reqcalendarid,
        wmsaislenameactive,
        wmsracknameactive,
        wmsrackformat,
        wmslevelnameactive,
        wmslevelformat,
        wmspositionnameactive,
        wmspositionformat,
        usewmsorders,
        inventlocationidtransit,
        vendaccount,
        branchnumber,
        inventsiteid,
        inventcountinggroup_br,
        custaccount_br,
        inventprofiletype_ru,
        inventprofileid_ru,
        inventlocidgoodsinroute_ru,
        wmslocidgoodsinroute_ru,
        activitytype_ru,
        numbersequencegroup_ru,
        retailweightex1,
        fshstore,
        rbodefaultwmspalletid,
        rbodefaultwmslocationid,
        rbodefaultinventprofileid_ru,
        allowlaborstandards,
        allowmarkingreservationremoval,
        consolidateshipatrtw,
        custaccount_hu,
        cyclecountallowpalletmove,
        decrementloadline,
        dfltkanbanfinishedgoodsloc,
        dfltproductionfinishgoodsloc,
        defaultshipmaintenanceloc,
        defaultstatusid,
        printbolbeforeshipconfirm,
        prodreserveonlywhse,
        removeinventblockonstatchange,
        reserveatloadpost,
        retailinventnegfinancial,
        retailinventnegphysical,
        retailwmslociddefaultreturn,
        retailwmspalletiddfltreturn,
        uniquecheckdigits,
        vendaccountcustom_ru,
        warehouseautoreleaseres,
        whsenabled,
        defaultproductioninputloc,
        defaultreturncreditonlyloc,
        modifieddatetime,
        del_modifiedtime,
        modifiedby,
        createddatetime,
        del_createdtime,
        createdby,
        dataareaid,
        recversion,
        partition,
        recid,
        wbxtooutbound,
        wbxproposedefaultvariant,
        whsrawmaterialpolicy,
        wbxinventlocationid,
        wbxinventsiteid,
        wbxwmstransferenabled,
        biseancodeid,
        defaultcontainertypecode,
        defaultshipdirectlocation,
        includedemandforecast

    from source

)

select * from renamed
