with source as (

    select * from {{ source('WEETABIX', 'custinvoicejour') }}

),

renamed as (

    select
        custgroup,
        refnum,
        salesid,
        orderaccount,
        invoiceaccount,
        invoicedate,
        duedate,
        cashdisc,
        cashdiscdate,
        qty,
        volume,
        weight,
        sumlinedisc,
        salesbalance,
        enddisc,
        invoiceamount,
        currencycode,
        exchrate,
        invoiceid,
        ledgervoucher,
        updated,
        onaccountamount,
        taxprintoninvoice,
        listcode,
        documentnum,
        documentdate,
        cashdiscpercent,
        intrastatdispatch,
        deliveryname,
        enterprisenumber,
        purchaseorder,
        dlvterm,
        dlvmode,
        payment,
        cashdisccode,
        invoiceroundoff,
        summarkup,
        covstatus,
        returnitemnum,
        postingprofile,
        backorder,
        prepayment,
        taxgroup,
        taxitemgroup,
        taxspecifybyline,
        einvoicelinespecific,
        onetimecustomer,
        paymentsched,
        sumtax,
        salestype,
        einvoiceaccountcode,
        intercompanyposted,
        parmid,
        returnreasoncodeid,
        eusaleslist,
        exchratesecondary,
        triangulation,
        customerref,
        vatnum,
        numbersequencegroup,
        languageid,
        incltax,
        log,
        paymdayid,
        invoicingname,
        girotype,
        contactpersonid,
        salesoriginid,
        billofladingid,
        inventlocationid,
        fixedduedate,
        invoiceamountmst,
        invoiceroundoffmst,
        summarkupmst,
        sumlinediscmst,
        enddiscmst,
        salesbalancemst,
        sumtaxmst,
        printmgmtsiteid,
        returnstatus,
        intercompanycompanyid,
        intercompanypurchid,
        printedoriginals,
        proforma,
        rcsaleslist_uk,
        reversecharge_uk,
        deliverypostaladdress,
        invoicepostaladdress,
        sourcedocumentheader,
        defaultdimension,
        banklcexportline,
        workersalestaker,
        reversedrecid,
        receiptdateconfirmed_es,
        paymid,
        taxinvoicesalesid,
        intrastatfulfillmentdate_hu,
        mcremail,
        mcrpaymamount,
        mcrdueamount,
        cashdiscbasedate,
        directdebitmandate,
        iscorrection,
        reasontableref,
        sourcedocumentline,
        transportationdocument,
        modifieddatetime,
        createddatetime,
        del_createdtime,
        createdby,
        upper(trim(dataareaid)) as dataareaid,
        recversion,
        partition,
        recid,
        bisediprocess,
        provisionalassessment_in,
        invoiceidentification_in

    from source

)

select * from renamed
