with source as (

    select * from {{ source('WEETABIX', 'purchparmtable') }}

),

renamed as (

    select
        deliveryname,
        purchid,
        ordering,
        batchadministration,
        transdate,
        num,
        documentdate,
        documentnum,
        paymid,
        cashdisc,
        invoiceroundoff,
        taxroundoff,
        enddisc,
        purchname,
        orderaccount,
        cashdiscdate,
        storno,
        invoiceaccount,
        description,
        parmjobstatus,
        currencycode,
        parmid,
        log,
        payment,
        hold,
        vendinvoicesavestatus,
        paymentsched,
        paymmode,
        paymspec,
        recalculate,
        vendbankaccountid,
        fixedexchrate,
        eurotriangulation,
        exchrate,
        exchratesecondary,
        fixedduedate,
        tablerefid,
        cashdisccode,
        documentorigin,
        cashdiscpercent,
        taxgroup,
        vatnum,
        releasedatecomment,
        invoicereleasedate,
        invoicereleasedatetzid,
        incltax,
        postingprofile,
        enterprisenumber,
        enddatetime,
        enddatetimetzid,
        startdatetime,
        startdatetimetzid,
        varianceapproved,
        varianceapproveddatetime,
        varianceapproveddatetimetzid,
        variancecomment,
        settlevoucher,
        numbersequencegroup,
        transactioncode,
        transport,
        port,
        statprocid,
        countyorigdest,
        vendinvoicegroup,
        vendpaymentgroup,
        lastmatchvariance,
        deliverypostaladdress,
        remittancelocation,
        ignorecalculatedsalestax,
        workflowstate,
        banklcimportline,
        electronicinvoice_br,
        inventprofiletype_ru,
        taxinformation_in,
        customsbillofentrynumtbl_in,
        customsimportinvoicenumtbl_in,
        consignmentnotenum_in,
        offsessionid_ru,
        offreporttype_ru,
        packingslipidforupdate_w,
        docregister_lt,
        fiscaldocumentseries_br,
        fiscaldocumentmodel_br,
        fiscaldocumentspecie_br,
        fiscaldocumenttype_br,
        reasontableref_br,
        servicecodeondlvaddress_br,
        stornophysical_ru,
        vendfinaluser_br,
        vendpackingslipjour,
        presencetype_br,
        createddatetime,
        createdby,
        dataareaid,
        recversion,
        partition,
        recid

    from source

)

select * from renamed